channels:
- http://ssb.stsci.edu/astroconda-dev
- defaults
dependencies:
- asdf=2.3.1
- astropy>=3.1.2
- astroquery=0.3.9
- bokeh=1.2.0
- crds>=7.2.7
- django=2.2.1
- inflection=0.3.1
- ipython=7.6.1
- jinja2=2.10
- jsonschema>=3.0.1
- jwst=0.13.1
- matplotlib=3.1.0
- numpy=1.16.4
- numpydoc=0.9.0
- pandas=0.24.2
- postgresql=9.6.6
- psycopg2=2.7.5
- python=3.6.4
- python-dateutil=2.7.5
- pytest=5.0.1
- pytest-cov=2.6.1
- pytest-html=1.19.0
- sphinx=2.1.0
- sphinx_rtd_theme=0.1.9
- sqlalchemy=1.3.5
- sqlparse=0.3.0
- stsci_rtd_theme=0.0.2
- twine=1.13.0
- pip:
  - authlib==0.10
  - codecov==2.0.15
  - jwedb>=0.0.3
  - pysiaf==0.3.1
  - sphinx-automodapi==0.10
