os: linux
language: python
env:
  - TRAVIS_CI=TRAVIS_CI
deploy:
  provider: pypi
  user: Trim21
  password:
    secure: NMXryZC93Ve08CCbdvjvfBfymNN88KVhgEodyqxQIxtpgfbWsG+JmN1wKeSgV/KIy2JNS11h1gcDlQeE7fa8EcHCKnHziK/VAIAWPBw6JbiqAYROAWKHiGV+xY1WU3RSc6p1guoqXTW/h4OnLOJGqTNtd7eAF5ENqf36jsxfOgEXohY6tY6urHbMronvJGeALPGw0g5Gk69Wqd7Yptw3xiQW+wzVIi5Wru9fG+/t6jPYaf5gr7aQoQjBKlmjKmEhJpiRall6jaNfruQ7ni1KzDHmoRKoribVcNJr8vyecmcWR23WLFxGatSxBBjj3zVYvL1n3PN0edMwlwXzImBwwRnpBtXX/L2h+wvZ9KrUDS3nDocUEes2gHPi2r/FixSLOH1e8+bk9tLN9lZoJ4iAhOAR9zbMSCl/PZJ+C5ZtZUWnnCtLN+jav2cN5Gnw8t1Hzkk58rXzAB/LgS67zTkqhMjhsYcPDxYYKkQT0wRP/8AuSF67+X31Ku8Zf/A2gPSjYnPilmXotXwyIMDufP4KFPt5EakA8rzethJyvq2JftAm+hTkwUIQQXIWEegfpyOwZUE1gMKeGd0CCaNes6e7JfKK0oBH4rUOJ1l8c+D7TK88G4z0ERmmiS1MwVIkW2fN4PNROCn8eohdBY7KFh+ikQ+7GH+dm0PZoeB08kmS7Q4=
  skip_cleanup: true
  on:
    tags: true
    branch: master
    python: '3.6'
  distributions: "sdist" # Your distributions here

cache:
  pip: true
  directories:
    - "$HOME/virtualenv"

python:
  - 3.4
  - 3.5
  - 3.6

install:
  - python setup.py install
  - pip install codecov
script:
  - coverage run -a -m unittest test.client
  - coverage run -a -m unittest test.top
  - coverage run -a -m unittest test.torrent
  - coverage run -a -m unittest test.utils
after_success:
  - codecov
