# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_data', '0005_auto_20190604_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lieu, établissement'),
        ),
    ]
