# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-05 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hd_data', '0007_auto_20190605_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationevent',
            old_name='adress',
            new_name='address',
        ),
    ]
