# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-26 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_data', '0012_auto_20190626_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='porteur',
            field=models.BooleanField(choices=[(True, 'Porteur'), (False, 'Membre')], default=True, verbose_name='Porteur de cellule'),
        ),
    ]
