# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-27 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_data', '0013_auto_20190626_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collective',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mail'),
        ),
    ]
