# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-28 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hd_data', '0016_auto_20190628_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='workwish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hd_data.Workwish'),
        ),
    ]
