[tool.poetry]
name = "autopub"
version = "0.1.0-alpha.20"
description = "Automatic package release upon pull request merge"
authors = ["Justin Mayer <entrop@gmail.com>"]
license = "AGPL-3.0"
readme = "README.md"
keywords = ["automatic", "packaging", "publish", "release", "version"]

[tool.poetry.dependencies]
python = "^3.7"
tomlkit = "^0.5.5"
githubrelease = {version = "^1.5.8",optional = true}

[tool.poetry.dev-dependencies]
black = {version = "^19.3b0",allows-prereleases = true}
githubrelease = "^1.5"

[tool.poetry.extras]
github = ["githubrelease"]

[tool.poetry.scripts]
autopub = "autopub.autopub:main"

[tool.black]
line-length = 85

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
