
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-15T18:26:43+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a3820e5d7dc86a60398f130b96f06558d2498f38",
 "version": "0.12.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
