
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-25T16:57:20-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "29f22315e1071b4ef72901b69931f917dbab03f7",
 "version": "1.1.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
