depends = ('ITKPyBase', 'ITKSpatialObjects', 'ITKCommon', )
templates = (
  ('BoxSpatialObjectToVTKPolyDataFilter', 'itk::BoxSpatialObjectToVTKPolyDataFilter', 'itkBoxSpatialObjectToVTKPolyDataFilter2', True, '2'),
  ('BoxSpatialObjectToVTKPolyDataFilter', 'itk::BoxSpatialObjectToVTKPolyDataFilter', 'itkBoxSpatialObjectToVTKPolyDataFilter3', True, '3'),
  ('ImageToVTKImageFilter', 'itk::ImageToVTKImageFilter', 'itkImageToVTKImageFilterIUC2', True, 'itk::Image< unsigned char,2 >'),
  ('ImageToVTKImageFilter', 'itk::ImageToVTKImageFilter', 'itkImageToVTKImageFilterIUC3', True, 'itk::Image< unsigned char,3 >'),
  ('ImageToVTKImageFilter', 'itk::ImageToVTKImageFilter', 'itkImageToVTKImageFilterIUL2', True, 'itk::Image< unsigned long,2 >'),
  ('ImageToVTKImageFilter', 'itk::ImageToVTKImageFilter', 'itkImageToVTKImageFilterIUL3', True, 'itk::Image< unsigned long,3 >'),
  ('ImageToVTKImageFilter', 'itk::ImageToVTKImageFilter', 'itkImageToVTKImageFilterISS2', True, 'itk::Image< signed short,2 >'),
  ('ImageToVTKImageFilter', 'itk::ImageToVTKImageFilter', 'itkImageToVTKImageFilterISS3', True, 'itk::Image< signed short,3 >'),
  ('ImageToVTKImageFilter', 'itk::ImageToVTKImageFilter', 'itkImageToVTKImageFilterIUS2', True, 'itk::Image< unsigned short,2 >'),
  ('ImageToVTKImageFilter', 'itk::ImageToVTKImageFilter', 'itkImageToVTKImageFilterIUS3', True, 'itk::Image< unsigned short,3 >'),
  ('ImageToVTKImageFilter', 'itk::ImageToVTKImageFilter', 'itkImageToVTKImageFilterIF2', True, 'itk::Image< float,2 >'),
  ('ImageToVTKImageFilter', 'itk::ImageToVTKImageFilter', 'itkImageToVTKImageFilterIF3', True, 'itk::Image< float,3 >'),
  ('ImageToVTKImageFilter', 'itk::ImageToVTKImageFilter', 'itkImageToVTKImageFilterIRGBUC2', True, 'itk::Image< itk::RGBPixel< unsigned char >,2 >'),
  ('ImageToVTKImageFilter', 'itk::ImageToVTKImageFilter', 'itkImageToVTKImageFilterIRGBUC3', True, 'itk::Image< itk::RGBPixel< unsigned char >,3 >'),
  ('ImageToVTKImageFilter', 'itk::ImageToVTKImageFilter', 'itkImageToVTKImageFilterIRGBAUC2', True, 'itk::Image< itk::RGBAPixel< unsigned char >,2 >'),
  ('ImageToVTKImageFilter', 'itk::ImageToVTKImageFilter', 'itkImageToVTKImageFilterIRGBAUC3', True, 'itk::Image< itk::RGBAPixel< unsigned char >,3 >'),
  ('ImageToVTKImageFilter', 'itk::ImageToVTKImageFilter', 'itkImageToVTKImageFilterIVF22', True, 'itk::Image< itk::Vector< float,2 >,2 >'),
  ('ImageToVTKImageFilter', 'itk::ImageToVTKImageFilter', 'itkImageToVTKImageFilterIVF23', True, 'itk::Image< itk::Vector< float,2 >,3 >'),
  ('ImageToVTKImageFilter', 'itk::ImageToVTKImageFilter', 'itkImageToVTKImageFilterIVF32', True, 'itk::Image< itk::Vector< float,3 >,2 >'),
  ('ImageToVTKImageFilter', 'itk::ImageToVTKImageFilter', 'itkImageToVTKImageFilterIVF33', True, 'itk::Image< itk::Vector< float,3 >,3 >'),
  ('ImageToVTKImageFilter', 'itk::ImageToVTKImageFilter', 'itkImageToVTKImageFilterIVF42', True, 'itk::Image< itk::Vector< float,4 >,2 >'),
  ('ImageToVTKImageFilter', 'itk::ImageToVTKImageFilter', 'itkImageToVTKImageFilterIVF43', True, 'itk::Image< itk::Vector< float,4 >,3 >'),
  ('ImageToVTKImageFilter', 'itk::ImageToVTKImageFilter', 'itkImageToVTKImageFilterICVF22', True, 'itk::Image< itk::CovariantVector< float,2 >,2 >'),
  ('ImageToVTKImageFilter', 'itk::ImageToVTKImageFilter', 'itkImageToVTKImageFilterICVF23', True, 'itk::Image< itk::CovariantVector< float,2 >,3 >'),
  ('ImageToVTKImageFilter', 'itk::ImageToVTKImageFilter', 'itkImageToVTKImageFilterICVF32', True, 'itk::Image< itk::CovariantVector< float,3 >,2 >'),
  ('ImageToVTKImageFilter', 'itk::ImageToVTKImageFilter', 'itkImageToVTKImageFilterICVF33', True, 'itk::Image< itk::CovariantVector< float,3 >,3 >'),
  ('ImageToVTKImageFilter', 'itk::ImageToVTKImageFilter', 'itkImageToVTKImageFilterICVF42', True, 'itk::Image< itk::CovariantVector< float,4 >,2 >'),
  ('ImageToVTKImageFilter', 'itk::ImageToVTKImageFilter', 'itkImageToVTKImageFilterICVF43', True, 'itk::Image< itk::CovariantVector< float,4 >,3 >'),
  ('SpatialObjectToVTKPolyDataFilter', 'itk::SpatialObjectToVTKPolyDataFilter', 'itkSpatialObjectToVTKPolyDataFilter2', True, '2'),
  ('SpatialObjectToVTKPolyDataFilter', 'itk::SpatialObjectToVTKPolyDataFilter', 'itkSpatialObjectToVTKPolyDataFilter3', True, '3'),
  ('VTKImageExportBase', 'itk::VTKImageExportBase', 'itkVTKImageExportBase', True),
  ('VTKImageExport', 'itk::VTKImageExport', 'itkVTKImageExportIUC2', True, 'itk::Image< unsigned char,2 >'),
  ('VTKImageExport', 'itk::VTKImageExport', 'itkVTKImageExportIUC3', True, 'itk::Image< unsigned char,3 >'),
  ('VTKImageExport', 'itk::VTKImageExport', 'itkVTKImageExportIUL2', True, 'itk::Image< unsigned long,2 >'),
  ('VTKImageExport', 'itk::VTKImageExport', 'itkVTKImageExportIUL3', True, 'itk::Image< unsigned long,3 >'),
  ('VTKImageExport', 'itk::VTKImageExport', 'itkVTKImageExportISS2', True, 'itk::Image< signed short,2 >'),
  ('VTKImageExport', 'itk::VTKImageExport', 'itkVTKImageExportISS3', True, 'itk::Image< signed short,3 >'),
  ('VTKImageExport', 'itk::VTKImageExport', 'itkVTKImageExportIUS2', True, 'itk::Image< unsigned short,2 >'),
  ('VTKImageExport', 'itk::VTKImageExport', 'itkVTKImageExportIUS3', True, 'itk::Image< unsigned short,3 >'),
  ('VTKImageExport', 'itk::VTKImageExport', 'itkVTKImageExportIF2', True, 'itk::Image< float,2 >'),
  ('VTKImageExport', 'itk::VTKImageExport', 'itkVTKImageExportIF3', True, 'itk::Image< float,3 >'),
  ('VTKImageExport', 'itk::VTKImageExport', 'itkVTKImageExportIRGBUC2', True, 'itk::Image< itk::RGBPixel< unsigned char >,2 >'),
  ('VTKImageExport', 'itk::VTKImageExport', 'itkVTKImageExportIRGBUC3', True, 'itk::Image< itk::RGBPixel< unsigned char >,3 >'),
  ('VTKImageExport', 'itk::VTKImageExport', 'itkVTKImageExportIRGBAUC2', True, 'itk::Image< itk::RGBAPixel< unsigned char >,2 >'),
  ('VTKImageExport', 'itk::VTKImageExport', 'itkVTKImageExportIRGBAUC3', True, 'itk::Image< itk::RGBAPixel< unsigned char >,3 >'),
  ('VTKImageExport', 'itk::VTKImageExport', 'itkVTKImageExportIVF22', True, 'itk::Image< itk::Vector< float,2 >,2 >'),
  ('VTKImageExport', 'itk::VTKImageExport', 'itkVTKImageExportIVF23', True, 'itk::Image< itk::Vector< float,2 >,3 >'),
  ('VTKImageExport', 'itk::VTKImageExport', 'itkVTKImageExportIVF32', True, 'itk::Image< itk::Vector< float,3 >,2 >'),
  ('VTKImageExport', 'itk::VTKImageExport', 'itkVTKImageExportIVF33', True, 'itk::Image< itk::Vector< float,3 >,3 >'),
  ('VTKImageExport', 'itk::VTKImageExport', 'itkVTKImageExportIVF42', True, 'itk::Image< itk::Vector< float,4 >,2 >'),
  ('VTKImageExport', 'itk::VTKImageExport', 'itkVTKImageExportIVF43', True, 'itk::Image< itk::Vector< float,4 >,3 >'),
  ('VTKImageExport', 'itk::VTKImageExport', 'itkVTKImageExportICVF22', True, 'itk::Image< itk::CovariantVector< float,2 >,2 >'),
  ('VTKImageExport', 'itk::VTKImageExport', 'itkVTKImageExportICVF23', True, 'itk::Image< itk::CovariantVector< float,2 >,3 >'),
  ('VTKImageExport', 'itk::VTKImageExport', 'itkVTKImageExportICVF32', True, 'itk::Image< itk::CovariantVector< float,3 >,2 >'),
  ('VTKImageExport', 'itk::VTKImageExport', 'itkVTKImageExportICVF33', True, 'itk::Image< itk::CovariantVector< float,3 >,3 >'),
  ('VTKImageExport', 'itk::VTKImageExport', 'itkVTKImageExportICVF42', True, 'itk::Image< itk::CovariantVector< float,4 >,2 >'),
  ('VTKImageExport', 'itk::VTKImageExport', 'itkVTKImageExportICVF43', True, 'itk::Image< itk::CovariantVector< float,4 >,3 >'),
  ('VTKImageImport', 'itk::VTKImageImport', 'itkVTKImageImportIUC2', True, 'itk::Image< unsigned char,2 >'),
  ('VTKImageImport', 'itk::VTKImageImport', 'itkVTKImageImportIUC3', True, 'itk::Image< unsigned char,3 >'),
  ('VTKImageImport', 'itk::VTKImageImport', 'itkVTKImageImportIUL2', True, 'itk::Image< unsigned long,2 >'),
  ('VTKImageImport', 'itk::VTKImageImport', 'itkVTKImageImportIUL3', True, 'itk::Image< unsigned long,3 >'),
  ('VTKImageImport', 'itk::VTKImageImport', 'itkVTKImageImportISS2', True, 'itk::Image< signed short,2 >'),
  ('VTKImageImport', 'itk::VTKImageImport', 'itkVTKImageImportISS3', True, 'itk::Image< signed short,3 >'),
  ('VTKImageImport', 'itk::VTKImageImport', 'itkVTKImageImportIUS2', True, 'itk::Image< unsigned short,2 >'),
  ('VTKImageImport', 'itk::VTKImageImport', 'itkVTKImageImportIUS3', True, 'itk::Image< unsigned short,3 >'),
  ('VTKImageImport', 'itk::VTKImageImport', 'itkVTKImageImportIF2', True, 'itk::Image< float,2 >'),
  ('VTKImageImport', 'itk::VTKImageImport', 'itkVTKImageImportIF3', True, 'itk::Image< float,3 >'),
  ('VTKImageImport', 'itk::VTKImageImport', 'itkVTKImageImportIRGBUC2', True, 'itk::Image< itk::RGBPixel< unsigned char >,2 >'),
  ('VTKImageImport', 'itk::VTKImageImport', 'itkVTKImageImportIRGBUC3', True, 'itk::Image< itk::RGBPixel< unsigned char >,3 >'),
  ('VTKImageImport', 'itk::VTKImageImport', 'itkVTKImageImportIRGBAUC2', True, 'itk::Image< itk::RGBAPixel< unsigned char >,2 >'),
  ('VTKImageImport', 'itk::VTKImageImport', 'itkVTKImageImportIRGBAUC3', True, 'itk::Image< itk::RGBAPixel< unsigned char >,3 >'),
  ('VTKImageImport', 'itk::VTKImageImport', 'itkVTKImageImportIVF22', True, 'itk::Image< itk::Vector< float,2 >,2 >'),
  ('VTKImageImport', 'itk::VTKImageImport', 'itkVTKImageImportIVF23', True, 'itk::Image< itk::Vector< float,2 >,3 >'),
  ('VTKImageImport', 'itk::VTKImageImport', 'itkVTKImageImportIVF32', True, 'itk::Image< itk::Vector< float,3 >,2 >'),
  ('VTKImageImport', 'itk::VTKImageImport', 'itkVTKImageImportIVF33', True, 'itk::Image< itk::Vector< float,3 >,3 >'),
  ('VTKImageImport', 'itk::VTKImageImport', 'itkVTKImageImportIVF42', True, 'itk::Image< itk::Vector< float,4 >,2 >'),
  ('VTKImageImport', 'itk::VTKImageImport', 'itkVTKImageImportIVF43', True, 'itk::Image< itk::Vector< float,4 >,3 >'),
  ('VTKImageImport', 'itk::VTKImageImport', 'itkVTKImageImportICVF22', True, 'itk::Image< itk::CovariantVector< float,2 >,2 >'),
  ('VTKImageImport', 'itk::VTKImageImport', 'itkVTKImageImportICVF23', True, 'itk::Image< itk::CovariantVector< float,2 >,3 >'),
  ('VTKImageImport', 'itk::VTKImageImport', 'itkVTKImageImportICVF32', True, 'itk::Image< itk::CovariantVector< float,3 >,2 >'),
  ('VTKImageImport', 'itk::VTKImageImport', 'itkVTKImageImportICVF33', True, 'itk::Image< itk::CovariantVector< float,3 >,3 >'),
  ('VTKImageImport', 'itk::VTKImageImport', 'itkVTKImageImportICVF42', True, 'itk::Image< itk::CovariantVector< float,4 >,2 >'),
  ('VTKImageImport', 'itk::VTKImageImport', 'itkVTKImageImportICVF43', True, 'itk::Image< itk::CovariantVector< float,4 >,3 >'),
  ('VTKImageToImageFilter', 'itk::VTKImageToImageFilter', 'itkVTKImageToImageFilterIUC2', True, 'itk::Image< unsigned char,2 >'),
  ('VTKImageToImageFilter', 'itk::VTKImageToImageFilter', 'itkVTKImageToImageFilterIUC3', True, 'itk::Image< unsigned char,3 >'),
  ('VTKImageToImageFilter', 'itk::VTKImageToImageFilter', 'itkVTKImageToImageFilterIUL2', True, 'itk::Image< unsigned long,2 >'),
  ('VTKImageToImageFilter', 'itk::VTKImageToImageFilter', 'itkVTKImageToImageFilterIUL3', True, 'itk::Image< unsigned long,3 >'),
  ('VTKImageToImageFilter', 'itk::VTKImageToImageFilter', 'itkVTKImageToImageFilterISS2', True, 'itk::Image< signed short,2 >'),
  ('VTKImageToImageFilter', 'itk::VTKImageToImageFilter', 'itkVTKImageToImageFilterISS3', True, 'itk::Image< signed short,3 >'),
  ('VTKImageToImageFilter', 'itk::VTKImageToImageFilter', 'itkVTKImageToImageFilterIUS2', True, 'itk::Image< unsigned short,2 >'),
  ('VTKImageToImageFilter', 'itk::VTKImageToImageFilter', 'itkVTKImageToImageFilterIUS3', True, 'itk::Image< unsigned short,3 >'),
  ('VTKImageToImageFilter', 'itk::VTKImageToImageFilter', 'itkVTKImageToImageFilterIF2', True, 'itk::Image< float,2 >'),
  ('VTKImageToImageFilter', 'itk::VTKImageToImageFilter', 'itkVTKImageToImageFilterIF3', True, 'itk::Image< float,3 >'),
  ('VTKImageToImageFilter', 'itk::VTKImageToImageFilter', 'itkVTKImageToImageFilterIRGBUC2', True, 'itk::Image< itk::RGBPixel< unsigned char >,2 >'),
  ('VTKImageToImageFilter', 'itk::VTKImageToImageFilter', 'itkVTKImageToImageFilterIRGBUC3', True, 'itk::Image< itk::RGBPixel< unsigned char >,3 >'),
  ('VTKImageToImageFilter', 'itk::VTKImageToImageFilter', 'itkVTKImageToImageFilterIRGBAUC2', True, 'itk::Image< itk::RGBAPixel< unsigned char >,2 >'),
  ('VTKImageToImageFilter', 'itk::VTKImageToImageFilter', 'itkVTKImageToImageFilterIRGBAUC3', True, 'itk::Image< itk::RGBAPixel< unsigned char >,3 >'),
  ('VTKImageToImageFilter', 'itk::VTKImageToImageFilter', 'itkVTKImageToImageFilterIVF22', True, 'itk::Image< itk::Vector< float,2 >,2 >'),
  ('VTKImageToImageFilter', 'itk::VTKImageToImageFilter', 'itkVTKImageToImageFilterIVF23', True, 'itk::Image< itk::Vector< float,2 >,3 >'),
  ('VTKImageToImageFilter', 'itk::VTKImageToImageFilter', 'itkVTKImageToImageFilterIVF32', True, 'itk::Image< itk::Vector< float,3 >,2 >'),
  ('VTKImageToImageFilter', 'itk::VTKImageToImageFilter', 'itkVTKImageToImageFilterIVF33', True, 'itk::Image< itk::Vector< float,3 >,3 >'),
  ('VTKImageToImageFilter', 'itk::VTKImageToImageFilter', 'itkVTKImageToImageFilterIVF42', True, 'itk::Image< itk::Vector< float,4 >,2 >'),
  ('VTKImageToImageFilter', 'itk::VTKImageToImageFilter', 'itkVTKImageToImageFilterIVF43', True, 'itk::Image< itk::Vector< float,4 >,3 >'),
  ('VTKImageToImageFilter', 'itk::VTKImageToImageFilter', 'itkVTKImageToImageFilterICVF22', True, 'itk::Image< itk::CovariantVector< float,2 >,2 >'),
  ('VTKImageToImageFilter', 'itk::VTKImageToImageFilter', 'itkVTKImageToImageFilterICVF23', True, 'itk::Image< itk::CovariantVector< float,2 >,3 >'),
  ('VTKImageToImageFilter', 'itk::VTKImageToImageFilter', 'itkVTKImageToImageFilterICVF32', True, 'itk::Image< itk::CovariantVector< float,3 >,2 >'),
  ('VTKImageToImageFilter', 'itk::VTKImageToImageFilter', 'itkVTKImageToImageFilterICVF33', True, 'itk::Image< itk::CovariantVector< float,3 >,3 >'),
  ('VTKImageToImageFilter', 'itk::VTKImageToImageFilter', 'itkVTKImageToImageFilterICVF42', True, 'itk::Image< itk::CovariantVector< float,4 >,2 >'),
  ('VTKImageToImageFilter', 'itk::VTKImageToImageFilter', 'itkVTKImageToImageFilterICVF43', True, 'itk::Image< itk::CovariantVector< float,4 >,3 >'),
  ('ViewImage', 'itk::ViewImage', 'itkViewImageISS2', True, 'itk::Image< signed short,2 >'),
  ('ViewImage', 'itk::ViewImage', 'itkViewImageIUC2', True, 'itk::Image< unsigned char,2 >'),
  ('ViewImage', 'itk::ViewImage', 'itkViewImageIUS2', True, 'itk::Image< unsigned short,2 >'),
  ('ViewImage', 'itk::ViewImage', 'itkViewImageIF2', True, 'itk::Image< float,2 >'),
  ('ViewImage', 'itk::ViewImage', 'itkViewImageISS3', True, 'itk::Image< signed short,3 >'),
  ('ViewImage', 'itk::ViewImage', 'itkViewImageIUC3', True, 'itk::Image< unsigned char,3 >'),
  ('ViewImage', 'itk::ViewImage', 'itkViewImageIUS3', True, 'itk::Image< unsigned short,3 >'),
  ('ViewImage', 'itk::ViewImage', 'itkViewImageIF3', True, 'itk::Image< float,3 >'),
)
snake_case_functions = ('vtk_image_export_base', 'vtk_image_import', 'spatial_object_to_vtk_poly_data_filter', 'vtk_image_to_image_filter', 'image_to_vtk_image_filter', 'vtk_image_export', 'box_spatial_object_to_vtk_poly_data_filter', )
