[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "audio-metadata"
description = "A library for reading and, in the future, writing metadata from audio files."
version = "0.5.0"

license = "MIT"

authors = ["thebigmunch <mail@thebigmunch.me>"]

readme = "README.md"

repository = "https://github.com/thebigmunch/audio-metadata"
homepage = "https://github.com/thebigmunch/audio-metadata"

[tool.poetry.dependencies]
python = "^3.6"

attrs = ">=18.2,<19.2"
bidict = "0.*"
bitstruct = ">=6.0,<=9.0"
more-itertools = ">=4.0,<8.0"
pprintpp = "0.*"

coverage = { version = "^4.5", optional = true }
flake8 = { version = "^3.5", optional = true }
flake8-builtins = { version = "^1.0", optional = true }
flake8-import-order = { version = "^0.18", optional = true }
flake8-import-order-tbm = { version = "^1.0.0", optional = true }
pytest = { version = "^4.0", optional = true }
sphinx = { version= "^2.0", optional = true}
tox = { version = "^3.0", optional = true }

[tool.poetry.extras]
dev = [
	"coverage",
	"flake8",
	"flake8-builtins",
	"flake8-import-order",
	"flake8-import-order-tbm",
	"pytest",
	"sphinx",
	"tox"
]
doc = [ "sphinx" ]
lint = [
	"flake8",
	"flake8-builtins",
	"flake8-import-order",
	"flake8-import-order-tbm"
]
test = [
	"coverage",
	"pytest",
	"tox"
]
