faceted_navigation:
    image: plone:4
    ports:
    - "8080"
    volumes:
    - ../../:/plone/instance/src/eea.facetednavigation
    environment:
      ADDONS: "eea.facetednavigation[test]"
      DEVELOP: "src/eea.facetednavigation"
