- job:
    name: openstacksdk-tox-py27-tips
    parent: openstack-tox-py27
    description: |
      Run tox python 27 unittests against master of important libs
    vars:
      tox_install_siblings: true
    # openstacksdk in required-projects so that os-client-config
    # and keystoneauth can add the job as well
    required-projects:
      - openstack/shade
      - openstack/keystoneauth
      - openstack/openstacksdk
      - openstack/os-client-config

- job:
    name: openstacksdk-tox-py35-tips
    parent: openstack-tox-py35
    description: |
      Run tox python 35 unittests against master of important libs
    vars:
      tox_install_siblings: true
    # openstacksdk in required-projects so that osc and keystoneauth
    # can add the job as well
    required-projects:
      - openstack/shade
      - openstack/keystoneauth
      - openstack/openstacksdk
      - openstack/os-client-config

- project-template:
    name: openstacksdk-tox-tips
    check:
      jobs:
        - openstacksdk-tox-py27-tips
        - openstacksdk-tox-py35-tips
    gate:
      jobs:
        - openstacksdk-tox-py27-tips
        - openstacksdk-tox-py35-tips

- job:
    name: openstacksdk-functional-devstack-minimum
    parent: devstack-tox-functional-consumer
    description: |
      Minimum job for devstack-based functional tests
    post-run: playbooks/devstack/post.yaml
    required-projects:
      - name: openstack/shade
        override-branch: master
      - name: openstack/openstacksdk
        override-branch: stable/rocky
      - name: openstack/os-client-config
        override-branch: stable/rocky
    timeout: 9000
    vars:
      devstack_localrc:
        Q_ML2_PLUGIN_EXT_DRIVERS: qos,port_security
      tox_environment:
        # Do we really need to set this? It's cargo culted
        PYTHONUNBUFFERED: 'true'
        # Is there a way we can query the localconf variable to get these
        # rather than setting them explicitly?
        OPENSTACKSDK_HAS_DESIGNATE: 0
        OPENSTACKSDK_HAS_HEAT: 0
        OPENSTACKSDK_HAS_MAGNUM: 0
        OPENSTACKSDK_HAS_NEUTRON: 1
        OPENSTACKSDK_HAS_SWIFT: 1
      tox_install_siblings: false
      tox_envlist: functional
      zuul_work_dir: src/opendev.org/openstack/openstacksdk

- job:
    name: openstacksdk-functional-devstack-base
    parent: openstacksdk-functional-devstack-minimum
    description: |
      Base job for devstack-based functional tests
    required-projects:
      - name: openstack/heat
      - name: openstack/swift
    vars:
      devstack_local_conf:
        post-config:
          $CINDER_CONF:
            DEFAULT:
              osapi_max_limit: 6
      devstack_services:
        s-account: true
        s-container: true
        s-object: true
        s-proxy: true
      devstack_plugins:
        heat: https://opendev.org/openstack/heat
      tox_environment:
        OPENSTACKSDK_HAS_HEAT: 1

- job:
    name: openstacksdk-functional-devstack-legacy
    parent: openstacksdk-functional-devstack-base
    description: |
      Run openstacksdk functional tests against a legacy devstack
    voting: false
    vars:
      devstack_localrc:
        ENABLE_IDENTITY_V2: true
        FLAT_INTERFACE: br_flat
        PUBLIC_INTERFACE: br_pub
      tox_environment:
        OPENSTACKSDK_USE_KEYSTONE_V2: 1
        OPENSTACKSDK_HAS_NEUTRON: 0
    override-branch: stable/newton

- job:
    name: openstacksdk-functional-devstack
    parent: openstacksdk-functional-devstack-base
    description: |
      Run openstacksdk functional tests against a stable/rocky devstack
    required-projects:
      - openstack/designate
      - openstack/octavia
    vars:
      devstack_localrc:
        DISABLE_AMP_IMAGE_BUILD: true
      devstack_local_conf:
        post-config:
          $OCTAVIA_CONF:
            DEFAULT:
              debug: true
            controller_worker:
              amphora_driver: amphora_noop_driver
              compute_driver: compute_noop_driver
              network_driver: network_noop_driver
            certificates:
              cert_manager: local_cert_manager
      devstack_plugins:
        designate: https://opendev.org/openstack/designate
        neutron: https://opendev.org/openstack/neutron
        octavia: https://opendev.org/openstack/octavia
      devstack_services:
        designate: true
        octavia: true
        o-api: true
        o-cw: true
        o-hm: true
        o-hk: true
        neutron-dns: true
        neutron-qos: true
        neutron-trunk: true
      tox_environment:
        OPENSTACKSDK_HAS_DESIGNATE: 1
        OPENSTACKSDK_HAS_OCTAVIA: 1

- job:
    name: openstacksdk-functional-devstack-python3
    parent: openstacksdk-functional-devstack
    description: |
      Run openstacksdk functional tests using python3 against a master devstack
    vars:
      tox_environment:
        OPENSTACKSDK_TOX_PYTHON: python3

- job:
    name: openstacksdk-functional-devstack-tips
    parent: openstacksdk-functional-devstack
    description: |
      Run openstacksdk functional tests with tips of library dependencies
      against a master devstack.
    required-projects:
      - openstack/shade
      - openstack/keystoneauth
      - openstack/openstacksdk
      - openstack/os-client-config
    vars:
      tox_install_siblings: true

- job:
    name: openstacksdk-functional-devstack-tips-python3
    parent: openstacksdk-functional-devstack-tips
    description: |
      Run openstacksdk functional tests with tips of library dependencies using
      python3 against a master devstack.
    vars:
      tox_environment:
        OPENSTACKSDK_TOX_PYTHON: python3

- job:
    name: openstacksdk-functional-devstack-magnum
    parent: openstacksdk-functional-devstack
    description: |
      Run openstacksdk functional tests against a master devstack with magnum
    required-projects:
      - openstack/magnum
      - openstack/python-magnumclient
    vars:
      devstack_plugins:
        magnum: https://opendev.org/openstack/magnum
      devstack_localrc:
        MAGNUM_GUEST_IMAGE_URL: https://tarballs.openstack.org/magnum/images/fedora-atomic-f23-dib.qcow2
        MAGNUM_IMAGE_NAME: fedora-atomic-f23-dib
      devstack_services:
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
      tox_environment:
        OPENSTACKSDK_HAS_SWIFT: 0
        OPENSTACKSDK_HAS_MAGNUM: 1

- job:
    name: openstacksdk-functional-devstack-senlin
    parent: openstacksdk-functional-devstack
    description: |
      Run shade functional tests against a master devstack with senlin
    required-projects:
      - openstack/senlin
    vars:
      devstack_plugins:
        senlin: https://opendev.org/openstack/senlin
      devstack_services:
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
      tox_environment:
        OPENSTACKSDK_HAS_SWIFT: 0
        OPENSTACKSDK_HAS_SENLIN: 1

- job:
    name: openstacksdk-functional-devstack-ironic
    parent: openstacksdk-functional-devstack-minimum
    description: |
      Run openstacksdk functional tests against a master devstack with ironic
    required-projects:
      - openstack/ironic
    vars:
      devstack_localrc:
        OVERRIDE_PUBLIC_BRIDGE_MTU: 1400
        IRONIC_BAREMETAL_BASIC_OPS: true
        IRONIC_BUILD_DEPLOY_RAMDISK: false
        IRONIC_CALLBACK_TIMEOUT: 600
        IRONIC_DEPLOY_DRIVER: ipmi
        IRONIC_RAMDISK_TYPE: tinyipa
        IRONIC_VM_COUNT: 6
        IRONIC_VM_LOG_DIR: '{{ devstack_base_dir }}/ironic-bm-logs'
        IRONIC_VM_SPECS_RAM: 384
      devstack_plugins:
        ironic: https://opendev.org/openstack/ironic
      devstack_services:
        c-api: false
        c-bak: false
        c-sch: false
        c-vol: false
        cinder: false
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        n-api: false
        n-api-meta: false
        n-cauth: false
        n-cond: false
        n-cpu: false
        n-novnc: false
        n-obj: false
        n-sch: false
        nova: false
        placement-api: false
      tox_environment:
        OPENSTACKSDK_HAS_IRONIC: 1
        # NOTE(dtantsur): this job cannot run many regular tests (e.g. compute
        # tests will take too long), so limiting it to baremetal tests only.
        OPENSTACKSDK_TESTS_SUBDIR: baremetal
      zuul_copy_output:
        '{{ devstack_base_dir }}/ironic-bm-logs': logs

- job:
    name: openstacksdk-ansible-functional-devstack
    parent: openstacksdk-functional-devstack
    description: |
      Run openstacksdk ansible functional tests against a master devstack
      using released version of ansible.
    vars:
      tox_envlist: ansible

- job:
    name: openstacksdk-ansible-functional-devstack
    parent: openstacksdk-functional-devstack
    description: |
      Run openstacksdk ansible functional tests against a master devstack
      using released version of ansible.
    vars:
      tox_envlist: ansible

- job:
    name: openstacksdk-ansible-devel-functional-devstack
    parent: openstacksdk-ansible-functional-devstack
    description: |
      Run openstacksdk ansible functional tests against a master devstack
      using git devel branch version of ansible.
    branches: ^(devel|master)$
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: devel
      - name: openstack/openstacksdk
        override-checkout: master
      - name: openstack/devstack
        override-checkout: master
    vars:
      # test-matrix grabs branch from the zuul branch setting. If the job
      # is triggered by ansible, that branch will be devel which doesn't
      # make sense to devstack. Override so that we run the right thing.
      test_matrix_branch: master
      tox_install_siblings: true

- job:
    name: openstacksdk-ansible-stable-2.6-functional-devstack
    parent: openstacksdk-ansible-functional-devstack
    description: |
      Run openstacksdk ansible functional tests against a master devstack
      using git stable-2.6 branch version of ansible.
    branches: ^(stable-2.6|master)$
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: stable-2.6
      - name: openstack/openstacksdk
        override-checkout: master
      - name: openstack/devstack
        override-checkout: master
    vars:
      # test-matrix grabs branch from the zuul branch setting. If the job
      # is triggered by ansible, that branch will be devel which doesn't
      # make sense to devstack. Override so that we run the right thing.
      test_matrix_branch: master
      tox_install_siblings: true

- project-template:
    name: openstacksdk-functional-tips
    check:
      jobs:
        - openstacksdk-functional-devstack-tips
        - openstacksdk-functional-devstack-tips-python3
    gate:
      jobs:
        - openstacksdk-functional-devstack-tips
        - openstacksdk-functional-devstack-tips-python3

- project:
    templates:
      - openstack-python36-jobs
      - openstacksdk-functional-tips
      - openstacksdk-tox-tips
      - os-client-config-tox-tips
      - osc-tox-unit-tips
      - shade-functional-tips
      - shade-tox-tips
      - openstack-python-jobs
      - openstack-python35-jobs
      - check-requirements
      - publish-openstack-sphinx-docs
      - release-notes-jobs
    check:
      jobs:
        - build-openstack-sphinx-docs:
            vars:
              sphinx_python: python3
        - openstacksdk-ansible-devel-functional-devstack:
            voting: false
        - openstacksdk-ansible-stable-2.6-functional-devstack:
            voting: false
        - openstacksdk-functional-devstack
        - openstacksdk-functional-devstack-senlin
        - openstacksdk-functional-devstack-magnum:
            voting: false
        - openstacksdk-functional-devstack-ironic:
            voting: false
        - openstacksdk-functional-devstack-python3
        - osc-functional-devstack-tips:
            voting: false
        - neutron-grenade
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - build-openstack-sphinx-docs:
            vars:
              sphinx_python: python3
        - openstacksdk-functional-devstack
        - openstacksdk-functional-devstack-python3
        - openstacksdk-functional-devstack-senlin
        - neutron-grenade
        - openstack-tox-lower-constraints
    post:
      jobs:
        - openstack-tox-cover
