[tool.poetry]
name = "maya-util"
version = "0.3.1"
description = "Utilities for working with the Maya API."
authors = ["Mitchell Coote <mitchellcoote@gmail.com>"]
packages = [
    { include = "mayautil" },
]

[tool.poetry.dependencies]
python = "^2.7.9 || ^3.4"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
pytest-cov = "^2.7"
mkdocs = "^1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
