[tool.poetry]
name = "gaphor"
version = "1.0.2"
description = "Gaphor is the simple modeling tool written in Python."
authors = [
    "Arjan J. Molenaar <gaphor@gmail.com>",
    "Dan Yeaw <dan@yeaw.me>"
]

readme = "README.md"

homepage = "https://gaphor.readthedocs.io/"
repository = "https://github.com/gaphor/gaphor"
documentation = "https://gaphor.readthedocs.io/"

keywords = ["gtk+", "diagram", "UML", "MBSE", "gaphor", "modeling"]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: X11 Applications :: GTK",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Programming Language :: Python",
    "Topic :: Multimedia :: Graphics :: Editors :: Vector-Based",
    "Topic :: Software Development :: Documentation",
]

[tool.poetry.dependencies]
python = "^3.5"
pycairo = "^1.16"
PyGObject = "^3.30"
gaphas = "^1.0.0"
importlib_metadata = "^0.18"
tomlkit = "^0.5"

[tool.poetry.dev-dependencies]
pytest = "^4.0"
pytest-sugar = "^0.9.2"
pytest-cov = "^2.5"
pytest-runner = "^4.2"
black = { version = "^19.3b0", python = "^3.6" }
pre-commit = "^1.12"

[tool.poetry.scripts]
gaphor = 'gaphor:main'
gaphorconvert = 'gaphor.tools.gaphorconvert:main'

[tool.poetry.plugins."gaphor.services"]
"component_registry" = "gaphor.services.componentregistry:ComponentRegistry"
"event_manager" = "gaphor.services.eventmanager:EventManager"
"properties" = "gaphor.services.properties:Properties"
"undo_manager" = "gaphor.services.undomanager:UndoManager"
"element_factory" = "gaphor.UML.elementfactory:ElementFactory"
"file_manager" = "gaphor.services.filemanager:FileManager"
"diagram_export_manager" = "gaphor.services.diagramexportmanager:DiagramExportManager"
"action_manager" = "gaphor.services.actionmanager:ActionManager"
"main_window" = "gaphor.ui.mainwindow:MainWindow"
"copy" = "gaphor.services.copyservice:CopyService"
"sanitizer" = "gaphor.services.sanitizerservice:SanitizerService"
"xmi_export" = "gaphor.plugins.xmiexport:XMIExport"
"diagram_layout" = "gaphor.plugins.diagramlayout:DiagramLayout"
"pynsource" = "gaphor.plugins.pynsource:PyNSource"
"alignment" = "gaphor.plugins.alignment:Alignment"
"help" = "gaphor.services.helpservice:HelpService"
"namespace" = "gaphor.ui.mainwindow:Namespace"
"toolbox" = "gaphor.ui.mainwindow:Toolbox"
"diagrams" = "gaphor.ui.mainwindow:Diagrams"
"consolewindow" = "gaphor.ui.consolewindow:ConsoleWindow"
"elementeditor" = "gaphor.ui.elementeditor:ElementEditor"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
