sudo: false
language: python

os: linux
dist: xenial

git:
  depth: 3
  submodules: false

branches:
  only:
    - master
    - next

matrix:
  fast_finish: true

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"

cache: pip

install:
  - pip install -r venv/requirements-test.txt --upgrade
  - pip install -r venv/requirements.txt --upgrade
  - python3 setup.py build
  - pip install -e .

script: ./check.sh
