[tool.poetry]
name = "pedroasad-attrs-patch"
version = "0.2.1"
description = "A set of patches for the excellent attrs library"
authors = ["Pedro Asad <pasad@lcg.ufrj.br>"]
repository = "https://gitlab.com/psa-exe/python-attrs-patch"
homepage = "https://psa-exe.gitlab.io/python-attrs-patch"
documentation = "https://psa-exe.gitlab.io/python-attrs-patch"
license = "MIT"
readme = "README.md"
packages = [
    { include = "attrs_patch", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.5"
numpy = { version = "^1.16", optional = true }
attrs = "^19.1"

[tool.poetry.dev-dependencies]
bumpversion = "^0.5.3"
codecov = "^2.0"
pre-commit = "^1.17"
pytest = "^5.0"
pytest-cov = "^2.7"
recommonmark = "^0.5.0"
sphinx = "^2.1"
sphinx_rtd_theme = "^0.4.3"
toml = "^0.10.0"
sphinx-markdown-tables = "^0.0.9"
flake8 = "^3.7"

[tool.poetry.extras]
all = [
    "numpy",
]
numpy = [
    "numpy",
]

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]

