[tool.poetry]
name = "midnite"
version = "0.1.2"
description = "This is a framework for visualization and uncertainty in CNNs."
authors = ["luminovo.ai, Christina Aigner, Fabian Huch"]
homepage = "https://luminovo.gitlab.io/public/midnite"
repository = "https://gitlab.com/luminovo/public/midnite"
license = "MIT"
keywords = [
    "torch",
    "pytorch",
    "uncertainty",
    "classification",
    "segmentation",
    "visualization",
    "GradCAM",
    "occlusion",
    "CNN",
]
include = [
    "LICENSE",
]
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.7",
    "Topic :: Scientific/Engineering :: Image Recognition",
    "Topic :: Scientific/Engineering :: Visualization",
]

[tool.poetry.dependencies]
python = "^3.7"
torch = "=1.1"
numpy = "^1.16"
pillow = "^6.1"
opencv-python = "^4.0"
tqdm = "^4.31"

[tool.poetry.dev-dependencies]
pytest = "^3.8"
gdown = "^3.7"
jupyter = "^1.0"
matplotlib = "^3.0"
assertpy = "^0.14"
pytest-mock = "^1.10"
torchvision = "^0.3"
tabulate = "^0.8"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
