image: python:3.6

stages:
  - test
  - deploy
  - playbook

python_test:
  stage: test
  script:
    - pip install virtualenv
    - virtualenv --python=python3 ve
    - source ve/bin/activate
    - pip3 install -rrequirements.txt
    - tox -r

deploy_stage:
  stage: deploy
  script:
    - mkdir -p $HOME
    - cp ./.pypirc $HOME/.pypirc
    - pip3 install virtualenv
    - virtualenv --python=python3 ve
    - source ve/bin/activate
    - pip3 install -r requirements.txt --quiet --upgrade
    - python setup.py sdist bdist_wheel
    - twine upload dist/*
    - rm dist/*

ansible-playbook:
  stage: playbook
  script: 
    - ansible all -i ansible/hosts.yml -m ping
    - ansible-playbook playbook.yml --syntax-check
    - ansible-playbook playbook.yml



