
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-17T15:58:20+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d5ca10a1e7dd53927a066f283a3113aa64aecf66",
 "version": "0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
