[build-system]
requires = [ "poetry>=0.12",]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "pyppl-notify"
version = "0.0.1"
description = "Email notification for PyPPL"
authors = [ "pwwang <pwwang@pwwang.com>",]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/pwwang/pyppl-notify"
repository = "https://github.com/pwwang/pyppl-notify"
packages = [{include = "pyppl-notify.py"}]

[tool.poetry.dependencies]
python = "^3.6"
pyppl = "^2.0.0"
panflute = "^1.0.0"
