# Generated by Django 2.2.3 on 2019-07-04 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('display_type', models.PositiveIntegerField(choices=[{1, 'HTML'}, {2, 'Latest Posts'}, {'Hottest Posts', 3}, {'Latest Comments', 4}], default=1, verbose_name='display type')),
                ('content', models.CharField(blank=True, max_length=500, verbose_name='post')),
                ('status', models.PositiveIntegerField(choices=[{1, 'show'}, {0, 'hide'}], default=1, verbose_name='status')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'side bar',
                'verbose_name_plural': 'side bar',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('href', models.URLField(verbose_name='link')),
                ('status', models.PositiveIntegerField(choices=[{1, 'normal'}, {0, 'delete'}], default=1, verbose_name='status')),
                ('weight', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, help_text='weight order from high to low', verbose_name='weight')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Link',
            },
        ),
    ]
