language: python
python:
  - "3.6"
  # - "2.7"
  # - "3.6-dev"
  # - "3.7"
install:
  - export ENVIRONMENT_YML="conda/environment.yml"
  - export CONDA_ENV_NAME="venv_nlpia"
  - export CONDA_PYTHON_VERSION=3.6
  - export PYTHON_VERSION=3.6
  - export CONDA_DIR="$HOME/miniconda"
  - env
  - sudo apt-get update
  - sudo apt-get remove -y python-boto
  - sudo apt-get install -y build-essential gfortran libopenblas-dev liblapack-dev pandoc portaudio19-dev libasound* pulseaudio* libpulse*
  - source tests/install_miniconda.sh
  - env
  - "echo \"before hash -r which python: $(which python)\""
  - "echo \"before hash -r which conda: $(which conda)\""
  # - cp conda/.condarc $HOME/.condarc
  - conda config --add channels conda-forge
  - conda config --add channels anaconda
  - conda config --set always_yes yes
  - conda config --set changeps1 no
  # - conda update -n base conda
  # - travis_wait 30 source tests/create_conda_environment.sh
  - conda update conda
  - conda env create --verbose --force --prefix "./$CONDA_ENV_NAME" --file "$ENVIRONMENT_YML"
  - source activate "./$CONDA_ENV_NAME"
  - hash -r
  - "echo \"after hash -r which python: $(which python)\""
  - "echo \"after hash -r which conda: $(which conda)\""
  - echo $PATH
  - conda install pip --yes
  - conda install python-annoy --yes
  - pip install --upgrade PyScaffold
  # - sudo apt-get install -y python-boto
  # - pip install -r requirements/requirements.txt
  - pip install --upgrade -e .
  - python -c "import nltk; nltk.download('punkt')"
  # - conda info -a
  # - conda list
  - pip list
  # - pip install codecov
  # - conda build conda-build-recipe
  # - conda install nlpia --use-local

after_success:
  - bash < (curl -s https://codecov.io/bash)
  - codecov

script:
  - python setup.py test

after_script:
  - travis-cleanup

# cache:
#   pip: true
#   directories:
#     - $HOME/miniconda
