
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-22T14:27:55-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "4b9e397e83817172236293bd72603d744273b7b5",
 "version": "2021.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
