
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-20T16:56:09+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7fda6aeb957c6d6fea2af79f0fbc82b7952a8a3d",
 "version": "1.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
