
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-09T18:06:18-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f91fab62c97828d806992d11d35bfdab9c91fc59",
 "version": "2020.0.1rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
