# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.


import vtk
import ctypes
import os
if os.name != 'nt':
  _vtk_major_version = str(vtk.vtkVersion.GetVTKMajorVersion())
  _vtk_minor_version = str(vtk.vtkVersion.GetVTKMinorVersion())
  _vtkIOlib = 'libvtkIO-' + _vtk_major_version + '.' + _vtk_minor_version + '.so.1'
  ctypes.CDLL(_vtkIOlib, ctypes.RTLD_GLOBAL)
  _vtkInteractionlib = 'libvtkInteraction-' + _vtk_major_version + '.' + _vtk_minor_version + '.so.1'
  ctypes.CDLL(_vtkInteractionlib, ctypes.RTLD_GLOBAL)
  _vtkOpenGLlib = 'libvtkOpenGL-' + _vtk_major_version + '.' + _vtk_minor_version + '.so.1'
  ctypes.CDLL(_vtkOpenGLlib, ctypes.RTLD_GLOBAL)
  import sys
  _vtkWrappinglib = 'libvtkWrappingPython' + str(sys.version_info[0]) + str(sys.version_info[1]) + 'Core-' + _vtk_major_version + '.'  + _vtk_minor_version + '.so.1'
  ctypes.CDLL(_vtkWrappinglib, ctypes.RTLD_GLOBAL)





from sys import version_info
if version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _itkViewImagePython.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_itkViewImagePython', [dirname(__file__)])
        except ImportError:
            import _itkViewImagePython
            return _itkViewImagePython
        if fp is not None:
            try:
                _mod = imp.load_module('_itkViewImagePython', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _itkViewImagePython = swig_import_helper()
    del swig_import_helper
else:
    import _itkViewImagePython
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


import itkImagePython
import itkIndexPython
import itkSizePython
import pyBasePython
import itkOffsetPython
import itkVectorPython
import vnl_vector_refPython
import stdcomplexPython
import vnl_vectorPython
import vnl_matrixPython
import itkFixedArrayPython
import ITKCommonBasePython
import itkRGBAPixelPython
import itkSymmetricSecondRankTensorPython
import itkMatrixPython
import itkCovariantVectorPython
import itkPointPython
import vnl_matrix_fixedPython
import itkImageRegionPython
import itkRGBPixelPython
class itkViewImageIF2(object):
    """Proxy of C++ itkViewImageIF2 class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def View(*args) -> "void":
        """
        View(itkImageF2 img, std::string const & windowTitle, unsigned long long windowWidth=600, unsigned long long windowHeight=600)
        View(itkImageF2 img, std::string const & windowTitle, unsigned long long windowWidth=600)
        View(itkImageF2 img, std::string const & windowTitle)
        View(itkImageF2 img)
        """
        return _itkViewImagePython.itkViewImageIF2_View(*args)

    View = staticmethod(View)

    def __init__(self, *args):
        """
        __init__(itkViewImageIF2 self) -> itkViewImageIF2
        __init__(itkViewImageIF2 self, itkViewImageIF2 arg0) -> itkViewImageIF2
        """
        _itkViewImagePython.itkViewImageIF2_swiginit(self, _itkViewImagePython.new_itkViewImageIF2(*args))
    __swig_destroy__ = _itkViewImagePython.delete_itkViewImageIF2
itkViewImageIF2_swigregister = _itkViewImagePython.itkViewImageIF2_swigregister
itkViewImageIF2_swigregister(itkViewImageIF2)

def itkViewImageIF2_View(*args) -> "void":
    """
    View(itkImageF2 img, std::string const & windowTitle, unsigned long long windowWidth=600, unsigned long long windowHeight=600)
    View(itkImageF2 img, std::string const & windowTitle, unsigned long long windowWidth=600)
    View(itkImageF2 img, std::string const & windowTitle)
    itkViewImageIF2_View(itkImageF2 img)
    """
    return _itkViewImagePython.itkViewImageIF2_View(*args)

class itkViewImageIF3(object):
    """Proxy of C++ itkViewImageIF3 class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def View(*args) -> "void":
        """
        View(itkImageF3 img, std::string const & windowTitle, unsigned long long windowWidth=600, unsigned long long windowHeight=600)
        View(itkImageF3 img, std::string const & windowTitle, unsigned long long windowWidth=600)
        View(itkImageF3 img, std::string const & windowTitle)
        View(itkImageF3 img)
        """
        return _itkViewImagePython.itkViewImageIF3_View(*args)

    View = staticmethod(View)

    def __init__(self, *args):
        """
        __init__(itkViewImageIF3 self) -> itkViewImageIF3
        __init__(itkViewImageIF3 self, itkViewImageIF3 arg0) -> itkViewImageIF3
        """
        _itkViewImagePython.itkViewImageIF3_swiginit(self, _itkViewImagePython.new_itkViewImageIF3(*args))
    __swig_destroy__ = _itkViewImagePython.delete_itkViewImageIF3
itkViewImageIF3_swigregister = _itkViewImagePython.itkViewImageIF3_swigregister
itkViewImageIF3_swigregister(itkViewImageIF3)

def itkViewImageIF3_View(*args) -> "void":
    """
    View(itkImageF3 img, std::string const & windowTitle, unsigned long long windowWidth=600, unsigned long long windowHeight=600)
    View(itkImageF3 img, std::string const & windowTitle, unsigned long long windowWidth=600)
    View(itkImageF3 img, std::string const & windowTitle)
    itkViewImageIF3_View(itkImageF3 img)
    """
    return _itkViewImagePython.itkViewImageIF3_View(*args)

class itkViewImageISS2(object):
    """Proxy of C++ itkViewImageISS2 class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def View(*args) -> "void":
        """
        View(itkImageSS2 img, std::string const & windowTitle, unsigned long long windowWidth=600, unsigned long long windowHeight=600)
        View(itkImageSS2 img, std::string const & windowTitle, unsigned long long windowWidth=600)
        View(itkImageSS2 img, std::string const & windowTitle)
        View(itkImageSS2 img)
        """
        return _itkViewImagePython.itkViewImageISS2_View(*args)

    View = staticmethod(View)

    def __init__(self, *args):
        """
        __init__(itkViewImageISS2 self) -> itkViewImageISS2
        __init__(itkViewImageISS2 self, itkViewImageISS2 arg0) -> itkViewImageISS2
        """
        _itkViewImagePython.itkViewImageISS2_swiginit(self, _itkViewImagePython.new_itkViewImageISS2(*args))
    __swig_destroy__ = _itkViewImagePython.delete_itkViewImageISS2
itkViewImageISS2_swigregister = _itkViewImagePython.itkViewImageISS2_swigregister
itkViewImageISS2_swigregister(itkViewImageISS2)

def itkViewImageISS2_View(*args) -> "void":
    """
    View(itkImageSS2 img, std::string const & windowTitle, unsigned long long windowWidth=600, unsigned long long windowHeight=600)
    View(itkImageSS2 img, std::string const & windowTitle, unsigned long long windowWidth=600)
    View(itkImageSS2 img, std::string const & windowTitle)
    itkViewImageISS2_View(itkImageSS2 img)
    """
    return _itkViewImagePython.itkViewImageISS2_View(*args)

class itkViewImageISS3(object):
    """Proxy of C++ itkViewImageISS3 class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def View(*args) -> "void":
        """
        View(itkImageSS3 img, std::string const & windowTitle, unsigned long long windowWidth=600, unsigned long long windowHeight=600)
        View(itkImageSS3 img, std::string const & windowTitle, unsigned long long windowWidth=600)
        View(itkImageSS3 img, std::string const & windowTitle)
        View(itkImageSS3 img)
        """
        return _itkViewImagePython.itkViewImageISS3_View(*args)

    View = staticmethod(View)

    def __init__(self, *args):
        """
        __init__(itkViewImageISS3 self) -> itkViewImageISS3
        __init__(itkViewImageISS3 self, itkViewImageISS3 arg0) -> itkViewImageISS3
        """
        _itkViewImagePython.itkViewImageISS3_swiginit(self, _itkViewImagePython.new_itkViewImageISS3(*args))
    __swig_destroy__ = _itkViewImagePython.delete_itkViewImageISS3
itkViewImageISS3_swigregister = _itkViewImagePython.itkViewImageISS3_swigregister
itkViewImageISS3_swigregister(itkViewImageISS3)

def itkViewImageISS3_View(*args) -> "void":
    """
    View(itkImageSS3 img, std::string const & windowTitle, unsigned long long windowWidth=600, unsigned long long windowHeight=600)
    View(itkImageSS3 img, std::string const & windowTitle, unsigned long long windowWidth=600)
    View(itkImageSS3 img, std::string const & windowTitle)
    itkViewImageISS3_View(itkImageSS3 img)
    """
    return _itkViewImagePython.itkViewImageISS3_View(*args)

class itkViewImageIUC2(object):
    """Proxy of C++ itkViewImageIUC2 class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def View(*args) -> "void":
        """
        View(itkImageUC2 img, std::string const & windowTitle, unsigned long long windowWidth=600, unsigned long long windowHeight=600)
        View(itkImageUC2 img, std::string const & windowTitle, unsigned long long windowWidth=600)
        View(itkImageUC2 img, std::string const & windowTitle)
        View(itkImageUC2 img)
        """
        return _itkViewImagePython.itkViewImageIUC2_View(*args)

    View = staticmethod(View)

    def __init__(self, *args):
        """
        __init__(itkViewImageIUC2 self) -> itkViewImageIUC2
        __init__(itkViewImageIUC2 self, itkViewImageIUC2 arg0) -> itkViewImageIUC2
        """
        _itkViewImagePython.itkViewImageIUC2_swiginit(self, _itkViewImagePython.new_itkViewImageIUC2(*args))
    __swig_destroy__ = _itkViewImagePython.delete_itkViewImageIUC2
itkViewImageIUC2_swigregister = _itkViewImagePython.itkViewImageIUC2_swigregister
itkViewImageIUC2_swigregister(itkViewImageIUC2)

def itkViewImageIUC2_View(*args) -> "void":
    """
    View(itkImageUC2 img, std::string const & windowTitle, unsigned long long windowWidth=600, unsigned long long windowHeight=600)
    View(itkImageUC2 img, std::string const & windowTitle, unsigned long long windowWidth=600)
    View(itkImageUC2 img, std::string const & windowTitle)
    itkViewImageIUC2_View(itkImageUC2 img)
    """
    return _itkViewImagePython.itkViewImageIUC2_View(*args)

class itkViewImageIUC3(object):
    """Proxy of C++ itkViewImageIUC3 class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def View(*args) -> "void":
        """
        View(itkImageUC3 img, std::string const & windowTitle, unsigned long long windowWidth=600, unsigned long long windowHeight=600)
        View(itkImageUC3 img, std::string const & windowTitle, unsigned long long windowWidth=600)
        View(itkImageUC3 img, std::string const & windowTitle)
        View(itkImageUC3 img)
        """
        return _itkViewImagePython.itkViewImageIUC3_View(*args)

    View = staticmethod(View)

    def __init__(self, *args):
        """
        __init__(itkViewImageIUC3 self) -> itkViewImageIUC3
        __init__(itkViewImageIUC3 self, itkViewImageIUC3 arg0) -> itkViewImageIUC3
        """
        _itkViewImagePython.itkViewImageIUC3_swiginit(self, _itkViewImagePython.new_itkViewImageIUC3(*args))
    __swig_destroy__ = _itkViewImagePython.delete_itkViewImageIUC3
itkViewImageIUC3_swigregister = _itkViewImagePython.itkViewImageIUC3_swigregister
itkViewImageIUC3_swigregister(itkViewImageIUC3)

def itkViewImageIUC3_View(*args) -> "void":
    """
    View(itkImageUC3 img, std::string const & windowTitle, unsigned long long windowWidth=600, unsigned long long windowHeight=600)
    View(itkImageUC3 img, std::string const & windowTitle, unsigned long long windowWidth=600)
    View(itkImageUC3 img, std::string const & windowTitle)
    itkViewImageIUC3_View(itkImageUC3 img)
    """
    return _itkViewImagePython.itkViewImageIUC3_View(*args)

class itkViewImageIUS2(object):
    """Proxy of C++ itkViewImageIUS2 class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def View(*args) -> "void":
        """
        View(itkImageUS2 img, std::string const & windowTitle, unsigned long long windowWidth=600, unsigned long long windowHeight=600)
        View(itkImageUS2 img, std::string const & windowTitle, unsigned long long windowWidth=600)
        View(itkImageUS2 img, std::string const & windowTitle)
        View(itkImageUS2 img)
        """
        return _itkViewImagePython.itkViewImageIUS2_View(*args)

    View = staticmethod(View)

    def __init__(self, *args):
        """
        __init__(itkViewImageIUS2 self) -> itkViewImageIUS2
        __init__(itkViewImageIUS2 self, itkViewImageIUS2 arg0) -> itkViewImageIUS2
        """
        _itkViewImagePython.itkViewImageIUS2_swiginit(self, _itkViewImagePython.new_itkViewImageIUS2(*args))
    __swig_destroy__ = _itkViewImagePython.delete_itkViewImageIUS2
itkViewImageIUS2_swigregister = _itkViewImagePython.itkViewImageIUS2_swigregister
itkViewImageIUS2_swigregister(itkViewImageIUS2)

def itkViewImageIUS2_View(*args) -> "void":
    """
    View(itkImageUS2 img, std::string const & windowTitle, unsigned long long windowWidth=600, unsigned long long windowHeight=600)
    View(itkImageUS2 img, std::string const & windowTitle, unsigned long long windowWidth=600)
    View(itkImageUS2 img, std::string const & windowTitle)
    itkViewImageIUS2_View(itkImageUS2 img)
    """
    return _itkViewImagePython.itkViewImageIUS2_View(*args)

class itkViewImageIUS3(object):
    """Proxy of C++ itkViewImageIUS3 class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def View(*args) -> "void":
        """
        View(itkImageUS3 img, std::string const & windowTitle, unsigned long long windowWidth=600, unsigned long long windowHeight=600)
        View(itkImageUS3 img, std::string const & windowTitle, unsigned long long windowWidth=600)
        View(itkImageUS3 img, std::string const & windowTitle)
        View(itkImageUS3 img)
        """
        return _itkViewImagePython.itkViewImageIUS3_View(*args)

    View = staticmethod(View)

    def __init__(self, *args):
        """
        __init__(itkViewImageIUS3 self) -> itkViewImageIUS3
        __init__(itkViewImageIUS3 self, itkViewImageIUS3 arg0) -> itkViewImageIUS3
        """
        _itkViewImagePython.itkViewImageIUS3_swiginit(self, _itkViewImagePython.new_itkViewImageIUS3(*args))
    __swig_destroy__ = _itkViewImagePython.delete_itkViewImageIUS3
itkViewImageIUS3_swigregister = _itkViewImagePython.itkViewImageIUS3_swigregister
itkViewImageIUS3_swigregister(itkViewImageIUS3)

def itkViewImageIUS3_View(*args) -> "void":
    """
    View(itkImageUS3 img, std::string const & windowTitle, unsigned long long windowWidth=600, unsigned long long windowHeight=600)
    View(itkImageUS3 img, std::string const & windowTitle, unsigned long long windowWidth=600)
    View(itkImageUS3 img, std::string const & windowTitle)
    itkViewImageIUS3_View(itkImageUS3 img)
    """
    return _itkViewImagePython.itkViewImageIUS3_View(*args)



