
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-13T00:10:23-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "60b0c2c72e90953f47a309cbbd2262edf1b8a1c4",
 "version": "2021.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
