BBBB BBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXX
    BBB B BB BBBB
        BB BBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBBBBBBBBB B
        XXXXXX
        BBBBB
    BBBBBB
XXXXXX