BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBB BBBBBBBBBBBB BBBBBBBBBB BBBBBBBB

BBBBB BBBBBBB
    XXXXX BB BBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBBXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB
        XXXXX
            XXXX XXXXX XXXXXX XXXXX XXX
            BB BBBBBBBBXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXBBBBB

            XXXX XXX XXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXX XXX XXX
            BB BBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXBBBBB
            BB BBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXBBBBB
            BB BBBBBBBBBBBBBBBBBB BBB BBBBBBBBXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXBBBBB
            XXXX XXX XXXX  XXXXXXXXXXX XXXXX XXXXXX XXXXX XXX XXX

            XXXX XX XXXXXXXXXX XX XXX XXX

            XXXX XXXXXX XXX
            BB BBBBBB
                XX XXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBB BB B gettext(u'Please correct the error below.') BBBB gettext(u'Please correct the errors below.') BBBBBXXXX
                XXX XXXXXXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXBBBBBBXXXXX
            BBBBB

            XXXX XXXXXXXXX XXX
            BBBBB BBBBBBBBBB
                BBB BBBBBBBB BB BBBBBBBBB
                    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                BBBBBB
            BBBBBBBB

            BBBBB BBBBBBBBBBBBBBBBBBBBBBBB

            XXXX XXXXXXX XXX
            BBBBB BBBBBBBBBBBBBBBBB
                BBB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBB
                    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                BBBBBB
            BBBBBBBB

            BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB

            XXXX XXXXXXXXXX XXX
            BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

            XXXX XX XXX XXXXXXXXXXXX XXXXXX XXX
            BBBBBBBBBBBBBBBBBBBBBB

        XXXXXX
    XXXXXXX
BBBBBBBB
