version: 2.0

shared: &shared
  working_directory: ~/django-environs
  steps:
    - checkout
    - run: echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
    - run: pip install --user tox
    - run:
        name: Run tests
        command: tox

jobs:
  "python-3.6":
    <<: *shared
    docker:
      - image: circleci/python:3.6
    environment:
      TOXENV: py36-django{111,21,22}

  "python-3.7":
    <<: *shared
    docker:
      - image: circleci/python:3.7
    environment:
      TOXENV: py37-django{111,21,22}

  "pre-commit":
    <<: *shared
    docker:
      - image: circleci/python
    environment:
      TOXENV: pre-commit

workflows:
  version: 2
  build:
    jobs:
      - "python-3.6"
      - "python-3.7"
      - "pre-commit"
