# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SocValidatorGUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(779, 631)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabStatus = QtWidgets.QTabWidget(self.centralwidget)
        self.tabStatus.setGeometry(QtCore.QRect(10, 410, 761, 191))
        self.tabStatus.setObjectName("tabStatus")
        self.tabStatus1 = QtWidgets.QWidget()
        self.tabStatus1.setObjectName("tabStatus1")
        self.textStatus = QtWidgets.QTextEdit(self.tabStatus1)
        self.textStatus.setGeometry(QtCore.QRect(10, 10, 731, 141))
        self.textStatus.setReadOnly(True)
        self.textStatus.setObjectName("textStatus")
        self.tabStatus.addTab(self.tabStatus1, "")
        self.tabKDHost = QtWidgets.QWidget()
        self.tabKDHost.setObjectName("tabKDHost")
        self.textKdhost = QtWidgets.QTextEdit(self.tabKDHost)
        self.textKdhost.setGeometry(QtCore.QRect(10, 10, 731, 141))
        self.textKdhost.setReadOnly(True)
        self.textKdhost.setObjectName("textKdhost")
        self.tabStatus.addTab(self.tabKDHost, "")
        self.tabKDSRA = QtWidgets.QWidget()
        self.tabKDSRA.setObjectName("tabKDSRA")
        self.textKdsra = QtWidgets.QTextEdit(self.tabKDSRA)
        self.textKdsra.setGeometry(QtCore.QRect(10, 10, 731, 141))
        self.textKdsra.setReadOnly(True)
        self.textKdsra.setObjectName("textKdsra")
        self.tabStatus.addTab(self.tabKDSRA, "")
        self.tabKDERA = QtWidgets.QWidget()
        self.tabKDERA.setObjectName("tabKDERA")
        self.textKdera = QtWidgets.QTextEdit(self.tabKDERA)
        self.textKdera.setGeometry(QtCore.QRect(10, 10, 731, 141))
        self.textKdera.setReadOnly(True)
        self.textKdera.setObjectName("textKdera")
        self.tabStatus.addTab(self.tabKDERA, "")
        self.tabDSMCTrace = QtWidgets.QWidget()
        self.tabDSMCTrace.setObjectName("tabDSMCTrace")
        self.textDsmc = QtWidgets.QTextEdit(self.tabDSMCTrace)
        self.textDsmc.setGeometry(QtCore.QRect(10, 10, 731, 141))
        self.textDsmc.setReadOnly(True)
        self.textDsmc.setObjectName("textDsmc")
        self.tabStatus.addTab(self.tabDSMCTrace, "")
        self.groupTemp = QtWidgets.QGroupBox(self.centralwidget)
        self.groupTemp.setGeometry(QtCore.QRect(10, 10, 581, 61))
        self.groupTemp.setObjectName("groupTemp")
        self.lineActualPackageTemp = QtWidgets.QLineEdit(self.groupTemp)
        self.lineActualPackageTemp.setGeometry(QtCore.QRect(200, 20, 41, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lineActualPackageTemp.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineActualPackageTemp.setFont(font)
        self.lineActualPackageTemp.setText("")
        self.lineActualPackageTemp.setObjectName("lineActualPackageTemp")
        self.label_7 = QtWidgets.QLabel(self.groupTemp)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 51, 20))
        self.label_7.setObjectName("label_7")
        self.btnSetPackageTemp = QtWidgets.QPushButton(self.groupTemp)
        self.btnSetPackageTemp.setGeometry(QtCore.QRect(110, 23, 41, 21))
        self.btnSetPackageTemp.setObjectName("btnSetPackageTemp")
        self.label_10 = QtWidgets.QLabel(self.groupTemp)
        self.label_10.setGeometry(QtCore.QRect(160, 20, 41, 20))
        self.label_10.setObjectName("label_10")
        self.btnSetDieTemp = QtWidgets.QPushButton(self.groupTemp)
        self.btnSetDieTemp.setGeometry(QtCore.QRect(440, 23, 41, 21))
        self.btnSetDieTemp.setObjectName("btnSetDieTemp")
        self.lineActualDieTemp = QtWidgets.QLineEdit(self.groupTemp)
        self.lineActualDieTemp.setGeometry(QtCore.QRect(530, 20, 41, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineActualDieTemp.setFont(font)
        self.lineActualDieTemp.setText("")
        self.lineActualDieTemp.setObjectName("lineActualDieTemp")
        self.label_11 = QtWidgets.QLabel(self.groupTemp)
        self.label_11.setGeometry(QtCore.QRect(490, 20, 41, 20))
        self.label_11.setObjectName("label_11")
        self.spinPackageTemp = QtWidgets.QDoubleSpinBox(self.groupTemp)
        self.spinPackageTemp.setGeometry(QtCore.QRect(60, 20, 51, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.spinPackageTemp.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spinPackageTemp.setFont(font)
        self.spinPackageTemp.setDecimals(1)
        self.spinPackageTemp.setMinimum(-30.0)
        self.spinPackageTemp.setMaximum(130.0)
        self.spinPackageTemp.setSingleStep(0.1)
        self.spinPackageTemp.setProperty("value", 25.0)
        self.spinPackageTemp.setObjectName("spinPackageTemp")
        self.spinDieTemp = QtWidgets.QDoubleSpinBox(self.groupTemp)
        self.spinDieTemp.setGeometry(QtCore.QRect(390, 20, 51, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.spinDieTemp.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spinDieTemp.setFont(font)
        self.spinDieTemp.setDecimals(1)
        self.spinDieTemp.setMinimum(-30.0)
        self.spinDieTemp.setMaximum(130.0)
        self.spinDieTemp.setSingleStep(0.1)
        self.spinDieTemp.setProperty("value", 88.0)
        self.spinDieTemp.setObjectName("spinDieTemp")
        self.chkDieTempAutoAdjust = QtWidgets.QCheckBox(self.groupTemp)
        self.chkDieTempAutoAdjust.setGeometry(QtCore.QRect(260, 10, 131, 23))
        self.chkDieTempAutoAdjust.setChecked(False)
        self.chkDieTempAutoAdjust.setObjectName("chkDieTempAutoAdjust")
        self.chkDieTempStopWhenStable = QtWidgets.QCheckBox(self.groupTemp)
        self.chkDieTempStopWhenStable.setGeometry(QtCore.QRect(260, 30, 131, 23))
        self.chkDieTempStopWhenStable.setChecked(False)
        self.chkDieTempStopWhenStable.setObjectName("chkDieTempStopWhenStable")
        self.tabMain = QtWidgets.QTabWidget(self.centralwidget)
        self.tabMain.setEnabled(True)
        self.tabMain.setGeometry(QtCore.QRect(10, 80, 761, 321))
        self.tabMain.setElideMode(QtCore.Qt.ElideLeft)
        self.tabMain.setTabBarAutoHide(False)
        self.tabMain.setObjectName("tabMain")
        self.tabAuto = QtWidgets.QWidget()
        self.tabAuto.setObjectName("tabAuto")
        self.groupSetup = QtWidgets.QGroupBox(self.tabAuto)
        self.groupSetup.setGeometry(QtCore.QRect(10, 10, 731, 271))
        self.groupSetup.setObjectName("groupSetup")
        self.lineAutoFile = QtWidgets.QLineEdit(self.groupSetup)
        self.lineAutoFile.setGeometry(QtCore.QRect(80, 240, 181, 21))
        self.lineAutoFile.setObjectName("lineAutoFile")
        self.label_9 = QtWidgets.QLabel(self.groupSetup)
        self.label_9.setGeometry(QtCore.QRect(20, 240, 61, 20))
        self.label_9.setObjectName("label_9")
        self.btnAutoFileLoad = QtWidgets.QPushButton(self.groupSetup)
        self.btnAutoFileLoad.setGeometry(QtCore.QRect(330, 240, 71, 21))
        self.btnAutoFileLoad.setObjectName("btnAutoFileLoad")
        self.progAuto = QtWidgets.QProgressBar(self.groupSetup)
        self.progAuto.setGeometry(QtCore.QRect(420, 240, 131, 20))
        self.progAuto.setProperty("value", 0)
        self.progAuto.setInvertedAppearance(False)
        self.progAuto.setObjectName("progAuto")
        self.btnAutoStop = QtWidgets.QPushButton(self.groupSetup)
        self.btnAutoStop.setGeometry(QtCore.QRect(640, 240, 81, 21))
        self.btnAutoStop.setObjectName("btnAutoStop")
        self.btnAutoGo = QtWidgets.QPushButton(self.groupSetup)
        self.btnAutoGo.setGeometry(QtCore.QRect(560, 240, 81, 21))
        self.btnAutoGo.setObjectName("btnAutoGo")
        self.comboAutoRailsBoardType = QtWidgets.QComboBox(self.groupSetup)
        self.comboAutoRailsBoardType.setGeometry(QtCore.QRect(70, 20, 131, 21))
        self.comboAutoRailsBoardType.setObjectName("comboAutoRailsBoardType")
        self.label_42 = QtWidgets.QLabel(self.groupSetup)
        self.label_42.setGeometry(QtCore.QRect(10, 20, 61, 20))
        self.label_42.setObjectName("label_42")
        self.tableAutoFile = QtWidgets.QTableWidget(self.groupSetup)
        self.tableAutoFile.setEnabled(True)
        self.tableAutoFile.setGeometry(QtCore.QRect(10, 80, 711, 151))
        self.tableAutoFile.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableAutoFile.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableAutoFile.setWordWrap(False)
        self.tableAutoFile.setObjectName("tableAutoFile")
        self.tableAutoFile.setColumnCount(0)
        self.tableAutoFile.setRowCount(0)
        self.chkAutoSkipTemp = QtWidgets.QCheckBox(self.groupSetup)
        self.chkAutoSkipTemp.setGeometry(QtCore.QRect(10, 50, 71, 21))
        self.chkAutoSkipTemp.setChecked(False)
        self.chkAutoSkipTemp.setObjectName("chkAutoSkipTemp")
        self.btnAutoFileBrowse = QtWidgets.QPushButton(self.groupSetup)
        self.btnAutoFileBrowse.setGeometry(QtCore.QRect(260, 240, 71, 21))
        self.btnAutoFileBrowse.setObjectName("btnAutoFileBrowse")
        self.btnAutoConfigFileLoad = QtWidgets.QPushButton(self.groupSetup)
        self.btnAutoConfigFileLoad.setGeometry(QtCore.QRect(480, 20, 61, 21))
        self.btnAutoConfigFileLoad.setObjectName("btnAutoConfigFileLoad")
        self.label_12 = QtWidgets.QLabel(self.groupSetup)
        self.label_12.setGeometry(QtCore.QRect(220, 20, 71, 20))
        self.label_12.setObjectName("label_12")
        self.btnAutoConfigFileBrowse = QtWidgets.QPushButton(self.groupSetup)
        self.btnAutoConfigFileBrowse.setGeometry(QtCore.QRect(420, 20, 61, 21))
        self.btnAutoConfigFileBrowse.setObjectName("btnAutoConfigFileBrowse")
        self.lineAutoConfigFile = QtWidgets.QLineEdit(self.groupSetup)
        self.lineAutoConfigFile.setGeometry(QtCore.QRect(290, 20, 131, 21))
        self.lineAutoConfigFile.setObjectName("lineAutoConfigFile")
        self.label_13 = QtWidgets.QLabel(self.groupSetup)
        self.label_13.setGeometry(QtCore.QRect(310, 50, 71, 20))
        self.label_13.setObjectName("label_13")
        self.lineAutoKnownErrorFiles = QtWidgets.QLineEdit(self.groupSetup)
        self.lineAutoKnownErrorFiles.setGeometry(QtCore.QRect(380, 50, 271, 21))
        self.lineAutoKnownErrorFiles.setObjectName("lineAutoKnownErrorFiles")
        self.chkAutoOneSample = QtWidgets.QCheckBox(self.groupSetup)
        self.chkAutoOneSample.setGeometry(QtCore.QRect(550, 20, 81, 21))
        self.chkAutoOneSample.setChecked(False)
        self.chkAutoOneSample.setObjectName("chkAutoOneSample")
        self.lineAutoHdtip = QtWidgets.QLineEdit(self.groupSetup)
        self.lineAutoHdtip.setEnabled(True)
        self.lineAutoHdtip.setGeometry(QtCore.QRect(130, 50, 91, 21))
        self.lineAutoHdtip.setObjectName("lineAutoHdtip")
        self.label_43 = QtWidgets.QLabel(self.groupSetup)
        self.label_43.setGeometry(QtCore.QRect(90, 50, 41, 20))
        self.label_43.setObjectName("label_43")
        self.chkAutoSoftFusing = QtWidgets.QCheckBox(self.groupSetup)
        self.chkAutoSoftFusing.setGeometry(QtCore.QRect(230, 50, 81, 21))
        self.chkAutoSoftFusing.setChecked(False)
        self.chkAutoSoftFusing.setObjectName("chkAutoSoftFusing")
        self.chkAutoTether = QtWidgets.QCheckBox(self.groupSetup)
        self.chkAutoTether.setGeometry(QtCore.QRect(660, 50, 51, 21))
        self.chkAutoTether.setChecked(False)
        self.chkAutoTether.setObjectName("chkAutoTether")
        self.chkAutoPool = QtWidgets.QCheckBox(self.groupSetup)
        self.chkAutoPool.setEnabled(True)
        self.chkAutoPool.setGeometry(QtCore.QRect(630, 20, 91, 23))
        self.chkAutoPool.setToolTip("")
        self.chkAutoPool.setChecked(False)
        self.chkAutoPool.setObjectName("chkAutoPool")
        self.tabMain.addTab(self.tabAuto, "")
        self.tabManual = QtWidgets.QWidget()
        self.tabManual.setObjectName("tabManual")
        self.groupTec = QtWidgets.QGroupBox(self.tabManual)
        self.groupTec.setGeometry(QtCore.QRect(10, 0, 131, 81))
        self.groupTec.setObjectName("groupTec")
        self.lineTecComPort = QtWidgets.QLineEdit(self.groupTec)
        self.lineTecComPort.setGeometry(QtCore.QRect(60, 20, 51, 21))
        self.lineTecComPort.setObjectName("lineTecComPort")
        self.label_28 = QtWidgets.QLabel(self.groupTec)
        self.label_28.setGeometry(QtCore.QRect(10, 20, 51, 20))
        self.label_28.setObjectName("label_28")
        self.btnTecComPortUpdate = QtWidgets.QPushButton(self.groupTec)
        self.btnTecComPortUpdate.setGeometry(QtCore.QRect(50, 50, 61, 21))
        self.btnTecComPortUpdate.setObjectName("btnTecComPortUpdate")
        self.groupDebugger = QtWidgets.QGroupBox(self.tabManual)
        self.groupDebugger.setGeometry(QtCore.QRect(10, 160, 131, 121))
        self.groupDebugger.setObjectName("groupDebugger")
        self.lineDebuggerIp = QtWidgets.QLineEdit(self.groupDebugger)
        self.lineDebuggerIp.setGeometry(QtCore.QRect(30, 20, 81, 21))
        self.lineDebuggerIp.setObjectName("lineDebuggerIp")
        self.label_22 = QtWidgets.QLabel(self.groupDebugger)
        self.label_22.setGeometry(QtCore.QRect(10, 20, 16, 20))
        self.label_22.setObjectName("label_22")
        self.btnDebuggerIpUpdate = QtWidgets.QPushButton(self.groupDebugger)
        self.btnDebuggerIpUpdate.setGeometry(QtCore.QRect(50, 50, 61, 21))
        self.btnDebuggerIpUpdate.setObjectName("btnDebuggerIpUpdate")
        self.groupConsole = QtWidgets.QGroupBox(self.tabManual)
        self.groupConsole.setGeometry(QtCore.QRect(470, 0, 271, 281))
        self.groupConsole.setObjectName("groupConsole")
        self.lineConsoleHostIP = QtWidgets.QLineEdit(self.groupConsole)
        self.lineConsoleHostIP.setEnabled(False)
        self.lineConsoleHostIP.setGeometry(QtCore.QRect(70, 80, 131, 21))
        self.lineConsoleHostIP.setObjectName("lineConsoleHostIP")
        self.label_23 = QtWidgets.QLabel(self.groupConsole)
        self.label_23.setGeometry(QtCore.QRect(20, 80, 41, 20))
        self.label_23.setObjectName("label_23")
        self.btnConsoleDiscover = QtWidgets.QPushButton(self.groupConsole)
        self.btnConsoleDiscover.setGeometry(QtCore.QRect(200, 30, 61, 21))
        self.btnConsoleDiscover.setObjectName("btnConsoleDiscover")
        self.label_30 = QtWidgets.QLabel(self.groupConsole)
        self.label_30.setGeometry(QtCore.QRect(10, 130, 61, 20))
        self.label_30.setObjectName("label_30")
        self.btnConsoleCommandSend = QtWidgets.QPushButton(self.groupConsole)
        self.btnConsoleCommandSend.setGeometry(QtCore.QRect(200, 170, 61, 21))
        self.btnConsoleCommandSend.setObjectName("btnConsoleCommandSend")
        self.comboConsoleAction = QtWidgets.QComboBox(self.groupConsole)
        self.comboConsoleAction.setGeometry(QtCore.QRect(30, 150, 231, 21))
        self.comboConsoleAction.setObjectName("comboConsoleAction")
        self.labelConsoleActionDesc = QtWidgets.QLabel(self.groupConsole)
        self.labelConsoleActionDesc.setGeometry(QtCore.QRect(40, 170, 161, 20))
        self.labelConsoleActionDesc.setObjectName("labelConsoleActionDesc")
        self.comboDeployApps = QtWidgets.QComboBox(self.groupConsole)
        self.comboDeployApps.setGeometry(QtCore.QRect(10, 210, 131, 21))
        self.comboDeployApps.setObjectName("comboDeployApps")
        self.btnAppDeploy = QtWidgets.QPushButton(self.groupConsole)
        self.btnAppDeploy.setGeometry(QtCore.QRect(140, 210, 61, 21))
        self.btnAppDeploy.setObjectName("btnAppDeploy")
        self.label_31 = QtWidgets.QLabel(self.groupConsole)
        self.label_31.setGeometry(QtCore.QRect(10, 190, 81, 20))
        self.label_31.setObjectName("label_31")
        self.lineConsoleSystemIP = QtWidgets.QLineEdit(self.groupConsole)
        self.lineConsoleSystemIP.setEnabled(False)
        self.lineConsoleSystemIP.setGeometry(QtCore.QRect(70, 100, 131, 21))
        self.lineConsoleSystemIP.setObjectName("lineConsoleSystemIP")
        self.label_32 = QtWidgets.QLabel(self.groupConsole)
        self.label_32.setGeometry(QtCore.QRect(10, 100, 51, 20))
        self.label_32.setObjectName("label_32")
        self.btnAppLaunch = QtWidgets.QPushButton(self.groupConsole)
        self.btnAppLaunch.setGeometry(QtCore.QRect(140, 230, 61, 21))
        self.btnAppLaunch.setObjectName("btnAppLaunch")
        self.comboLaunchTerminateApps = QtWidgets.QComboBox(self.groupConsole)
        self.comboLaunchTerminateApps.setGeometry(QtCore.QRect(10, 230, 131, 21))
        self.comboLaunchTerminateApps.setObjectName("comboLaunchTerminateApps")
        self.btnAppDeployAll = QtWidgets.QPushButton(self.groupConsole)
        self.btnAppDeployAll.setGeometry(QtCore.QRect(200, 210, 61, 21))
        self.btnAppDeployAll.setObjectName("btnAppDeployAll")
        self.btnAppTerminate = QtWidgets.QPushButton(self.groupConsole)
        self.btnAppTerminate.setGeometry(QtCore.QRect(200, 230, 61, 21))
        self.btnAppTerminate.setObjectName("btnAppTerminate")
        self.label_29 = QtWidgets.QLabel(self.groupConsole)
        self.label_29.setGeometry(QtCore.QRect(30, 30, 41, 20))
        self.label_29.setObjectName("label_29")
        self.lineConsoleHdtip = QtWidgets.QLineEdit(self.groupConsole)
        self.lineConsoleHdtip.setEnabled(True)
        self.lineConsoleHdtip.setGeometry(QtCore.QRect(70, 30, 131, 21))
        self.lineConsoleHdtip.setObjectName("lineConsoleHdtip")
        self.chkConsoleSoftFusing = QtWidgets.QCheckBox(self.groupConsole)
        self.chkConsoleSoftFusing.setGeometry(QtCore.QRect(70, 50, 81, 23))
        self.chkConsoleSoftFusing.setChecked(False)
        self.chkConsoleSoftFusing.setObjectName("chkConsoleSoftFusing")
        self.btnConsolePingHost = QtWidgets.QPushButton(self.groupConsole)
        self.btnConsolePingHost.setGeometry(QtCore.QRect(200, 80, 61, 21))
        self.btnConsolePingHost.setObjectName("btnConsolePingHost")
        self.btnConsolePingSystem = QtWidgets.QPushButton(self.groupConsole)
        self.btnConsolePingSystem.setGeometry(QtCore.QRect(200, 100, 61, 21))
        self.btnConsolePingSystem.setObjectName("btnConsolePingSystem")
        self.chkConsoleTether = QtWidgets.QCheckBox(self.groupConsole)
        self.chkConsoleTether.setGeometry(QtCore.QRect(150, 50, 61, 23))
        self.chkConsoleTether.setChecked(False)
        self.chkConsoleTether.setObjectName("chkConsoleTether")
        self.groupVideoRes = QtWidgets.QGroupBox(self.tabManual)
        self.groupVideoRes.setGeometry(QtCore.QRect(10, 80, 131, 81))
        self.groupVideoRes.setObjectName("groupVideoRes")
        self.comboResolutions = QtWidgets.QComboBox(self.groupVideoRes)
        self.comboResolutions.setGeometry(QtCore.QRect(10, 20, 101, 21))
        self.comboResolutions.setObjectName("comboResolutions")
        self.btnResolutionUpdate = QtWidgets.QPushButton(self.groupVideoRes)
        self.btnResolutionUpdate.setGeometry(QtCore.QRect(50, 50, 61, 21))
        self.btnResolutionUpdate.setObjectName("btnResolutionUpdate")
        self.groupRails = QtWidgets.QGroupBox(self.tabManual)
        self.groupRails.setGeometry(QtCore.QRect(150, 0, 311, 281))
        self.groupRails.setObjectName("groupRails")
        self.lineCpuVolt = QtWidgets.QLineEdit(self.groupRails)
        self.lineCpuVolt.setGeometry(QtCore.QRect(200, 60, 71, 21))
        self.lineCpuVolt.setReadOnly(True)
        self.lineCpuVolt.setObjectName("lineCpuVolt")
        self.chkCpu = QtWidgets.QCheckBox(self.groupRails)
        self.chkCpu.setGeometry(QtCore.QRect(70, 60, 30, 23))
        self.chkCpu.setText("")
        self.chkCpu.setChecked(True)
        self.chkCpu.setObjectName("chkCpu")
        self.lineNbVolt = QtWidgets.QLineEdit(self.groupRails)
        self.lineNbVolt.setGeometry(QtCore.QRect(200, 80, 71, 21))
        self.lineNbVolt.setObjectName("lineNbVolt")
        self.chkNbsoc = QtWidgets.QCheckBox(self.groupRails)
        self.chkNbsoc.setGeometry(QtCore.QRect(70, 80, 30, 23))
        self.chkNbsoc.setText("")
        self.chkNbsoc.setChecked(True)
        self.chkNbsoc.setObjectName("chkNbsoc")
        self.spinNbsoc = QtWidgets.QSpinBox(self.groupRails)
        self.spinNbsoc.setGeometry(QtCore.QRect(90, 80, 71, 21))
        self.spinNbsoc.setMaximum(2000)
        self.spinNbsoc.setSingleStep(10)
        self.spinNbsoc.setProperty("value", 1000)
        self.spinNbsoc.setObjectName("spinNbsoc")
        self.spinGfx = QtWidgets.QSpinBox(self.groupRails)
        self.spinGfx.setGeometry(QtCore.QRect(90, 40, 71, 21))
        self.spinGfx.setMaximum(2000)
        self.spinGfx.setSingleStep(10)
        self.spinGfx.setProperty("value", 1000)
        self.spinGfx.setObjectName("spinGfx")
        self.chkGfx = QtWidgets.QCheckBox(self.groupRails)
        self.chkGfx.setGeometry(QtCore.QRect(70, 40, 30, 23))
        self.chkGfx.setText("")
        self.chkGfx.setChecked(True)
        self.chkGfx.setObjectName("chkGfx")
        self.spinCpu = QtWidgets.QSpinBox(self.groupRails)
        self.spinCpu.setGeometry(QtCore.QRect(90, 60, 71, 21))
        self.spinCpu.setMaximum(2000)
        self.spinCpu.setSingleStep(10)
        self.spinCpu.setProperty("value", 1000)
        self.spinCpu.setObjectName("spinCpu")
        self.label_24 = QtWidgets.QLabel(self.groupRails)
        self.label_24.setGeometry(QtCore.QRect(20, 80, 51, 20))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupRails)
        self.label_25.setGeometry(QtCore.QRect(40, 60, 31, 20))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupRails)
        self.label_26.setGeometry(QtCore.QRect(40, 40, 31, 20))
        self.label_26.setObjectName("label_26")
        self.btnRailsSet = QtWidgets.QPushButton(self.groupRails)
        self.btnRailsSet.setGeometry(QtCore.QRect(90, 130, 71, 21))
        self.btnRailsSet.setObjectName("btnRailsSet")
        self.lineGfxVolt = QtWidgets.QLineEdit(self.groupRails)
        self.lineGfxVolt.setGeometry(QtCore.QRect(200, 40, 71, 21))
        self.lineGfxVolt.setReadOnly(True)
        self.lineGfxVolt.setObjectName("lineGfxVolt")
        self.lineMemphyVolt = QtWidgets.QLineEdit(self.groupRails)
        self.lineMemphyVolt.setGeometry(QtCore.QRect(200, 100, 71, 21))
        self.lineMemphyVolt.setObjectName("lineMemphyVolt")
        self.spinMemphy = QtWidgets.QSpinBox(self.groupRails)
        self.spinMemphy.setGeometry(QtCore.QRect(90, 100, 71, 21))
        self.spinMemphy.setMaximum(2000)
        self.spinMemphy.setSingleStep(10)
        self.spinMemphy.setProperty("value", 1000)
        self.spinMemphy.setObjectName("spinMemphy")
        self.label_27 = QtWidgets.QLabel(self.groupRails)
        self.label_27.setGeometry(QtCore.QRect(20, 100, 51, 20))
        self.label_27.setObjectName("label_27")
        self.chkMemphy = QtWidgets.QCheckBox(self.groupRails)
        self.chkMemphy.setGeometry(QtCore.QRect(70, 100, 30, 23))
        self.chkMemphy.setText("")
        self.chkMemphy.setChecked(True)
        self.chkMemphy.setObjectName("chkMemphy")
        self.btnRailsGet = QtWidgets.QPushButton(self.groupRails)
        self.btnRailsGet.setGeometry(QtCore.QRect(200, 130, 71, 21))
        self.btnRailsGet.setObjectName("btnRailsGet")
        self.comboRailsBoardType = QtWidgets.QComboBox(self.groupRails)
        self.comboRailsBoardType.setGeometry(QtCore.QRect(90, 15, 211, 21))
        self.comboRailsBoardType.setObjectName("comboRailsBoardType")
        self.label_33 = QtWidgets.QLabel(self.groupRails)
        self.label_33.setGeometry(QtCore.QRect(30, 15, 61, 20))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.groupRails)
        self.label_34.setGeometry(QtCore.QRect(170, 40, 21, 20))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.groupRails)
        self.label_35.setGeometry(QtCore.QRect(280, 40, 21, 20))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.groupRails)
        self.label_36.setGeometry(QtCore.QRect(170, 60, 21, 20))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.groupRails)
        self.label_37.setGeometry(QtCore.QRect(280, 60, 21, 20))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupRails)
        self.label_38.setGeometry(QtCore.QRect(170, 80, 21, 20))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.groupRails)
        self.label_39.setGeometry(QtCore.QRect(280, 80, 21, 20))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.groupRails)
        self.label_40.setGeometry(QtCore.QRect(170, 100, 21, 20))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.groupRails)
        self.label_41.setGeometry(QtCore.QRect(280, 100, 21, 20))
        self.label_41.setObjectName("label_41")
        self.tabMain.addTab(self.tabManual, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupSampling = QtWidgets.QGroupBox(self.tab)
        self.groupSampling.setGeometry(QtCore.QRect(10, 10, 731, 271))
        self.groupSampling.setObjectName("groupSampling")
        self.lineSampleCount = QtWidgets.QLineEdit(self.groupSampling)
        self.lineSampleCount.setGeometry(QtCore.QRect(680, 70, 41, 21))
        self.lineSampleCount.setObjectName("lineSampleCount")
        self.lineSampleRate = QtWidgets.QLineEdit(self.groupSampling)
        self.lineSampleRate.setGeometry(QtCore.QRect(680, 30, 41, 21))
        self.lineSampleRate.setObjectName("lineSampleRate")
        self.lineSampleOversample = QtWidgets.QLineEdit(self.groupSampling)
        self.lineSampleOversample.setGeometry(QtCore.QRect(680, 50, 41, 21))
        self.lineSampleOversample.setObjectName("lineSampleOversample")
        self.label_2 = QtWidgets.QLabel(self.groupSampling)
        self.label_2.setGeometry(QtCore.QRect(620, 50, 61, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupSampling)
        self.label_3.setGeometry(QtCore.QRect(610, 70, 71, 20))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.groupSampling)
        self.label.setGeometry(QtCore.QRect(590, 30, 91, 20))
        self.label.setObjectName("label")
        self.lineSamplingOutputFile = QtWidgets.QLineEdit(self.groupSampling)
        self.lineSamplingOutputFile.setGeometry(QtCore.QRect(90, 40, 291, 21))
        self.lineSamplingOutputFile.setObjectName("lineSamplingOutputFile")
        self.lineSamplingConfigFile = QtWidgets.QLineEdit(self.groupSampling)
        self.lineSamplingConfigFile.setGeometry(QtCore.QRect(90, 20, 291, 21))
        self.lineSamplingConfigFile.setObjectName("lineSamplingConfigFile")
        self.progSamplingOutput = QtWidgets.QProgressBar(self.groupSampling)
        self.progSamplingOutput.setGeometry(QtCore.QRect(390, 45, 191, 16))
        self.progSamplingOutput.setProperty("value", 0)
        self.progSamplingOutput.setInvertedAppearance(False)
        self.progSamplingOutput.setObjectName("progSamplingOutput")
        self.btnSamplingStop = QtWidgets.QPushButton(self.groupSampling)
        self.btnSamplingStop.setGeometry(QtCore.QRect(170, 70, 81, 21))
        self.btnSamplingStop.setObjectName("btnSamplingStop")
        self.btnSamplingConfigFileLoad = QtWidgets.QPushButton(self.groupSampling)
        self.btnSamplingConfigFileLoad.setGeometry(QtCore.QRect(490, 20, 91, 21))
        self.btnSamplingConfigFileLoad.setObjectName("btnSamplingConfigFileLoad")
        self.btnSamplingGo = QtWidgets.QPushButton(self.groupSampling)
        self.btnSamplingGo.setGeometry(QtCore.QRect(90, 70, 81, 21))
        self.btnSamplingGo.setObjectName("btnSamplingGo")
        self.label_4 = QtWidgets.QLabel(self.groupSampling)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 51, 20))
        self.label_4.setObjectName("label_4")
        self.btnSamplingOneSample = QtWidgets.QPushButton(self.groupSampling)
        self.btnSamplingOneSample.setGeometry(QtCore.QRect(10, 70, 81, 21))
        self.btnSamplingOneSample.setObjectName("btnSamplingOneSample")
        self.btnSamplingConfigFileBrowse = QtWidgets.QPushButton(self.groupSampling)
        self.btnSamplingConfigFileBrowse.setGeometry(QtCore.QRect(390, 20, 91, 21))
        self.btnSamplingConfigFileBrowse.setObjectName("btnSamplingConfigFileBrowse")
        self.tableSampling = QtWidgets.QTableWidget(self.groupSampling)
        self.tableSampling.setEnabled(True)
        self.tableSampling.setGeometry(QtCore.QRect(10, 100, 581, 163))
        self.tableSampling.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableSampling.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableSampling.setWordWrap(False)
        self.tableSampling.setRowCount(0)
        self.tableSampling.setColumnCount(0)
        self.tableSampling.setObjectName("tableSampling")
        self.btnSamplingReset = QtWidgets.QPushButton(self.groupSampling)
        self.btnSamplingReset.setGeometry(QtCore.QRect(600, 220, 61, 21))
        self.btnSamplingReset.setObjectName("btnSamplingReset")
        self.btnSamplingFreeze = QtWidgets.QPushButton(self.groupSampling)
        self.btnSamplingFreeze.setGeometry(QtCore.QRect(660, 220, 61, 21))
        self.btnSamplingFreeze.setObjectName("btnSamplingFreeze")
        self.btnSamplingClipboard = QtWidgets.QPushButton(self.groupSampling)
        self.btnSamplingClipboard.setGeometry(QtCore.QRect(600, 240, 121, 21))
        self.btnSamplingClipboard.setObjectName("btnSamplingClipboard")
        self.btnSamplingLive = QtWidgets.QPushButton(self.groupSampling)
        self.btnSamplingLive.setGeometry(QtCore.QRect(260, 70, 81, 21))
        self.btnSamplingLive.setObjectName("btnSamplingLive")
        self.chkSamplingOverride = QtWidgets.QCheckBox(self.groupSampling)
        self.chkSamplingOverride.setGeometry(QtCore.QRect(590, 10, 131, 23))
        self.chkSamplingOverride.setChecked(False)
        self.chkSamplingOverride.setObjectName("chkSamplingOverride")
        self.comboSamplingPlotOptions = QtWidgets.QComboBox(self.groupSampling)
        self.comboSamplingPlotOptions.setGeometry(QtCore.QRect(595, 100, 126, 21))
        self.comboSamplingPlotOptions.setObjectName("comboSamplingPlotOptions")
        self.labelPlotTheseColumns = QtWidgets.QLabel(self.groupSampling)
        self.labelPlotTheseColumns.setGeometry(QtCore.QRect(595, 140, 121, 20))
        self.labelPlotTheseColumns.setObjectName("labelPlotTheseColumns")
        self.labelPlot1 = QtWidgets.QLabel(self.groupSampling)
        self.labelPlot1.setGeometry(QtCore.QRect(595, 160, 41, 20))
        self.labelPlot1.setObjectName("labelPlot1")
        self.labelPlot2 = QtWidgets.QLabel(self.groupSampling)
        self.labelPlot2.setGeometry(QtCore.QRect(640, 160, 41, 20))
        self.labelPlot2.setObjectName("labelPlot2")
        self.labelPlot3 = QtWidgets.QLabel(self.groupSampling)
        self.labelPlot3.setGeometry(QtCore.QRect(680, 160, 41, 20))
        self.labelPlot3.setObjectName("labelPlot3")
        self.chkSamplingOutputFile = QtWidgets.QCheckBox(self.groupSampling)
        self.chkSamplingOutputFile.setGeometry(QtCore.QRect(10, 40, 71, 23))
        self.chkSamplingOutputFile.setChecked(True)
        self.chkSamplingOutputFile.setObjectName("chkSamplingOutputFile")
        self.label_5 = QtWidgets.QLabel(self.groupSampling)
        self.label_5.setGeometry(QtCore.QRect(470, 70, 61, 20))
        self.label_5.setObjectName("label_5")
        self.lineSamplingTotalPower = QtWidgets.QLineEdit(self.groupSampling)
        self.lineSamplingTotalPower.setGeometry(QtCore.QRect(530, 70, 61, 21))
        self.lineSamplingTotalPower.setText("")
        self.lineSamplingTotalPower.setObjectName("lineSamplingTotalPower")
        self.comboSamplingFrame = QtWidgets.QComboBox(self.groupSampling)
        self.comboSamplingFrame.setGeometry(QtCore.QRect(595, 120, 126, 21))
        self.comboSamplingFrame.setObjectName("comboSamplingFrame")
        self.labelPlot6 = QtWidgets.QLabel(self.groupSampling)
        self.labelPlot6.setGeometry(QtCore.QRect(680, 180, 41, 20))
        self.labelPlot6.setObjectName("labelPlot6")
        self.labelPlot5 = QtWidgets.QLabel(self.groupSampling)
        self.labelPlot5.setGeometry(QtCore.QRect(640, 180, 41, 20))
        self.labelPlot5.setObjectName("labelPlot5")
        self.labelPlot4 = QtWidgets.QLabel(self.groupSampling)
        self.labelPlot4.setGeometry(QtCore.QRect(595, 180, 41, 20))
        self.labelPlot4.setObjectName("labelPlot4")
        self.labelPlot7 = QtWidgets.QLabel(self.groupSampling)
        self.labelPlot7.setGeometry(QtCore.QRect(595, 200, 41, 20))
        self.labelPlot7.setObjectName("labelPlot7")
        self.labelPlot8 = QtWidgets.QLabel(self.groupSampling)
        self.labelPlot8.setGeometry(QtCore.QRect(640, 200, 41, 20))
        self.labelPlot8.setObjectName("labelPlot8")
        self.labelPlot9 = QtWidgets.QLabel(self.groupSampling)
        self.labelPlot9.setGeometry(QtCore.QRect(680, 200, 41, 20))
        self.labelPlot9.setObjectName("labelPlot9")
        self.chkSamplingPool = QtWidgets.QCheckBox(self.groupSampling)
        self.chkSamplingPool.setEnabled(True)
        self.chkSamplingPool.setGeometry(QtCore.QRect(360, 70, 101, 23))
        self.chkSamplingPool.setChecked(False)
        self.chkSamplingPool.setObjectName("chkSamplingPool")
        self.tabMain.addTab(self.tab, "")
        self.btnScreenshot = QtWidgets.QPushButton(self.centralwidget)
        self.btnScreenshot.setGeometry(QtCore.QRect(600, 10, 161, 71))
        self.btnScreenshot.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("XboxLogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnScreenshot.setIcon(icon)
        self.btnScreenshot.setIconSize(QtCore.QSize(161, 71))
        self.btnScreenshot.setFlat(True)
        self.btnScreenshot.setObjectName("btnScreenshot")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 779, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabStatus.setCurrentIndex(0)
        self.tabMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Microsoft SoC Validator"))
        self.tabStatus.setTabText(self.tabStatus.indexOf(self.tabStatus1), _translate("MainWindow", "Status"))
        self.tabStatus.setTabText(self.tabStatus.indexOf(self.tabKDHost), _translate("MainWindow", "KDHost"))
        self.tabStatus.setTabText(self.tabStatus.indexOf(self.tabKDSRA), _translate("MainWindow", "KDSRA"))
        self.tabStatus.setTabText(self.tabStatus.indexOf(self.tabKDERA), _translate("MainWindow", "KDERA"))
        self.tabStatus.setTabText(self.tabStatus.indexOf(self.tabDSMCTrace), _translate("MainWindow", "DSMCTrace"))
        self.groupTemp.setTitle(_translate("MainWindow", "Temperature"))
        self.label_7.setText(_translate("MainWindow", "TEC Temp"))
        self.btnSetPackageTemp.setText(_translate("MainWindow", "Set"))
        self.label_10.setText(_translate("MainWindow", "Actual"))
        self.btnSetDieTemp.setText(_translate("MainWindow", "Set"))
        self.label_11.setText(_translate("MainWindow", "Actual"))
        self.chkDieTempAutoAdjust.setText(_translate("MainWindow", "Auto Adjust Die Temp"))
        self.chkDieTempStopWhenStable.setText(_translate("MainWindow", "Stop when stable"))
        self.groupSetup.setTitle(_translate("MainWindow", "Setup"))
        self.lineAutoFile.setText(_translate("MainWindow", ".\\MyAppList.csv"))
        self.label_9.setText(_translate("MainWindow", "Test Script"))
        self.btnAutoFileLoad.setText(_translate("MainWindow", "Load"))
        self.btnAutoStop.setText(_translate("MainWindow", "Stop"))
        self.btnAutoGo.setText(_translate("MainWindow", "Go"))
        self.label_42.setText(_translate("MainWindow", "Board Type"))
        self.chkAutoSkipTemp.setText(_translate("MainWindow", "Skip Temp"))
        self.btnAutoFileBrowse.setText(_translate("MainWindow", "Browse..."))
        self.btnAutoConfigFileLoad.setText(_translate("MainWindow", "Load"))
        self.label_12.setText(_translate("MainWindow", "NI Daq Config"))
        self.btnAutoConfigFileBrowse.setText(_translate("MainWindow", "Browse..."))
        self.lineAutoConfigFile.setText(_translate("MainWindow", ".\\NIDaq.PJDAQ"))
        self.label_13.setText(_translate("MainWindow", "Known Errors"))
        self.lineAutoKnownErrorFiles.setText(_translate("MainWindow", ".\\KnownErrorExceptions.txt, .\\KnownErrorStrings.txt "))
        self.chkAutoOneSample.setText(_translate("MainWindow", "One Sample"))
        self.lineAutoHdtip.setText(_translate("MainWindow", "172.29.197.245"))
        self.label_43.setText(_translate("MainWindow", "HDTIP"))
        self.chkAutoSoftFusing.setText(_translate("MainWindow", "Soft Fusing"))
        self.chkAutoTether.setText(_translate("MainWindow", "Tether"))
        self.chkAutoPool.setText(_translate("MainWindow", "Multi-threaded"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabAuto), _translate("MainWindow", "Automation"))
        self.groupTec.setTitle(_translate("MainWindow", "TEC"))
        self.lineTecComPort.setText(_translate("MainWindow", "COM3"))
        self.label_28.setText(_translate("MainWindow", "COM Port"))
        self.btnTecComPortUpdate.setText(_translate("MainWindow", "Update"))
        self.groupDebugger.setTitle(_translate("MainWindow", "AMD HDT Debugger"))
        self.label_22.setText(_translate("MainWindow", "IP"))
        self.btnDebuggerIpUpdate.setText(_translate("MainWindow", "Update"))
        self.groupConsole.setTitle(_translate("MainWindow", "Xbox Console"))
        self.label_23.setText(_translate("MainWindow", "Host IP"))
        self.btnConsoleDiscover.setText(_translate("MainWindow", "Discover"))
        self.label_30.setText(_translate("MainWindow", "Command:"))
        self.btnConsoleCommandSend.setText(_translate("MainWindow", "Send"))
        self.labelConsoleActionDesc.setText(_translate("MainWindow", "(description of action)"))
        self.btnAppDeploy.setText(_translate("MainWindow", "Deploy"))
        self.label_31.setText(_translate("MainWindow", "Apps available:"))
        self.label_32.setText(_translate("MainWindow", "System IP"))
        self.btnAppLaunch.setText(_translate("MainWindow", "Launch"))
        self.btnAppDeployAll.setText(_translate("MainWindow", "Deploy All"))
        self.btnAppTerminate.setText(_translate("MainWindow", "Terminate"))
        self.label_29.setText(_translate("MainWindow", "HDTIP"))
        self.lineConsoleHdtip.setText(_translate("MainWindow", "172.29.197.245"))
        self.chkConsoleSoftFusing.setText(_translate("MainWindow", "Soft Fusing"))
        self.btnConsolePingHost.setText(_translate("MainWindow", "Ping"))
        self.btnConsolePingSystem.setText(_translate("MainWindow", "Ping"))
        self.chkConsoleTether.setText(_translate("MainWindow", "Tether"))
        self.groupVideoRes.setTitle(_translate("MainWindow", "Video Resolution"))
        self.btnResolutionUpdate.setText(_translate("MainWindow", "Update"))
        self.groupRails.setTitle(_translate("MainWindow", "Rails"))
        self.label_24.setText(_translate("MainWindow", "NB/SOC"))
        self.label_25.setText(_translate("MainWindow", "CPU"))
        self.label_26.setText(_translate("MainWindow", "GFX"))
        self.btnRailsSet.setText(_translate("MainWindow", "Set"))
        self.label_27.setText(_translate("MainWindow", "MEMPHY"))
        self.btnRailsGet.setText(_translate("MainWindow", "Get"))
        self.label_33.setText(_translate("MainWindow", "Board Type"))
        self.label_34.setText(_translate("MainWindow", "mV"))
        self.label_35.setText(_translate("MainWindow", "mV"))
        self.label_36.setText(_translate("MainWindow", "mV"))
        self.label_37.setText(_translate("MainWindow", "mV"))
        self.label_38.setText(_translate("MainWindow", "mV"))
        self.label_39.setText(_translate("MainWindow", "mV"))
        self.label_40.setText(_translate("MainWindow", "mV"))
        self.label_41.setText(_translate("MainWindow", "mV"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabManual), _translate("MainWindow", "Manual"))
        self.groupSampling.setTitle(_translate("MainWindow", "Sampling"))
        self.lineSampleCount.setText(_translate("MainWindow", "27778"))
        self.lineSampleRate.setText(_translate("MainWindow", "36000"))
        self.lineSampleOversample.setText(_translate("MainWindow", "1"))
        self.label_2.setText(_translate("MainWindow", "Oversample"))
        self.label_3.setText(_translate("MainWindow", "Sample Count"))
        self.label.setText(_translate("MainWindow", "Sample Rate (Hz)"))
        self.lineSamplingOutputFile.setText(_translate("MainWindow", ".\\Output.csv"))
        self.lineSamplingConfigFile.setText(_translate("MainWindow", ".\\NIDaq.PJDAQ"))
        self.btnSamplingStop.setText(_translate("MainWindow", "Stop"))
        self.btnSamplingConfigFileLoad.setText(_translate("MainWindow", "Load"))
        self.btnSamplingGo.setText(_translate("MainWindow", "Go"))
        self.label_4.setText(_translate("MainWindow", "Config File"))
        self.btnSamplingOneSample.setText(_translate("MainWindow", "One Sample"))
        self.btnSamplingConfigFileBrowse.setText(_translate("MainWindow", "Browse..."))
        self.btnSamplingReset.setText(_translate("MainWindow", "Reset"))
        self.btnSamplingFreeze.setText(_translate("MainWindow", "Freeze"))
        self.btnSamplingClipboard.setText(_translate("MainWindow", "Copy to Clipboard"))
        self.btnSamplingLive.setText(_translate("MainWindow", "Live"))
        self.chkSamplingOverride.setText(_translate("MainWindow", "Override parameters"))
        self.labelPlotTheseColumns.setText(_translate("MainWindow", "Plot these columns:"))
        self.labelPlot1.setText(_translate("MainWindow", "  1"))
        self.labelPlot2.setText(_translate("MainWindow", "  2"))
        self.labelPlot3.setText(_translate("MainWindow", "  3"))
        self.chkSamplingOutputFile.setText(_translate("MainWindow", "Output File"))
        self.label_5.setText(_translate("MainWindow", "Total Power"))
        self.labelPlot6.setText(_translate("MainWindow", "  6"))
        self.labelPlot5.setText(_translate("MainWindow", "  5"))
        self.labelPlot4.setText(_translate("MainWindow", "  4"))
        self.labelPlot7.setText(_translate("MainWindow", "  7"))
        self.labelPlot8.setText(_translate("MainWindow", "  8"))
        self.labelPlot9.setText(_translate("MainWindow", "  9"))
        self.chkSamplingPool.setText(_translate("MainWindow", "Multi-threaded"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tab), _translate("MainWindow", "NI DAQ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

