# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-12 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csnotifier', '0003_notification_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='desc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
