# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-18 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csnotifier', '0006_auto_20170328_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
