# Generated by Django 2.2.3 on 2019-07-04 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000, verbose_name='content')),
                ('nickname', models.CharField(max_length=50, verbose_name='nickname')),
                ('website', models.URLField(verbose_name='website')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('status', models.PositiveIntegerField(choices=[{1, 'normal'}, {0, 'delete'}], default=1, verbose_name='status')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='comment target')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comment',
            },
        ),
    ]
