# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _itkThresholdMaximumConnectedComponentsImageFilterPython.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_itkThresholdMaximumConnectedComponentsImageFilterPython', [dirname(__file__)])
        except ImportError:
            import _itkThresholdMaximumConnectedComponentsImageFilterPython
            return _itkThresholdMaximumConnectedComponentsImageFilterPython
        if fp is not None:
            try:
                _mod = imp.load_module('_itkThresholdMaximumConnectedComponentsImageFilterPython', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _itkThresholdMaximumConnectedComponentsImageFilterPython = swig_import_helper()
    del swig_import_helper
else:
    import _itkThresholdMaximumConnectedComponentsImageFilterPython
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


import itkImageToImageFilterAPython
import itkImagePython
import stdcomplexPython
import pyBasePython
import itkCovariantVectorPython
import itkVectorPython
import vnl_vectorPython
import vnl_matrixPython
import vnl_vector_refPython
import itkFixedArrayPython
import itkRGBPixelPython
import itkImageRegionPython
import itkIndexPython
import itkOffsetPython
import itkSizePython
import ITKCommonBasePython
import itkMatrixPython
import vnl_matrix_fixedPython
import itkPointPython
import itkSymmetricSecondRankTensorPython
import itkRGBAPixelPython
import itkImageSourcePython
import itkImageSourceCommonPython
import itkVectorImagePython
import itkVariableLengthVectorPython
import itkImageToImageFilterCommonPython

def itkThresholdMaximumConnectedComponentsImageFilterIUS3_New():
  return itkThresholdMaximumConnectedComponentsImageFilterIUS3.New()


def itkThresholdMaximumConnectedComponentsImageFilterIUS2_New():
  return itkThresholdMaximumConnectedComponentsImageFilterIUS2.New()


def itkThresholdMaximumConnectedComponentsImageFilterIUC3_New():
  return itkThresholdMaximumConnectedComponentsImageFilterIUC3.New()


def itkThresholdMaximumConnectedComponentsImageFilterIUC2_New():
  return itkThresholdMaximumConnectedComponentsImageFilterIUC2.New()


def itkThresholdMaximumConnectedComponentsImageFilterISS3_New():
  return itkThresholdMaximumConnectedComponentsImageFilterISS3.New()


def itkThresholdMaximumConnectedComponentsImageFilterISS2_New():
  return itkThresholdMaximumConnectedComponentsImageFilterISS2.New()

class itkThresholdMaximumConnectedComponentsImageFilterISS2(itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    """


    Finds the threshold value of an image based on maximizing the number
    of objects in the image that are larger than a given minimal size.

    This method is based on Topological Stable State Thresholding to
    calculate the threshold set point. This method is particularly
    effective when there are a large number of objects in a microscopy
    image. Compiling in Debug mode and enable the debug flag for this
    filter to print debug information to see how the filter focuses in on
    a threshold value. Please see the Insight Journal's MICCAI 2005
    workshop for a complete description. References are below. Parameters
    The MinimumObjectSizeInPixels parameter is controlled through the
    class Get/SetMinimumObjectSizeInPixels() method. Similar to the
    standard itk::BinaryThresholdImageFilter the Get/SetInside and
    Get/SetOutside values of the threshold can be set. The
    GetNumberOfObjects() and GetThresholdValue() methods return the number
    of objects above the minimum pixel size and the calculated threshold
    value. Automatic Thresholding in ITK There are multiple methods to
    automatically calculate the threshold intensity value of an image. As
    of version 4.0, ITK has a Thresholding ( ITKThresholding ) module
    which contains numerous automatic thresholding methods.implements two
    of these. Topological Stable State Thresholding works well on images
    with a large number of objects to be counted. References: 1) Urish KL,
    August J, Huard J. "Unsupervised segmentation for myofiber counting
    in immunoflourescent images". Insight Journal. ISC /NA-MIC/MICCAI
    Workshop on Open-Source Software (2005) Dspace
    handle:https://hdl.handle.net/1926/48 2) Pikaz A, Averbuch, A.
    "Digital image thresholding based on topological stable-state".
    Pattern Recognition, 29(5): 829-843, 1996.

    Questions: email Ken Urish at ken.urish(at)gmail.com Please cc the itk
    list serve for archival purposes.

    C++ includes: itkThresholdMaximumConnectedComponentsImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__():
        """__New_orig__() -> itkThresholdMaximumConnectedComponentsImageFilterISS2_Pointer"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self):
        """Clone(itkThresholdMaximumConnectedComponentsImageFilterISS2 self) -> itkThresholdMaximumConnectedComponentsImageFilterISS2_Pointer"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS2_Clone(self)

    PixelTypeComparable = _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS2_PixelTypeComparable

    def SetMinimumObjectSizeInPixels(self, _arg):
        """
        SetMinimumObjectSizeInPixels(itkThresholdMaximumConnectedComponentsImageFilterISS2 self, unsigned int const _arg)

        Set
        the minimum pixel area used to count objects on the image. Thus, only
        objects that have a pixel area greater than the minimum pixel area
        will be counted as an object in the optimization portion of this
        filter. Essentially, it eliminates noise from being counted as an
        object. The default value is zero. 
        """
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS2_SetMinimumObjectSizeInPixels(self, _arg)


    def GetMinimumObjectSizeInPixels(self):
        """GetMinimumObjectSizeInPixels(itkThresholdMaximumConnectedComponentsImageFilterISS2 self) -> unsigned int"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS2_GetMinimumObjectSizeInPixels(self)


    def SetInsideValue(self, _arg):
        """
        SetInsideValue(itkThresholdMaximumConnectedComponentsImageFilterISS2 self, short const _arg)

        The following
        Set/Get methods are for the binary threshold function. This class
        automatically calculates the lower threshold boundary. The upper
        threshold boundary, inside value, and outside value can be defined by
        the user, however the standard values are used as default if not set
        by the user. The default value of the: Inside value is the maximum
        pixel type intensity. Outside value is the minimum pixel type
        intensity. Upper threshold boundary is the maximum pixel type
        intensity. 
        """
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS2_SetInsideValue(self, _arg)


    def SetOutsideValue(self, _arg):
        """SetOutsideValue(itkThresholdMaximumConnectedComponentsImageFilterISS2 self, short const _arg)"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS2_SetOutsideValue(self, _arg)


    def SetUpperBoundary(self, _arg):
        """SetUpperBoundary(itkThresholdMaximumConnectedComponentsImageFilterISS2 self, short const _arg)"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS2_SetUpperBoundary(self, _arg)


    def GetInsideValue(self):
        """GetInsideValue(itkThresholdMaximumConnectedComponentsImageFilterISS2 self) -> short"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS2_GetInsideValue(self)


    def GetOutsideValue(self):
        """GetOutsideValue(itkThresholdMaximumConnectedComponentsImageFilterISS2 self) -> short"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS2_GetOutsideValue(self)


    def GetUpperBoundary(self):
        """GetUpperBoundary(itkThresholdMaximumConnectedComponentsImageFilterISS2 self) -> short"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS2_GetUpperBoundary(self)


    def GetNumberOfObjects(self):
        """
        GetNumberOfObjects(itkThresholdMaximumConnectedComponentsImageFilterISS2 self) -> unsigned long

        Returns the
        number of objects in the image. This information is only valid after
        the filter has executed. Useful if your counting something 
        """
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS2_GetNumberOfObjects(self)


    def GetThresholdValue(self):
        """
        GetThresholdValue(itkThresholdMaximumConnectedComponentsImageFilterISS2 self) -> short

        Returns the
        automatic threshold setpoint. This information is only valid after the
        filter has executed. 
        """
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS2_GetThresholdValue(self)

    __swig_destroy__ = _itkThresholdMaximumConnectedComponentsImageFilterPython.delete_itkThresholdMaximumConnectedComponentsImageFilterISS2

    def cast(obj):
        """cast(itkLightObject obj) -> itkThresholdMaximumConnectedComponentsImageFilterISS2"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS2_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkThresholdMaximumConnectedComponentsImageFilterISS2

        Create a new object of the class itkThresholdMaximumConnectedComponentsImageFilterISS2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkThresholdMaximumConnectedComponentsImageFilterISS2.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkThresholdMaximumConnectedComponentsImageFilterISS2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkThresholdMaximumConnectedComponentsImageFilterISS2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkThresholdMaximumConnectedComponentsImageFilterISS2.Clone = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS2_Clone, None, itkThresholdMaximumConnectedComponentsImageFilterISS2)
itkThresholdMaximumConnectedComponentsImageFilterISS2.SetMinimumObjectSizeInPixels = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS2_SetMinimumObjectSizeInPixels, None, itkThresholdMaximumConnectedComponentsImageFilterISS2)
itkThresholdMaximumConnectedComponentsImageFilterISS2.GetMinimumObjectSizeInPixels = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS2_GetMinimumObjectSizeInPixels, None, itkThresholdMaximumConnectedComponentsImageFilterISS2)
itkThresholdMaximumConnectedComponentsImageFilterISS2.SetInsideValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS2_SetInsideValue, None, itkThresholdMaximumConnectedComponentsImageFilterISS2)
itkThresholdMaximumConnectedComponentsImageFilterISS2.SetOutsideValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS2_SetOutsideValue, None, itkThresholdMaximumConnectedComponentsImageFilterISS2)
itkThresholdMaximumConnectedComponentsImageFilterISS2.SetUpperBoundary = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS2_SetUpperBoundary, None, itkThresholdMaximumConnectedComponentsImageFilterISS2)
itkThresholdMaximumConnectedComponentsImageFilterISS2.GetInsideValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS2_GetInsideValue, None, itkThresholdMaximumConnectedComponentsImageFilterISS2)
itkThresholdMaximumConnectedComponentsImageFilterISS2.GetOutsideValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS2_GetOutsideValue, None, itkThresholdMaximumConnectedComponentsImageFilterISS2)
itkThresholdMaximumConnectedComponentsImageFilterISS2.GetUpperBoundary = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS2_GetUpperBoundary, None, itkThresholdMaximumConnectedComponentsImageFilterISS2)
itkThresholdMaximumConnectedComponentsImageFilterISS2.GetNumberOfObjects = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS2_GetNumberOfObjects, None, itkThresholdMaximumConnectedComponentsImageFilterISS2)
itkThresholdMaximumConnectedComponentsImageFilterISS2.GetThresholdValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS2_GetThresholdValue, None, itkThresholdMaximumConnectedComponentsImageFilterISS2)
itkThresholdMaximumConnectedComponentsImageFilterISS2_swigregister = _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS2_swigregister
itkThresholdMaximumConnectedComponentsImageFilterISS2_swigregister(itkThresholdMaximumConnectedComponentsImageFilterISS2)

def itkThresholdMaximumConnectedComponentsImageFilterISS2___New_orig__():
    """itkThresholdMaximumConnectedComponentsImageFilterISS2___New_orig__() -> itkThresholdMaximumConnectedComponentsImageFilterISS2_Pointer"""
    return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS2___New_orig__()

def itkThresholdMaximumConnectedComponentsImageFilterISS2_cast(obj):
    """itkThresholdMaximumConnectedComponentsImageFilterISS2_cast(itkLightObject obj) -> itkThresholdMaximumConnectedComponentsImageFilterISS2"""
    return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS2_cast(obj)

class itkThresholdMaximumConnectedComponentsImageFilterISS3(itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    """


    Finds the threshold value of an image based on maximizing the number
    of objects in the image that are larger than a given minimal size.

    This method is based on Topological Stable State Thresholding to
    calculate the threshold set point. This method is particularly
    effective when there are a large number of objects in a microscopy
    image. Compiling in Debug mode and enable the debug flag for this
    filter to print debug information to see how the filter focuses in on
    a threshold value. Please see the Insight Journal's MICCAI 2005
    workshop for a complete description. References are below. Parameters
    The MinimumObjectSizeInPixels parameter is controlled through the
    class Get/SetMinimumObjectSizeInPixels() method. Similar to the
    standard itk::BinaryThresholdImageFilter the Get/SetInside and
    Get/SetOutside values of the threshold can be set. The
    GetNumberOfObjects() and GetThresholdValue() methods return the number
    of objects above the minimum pixel size and the calculated threshold
    value. Automatic Thresholding in ITK There are multiple methods to
    automatically calculate the threshold intensity value of an image. As
    of version 4.0, ITK has a Thresholding ( ITKThresholding ) module
    which contains numerous automatic thresholding methods.implements two
    of these. Topological Stable State Thresholding works well on images
    with a large number of objects to be counted. References: 1) Urish KL,
    August J, Huard J. "Unsupervised segmentation for myofiber counting
    in immunoflourescent images". Insight Journal. ISC /NA-MIC/MICCAI
    Workshop on Open-Source Software (2005) Dspace
    handle:https://hdl.handle.net/1926/48 2) Pikaz A, Averbuch, A.
    "Digital image thresholding based on topological stable-state".
    Pattern Recognition, 29(5): 829-843, 1996.

    Questions: email Ken Urish at ken.urish(at)gmail.com Please cc the itk
    list serve for archival purposes.

    C++ includes: itkThresholdMaximumConnectedComponentsImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__():
        """__New_orig__() -> itkThresholdMaximumConnectedComponentsImageFilterISS3_Pointer"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self):
        """Clone(itkThresholdMaximumConnectedComponentsImageFilterISS3 self) -> itkThresholdMaximumConnectedComponentsImageFilterISS3_Pointer"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS3_Clone(self)

    PixelTypeComparable = _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS3_PixelTypeComparable

    def SetMinimumObjectSizeInPixels(self, _arg):
        """
        SetMinimumObjectSizeInPixels(itkThresholdMaximumConnectedComponentsImageFilterISS3 self, unsigned int const _arg)

        Set
        the minimum pixel area used to count objects on the image. Thus, only
        objects that have a pixel area greater than the minimum pixel area
        will be counted as an object in the optimization portion of this
        filter. Essentially, it eliminates noise from being counted as an
        object. The default value is zero. 
        """
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS3_SetMinimumObjectSizeInPixels(self, _arg)


    def GetMinimumObjectSizeInPixels(self):
        """GetMinimumObjectSizeInPixels(itkThresholdMaximumConnectedComponentsImageFilterISS3 self) -> unsigned int"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS3_GetMinimumObjectSizeInPixels(self)


    def SetInsideValue(self, _arg):
        """
        SetInsideValue(itkThresholdMaximumConnectedComponentsImageFilterISS3 self, short const _arg)

        The following
        Set/Get methods are for the binary threshold function. This class
        automatically calculates the lower threshold boundary. The upper
        threshold boundary, inside value, and outside value can be defined by
        the user, however the standard values are used as default if not set
        by the user. The default value of the: Inside value is the maximum
        pixel type intensity. Outside value is the minimum pixel type
        intensity. Upper threshold boundary is the maximum pixel type
        intensity. 
        """
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS3_SetInsideValue(self, _arg)


    def SetOutsideValue(self, _arg):
        """SetOutsideValue(itkThresholdMaximumConnectedComponentsImageFilterISS3 self, short const _arg)"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS3_SetOutsideValue(self, _arg)


    def SetUpperBoundary(self, _arg):
        """SetUpperBoundary(itkThresholdMaximumConnectedComponentsImageFilterISS3 self, short const _arg)"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS3_SetUpperBoundary(self, _arg)


    def GetInsideValue(self):
        """GetInsideValue(itkThresholdMaximumConnectedComponentsImageFilterISS3 self) -> short"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS3_GetInsideValue(self)


    def GetOutsideValue(self):
        """GetOutsideValue(itkThresholdMaximumConnectedComponentsImageFilterISS3 self) -> short"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS3_GetOutsideValue(self)


    def GetUpperBoundary(self):
        """GetUpperBoundary(itkThresholdMaximumConnectedComponentsImageFilterISS3 self) -> short"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS3_GetUpperBoundary(self)


    def GetNumberOfObjects(self):
        """
        GetNumberOfObjects(itkThresholdMaximumConnectedComponentsImageFilterISS3 self) -> unsigned long

        Returns the
        number of objects in the image. This information is only valid after
        the filter has executed. Useful if your counting something 
        """
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS3_GetNumberOfObjects(self)


    def GetThresholdValue(self):
        """
        GetThresholdValue(itkThresholdMaximumConnectedComponentsImageFilterISS3 self) -> short

        Returns the
        automatic threshold setpoint. This information is only valid after the
        filter has executed. 
        """
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS3_GetThresholdValue(self)

    __swig_destroy__ = _itkThresholdMaximumConnectedComponentsImageFilterPython.delete_itkThresholdMaximumConnectedComponentsImageFilterISS3

    def cast(obj):
        """cast(itkLightObject obj) -> itkThresholdMaximumConnectedComponentsImageFilterISS3"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS3_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkThresholdMaximumConnectedComponentsImageFilterISS3

        Create a new object of the class itkThresholdMaximumConnectedComponentsImageFilterISS3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkThresholdMaximumConnectedComponentsImageFilterISS3.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkThresholdMaximumConnectedComponentsImageFilterISS3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkThresholdMaximumConnectedComponentsImageFilterISS3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkThresholdMaximumConnectedComponentsImageFilterISS3.Clone = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS3_Clone, None, itkThresholdMaximumConnectedComponentsImageFilterISS3)
itkThresholdMaximumConnectedComponentsImageFilterISS3.SetMinimumObjectSizeInPixels = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS3_SetMinimumObjectSizeInPixels, None, itkThresholdMaximumConnectedComponentsImageFilterISS3)
itkThresholdMaximumConnectedComponentsImageFilterISS3.GetMinimumObjectSizeInPixels = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS3_GetMinimumObjectSizeInPixels, None, itkThresholdMaximumConnectedComponentsImageFilterISS3)
itkThresholdMaximumConnectedComponentsImageFilterISS3.SetInsideValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS3_SetInsideValue, None, itkThresholdMaximumConnectedComponentsImageFilterISS3)
itkThresholdMaximumConnectedComponentsImageFilterISS3.SetOutsideValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS3_SetOutsideValue, None, itkThresholdMaximumConnectedComponentsImageFilterISS3)
itkThresholdMaximumConnectedComponentsImageFilterISS3.SetUpperBoundary = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS3_SetUpperBoundary, None, itkThresholdMaximumConnectedComponentsImageFilterISS3)
itkThresholdMaximumConnectedComponentsImageFilterISS3.GetInsideValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS3_GetInsideValue, None, itkThresholdMaximumConnectedComponentsImageFilterISS3)
itkThresholdMaximumConnectedComponentsImageFilterISS3.GetOutsideValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS3_GetOutsideValue, None, itkThresholdMaximumConnectedComponentsImageFilterISS3)
itkThresholdMaximumConnectedComponentsImageFilterISS3.GetUpperBoundary = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS3_GetUpperBoundary, None, itkThresholdMaximumConnectedComponentsImageFilterISS3)
itkThresholdMaximumConnectedComponentsImageFilterISS3.GetNumberOfObjects = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS3_GetNumberOfObjects, None, itkThresholdMaximumConnectedComponentsImageFilterISS3)
itkThresholdMaximumConnectedComponentsImageFilterISS3.GetThresholdValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS3_GetThresholdValue, None, itkThresholdMaximumConnectedComponentsImageFilterISS3)
itkThresholdMaximumConnectedComponentsImageFilterISS3_swigregister = _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS3_swigregister
itkThresholdMaximumConnectedComponentsImageFilterISS3_swigregister(itkThresholdMaximumConnectedComponentsImageFilterISS3)

def itkThresholdMaximumConnectedComponentsImageFilterISS3___New_orig__():
    """itkThresholdMaximumConnectedComponentsImageFilterISS3___New_orig__() -> itkThresholdMaximumConnectedComponentsImageFilterISS3_Pointer"""
    return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS3___New_orig__()

def itkThresholdMaximumConnectedComponentsImageFilterISS3_cast(obj):
    """itkThresholdMaximumConnectedComponentsImageFilterISS3_cast(itkLightObject obj) -> itkThresholdMaximumConnectedComponentsImageFilterISS3"""
    return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterISS3_cast(obj)

class itkThresholdMaximumConnectedComponentsImageFilterIUC2(itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    """


    Finds the threshold value of an image based on maximizing the number
    of objects in the image that are larger than a given minimal size.

    This method is based on Topological Stable State Thresholding to
    calculate the threshold set point. This method is particularly
    effective when there are a large number of objects in a microscopy
    image. Compiling in Debug mode and enable the debug flag for this
    filter to print debug information to see how the filter focuses in on
    a threshold value. Please see the Insight Journal's MICCAI 2005
    workshop for a complete description. References are below. Parameters
    The MinimumObjectSizeInPixels parameter is controlled through the
    class Get/SetMinimumObjectSizeInPixels() method. Similar to the
    standard itk::BinaryThresholdImageFilter the Get/SetInside and
    Get/SetOutside values of the threshold can be set. The
    GetNumberOfObjects() and GetThresholdValue() methods return the number
    of objects above the minimum pixel size and the calculated threshold
    value. Automatic Thresholding in ITK There are multiple methods to
    automatically calculate the threshold intensity value of an image. As
    of version 4.0, ITK has a Thresholding ( ITKThresholding ) module
    which contains numerous automatic thresholding methods.implements two
    of these. Topological Stable State Thresholding works well on images
    with a large number of objects to be counted. References: 1) Urish KL,
    August J, Huard J. "Unsupervised segmentation for myofiber counting
    in immunoflourescent images". Insight Journal. ISC /NA-MIC/MICCAI
    Workshop on Open-Source Software (2005) Dspace
    handle:https://hdl.handle.net/1926/48 2) Pikaz A, Averbuch, A.
    "Digital image thresholding based on topological stable-state".
    Pattern Recognition, 29(5): 829-843, 1996.

    Questions: email Ken Urish at ken.urish(at)gmail.com Please cc the itk
    list serve for archival purposes.

    C++ includes: itkThresholdMaximumConnectedComponentsImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__():
        """__New_orig__() -> itkThresholdMaximumConnectedComponentsImageFilterIUC2_Pointer"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self):
        """Clone(itkThresholdMaximumConnectedComponentsImageFilterIUC2 self) -> itkThresholdMaximumConnectedComponentsImageFilterIUC2_Pointer"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC2_Clone(self)

    PixelTypeComparable = _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC2_PixelTypeComparable

    def SetMinimumObjectSizeInPixels(self, _arg):
        """
        SetMinimumObjectSizeInPixels(itkThresholdMaximumConnectedComponentsImageFilterIUC2 self, unsigned int const _arg)

        Set
        the minimum pixel area used to count objects on the image. Thus, only
        objects that have a pixel area greater than the minimum pixel area
        will be counted as an object in the optimization portion of this
        filter. Essentially, it eliminates noise from being counted as an
        object. The default value is zero. 
        """
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC2_SetMinimumObjectSizeInPixels(self, _arg)


    def GetMinimumObjectSizeInPixels(self):
        """GetMinimumObjectSizeInPixels(itkThresholdMaximumConnectedComponentsImageFilterIUC2 self) -> unsigned int"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC2_GetMinimumObjectSizeInPixels(self)


    def SetInsideValue(self, _arg):
        """
        SetInsideValue(itkThresholdMaximumConnectedComponentsImageFilterIUC2 self, unsigned char const _arg)

        The following
        Set/Get methods are for the binary threshold function. This class
        automatically calculates the lower threshold boundary. The upper
        threshold boundary, inside value, and outside value can be defined by
        the user, however the standard values are used as default if not set
        by the user. The default value of the: Inside value is the maximum
        pixel type intensity. Outside value is the minimum pixel type
        intensity. Upper threshold boundary is the maximum pixel type
        intensity. 
        """
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC2_SetInsideValue(self, _arg)


    def SetOutsideValue(self, _arg):
        """SetOutsideValue(itkThresholdMaximumConnectedComponentsImageFilterIUC2 self, unsigned char const _arg)"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC2_SetOutsideValue(self, _arg)


    def SetUpperBoundary(self, _arg):
        """SetUpperBoundary(itkThresholdMaximumConnectedComponentsImageFilterIUC2 self, unsigned char const _arg)"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC2_SetUpperBoundary(self, _arg)


    def GetInsideValue(self):
        """GetInsideValue(itkThresholdMaximumConnectedComponentsImageFilterIUC2 self) -> unsigned char"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC2_GetInsideValue(self)


    def GetOutsideValue(self):
        """GetOutsideValue(itkThresholdMaximumConnectedComponentsImageFilterIUC2 self) -> unsigned char"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC2_GetOutsideValue(self)


    def GetUpperBoundary(self):
        """GetUpperBoundary(itkThresholdMaximumConnectedComponentsImageFilterIUC2 self) -> unsigned char"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC2_GetUpperBoundary(self)


    def GetNumberOfObjects(self):
        """
        GetNumberOfObjects(itkThresholdMaximumConnectedComponentsImageFilterIUC2 self) -> unsigned long

        Returns the
        number of objects in the image. This information is only valid after
        the filter has executed. Useful if your counting something 
        """
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC2_GetNumberOfObjects(self)


    def GetThresholdValue(self):
        """
        GetThresholdValue(itkThresholdMaximumConnectedComponentsImageFilterIUC2 self) -> unsigned char

        Returns the
        automatic threshold setpoint. This information is only valid after the
        filter has executed. 
        """
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC2_GetThresholdValue(self)

    __swig_destroy__ = _itkThresholdMaximumConnectedComponentsImageFilterPython.delete_itkThresholdMaximumConnectedComponentsImageFilterIUC2

    def cast(obj):
        """cast(itkLightObject obj) -> itkThresholdMaximumConnectedComponentsImageFilterIUC2"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC2_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkThresholdMaximumConnectedComponentsImageFilterIUC2

        Create a new object of the class itkThresholdMaximumConnectedComponentsImageFilterIUC2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkThresholdMaximumConnectedComponentsImageFilterIUC2.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkThresholdMaximumConnectedComponentsImageFilterIUC2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkThresholdMaximumConnectedComponentsImageFilterIUC2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkThresholdMaximumConnectedComponentsImageFilterIUC2.Clone = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC2_Clone, None, itkThresholdMaximumConnectedComponentsImageFilterIUC2)
itkThresholdMaximumConnectedComponentsImageFilterIUC2.SetMinimumObjectSizeInPixels = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC2_SetMinimumObjectSizeInPixels, None, itkThresholdMaximumConnectedComponentsImageFilterIUC2)
itkThresholdMaximumConnectedComponentsImageFilterIUC2.GetMinimumObjectSizeInPixels = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC2_GetMinimumObjectSizeInPixels, None, itkThresholdMaximumConnectedComponentsImageFilterIUC2)
itkThresholdMaximumConnectedComponentsImageFilterIUC2.SetInsideValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC2_SetInsideValue, None, itkThresholdMaximumConnectedComponentsImageFilterIUC2)
itkThresholdMaximumConnectedComponentsImageFilterIUC2.SetOutsideValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC2_SetOutsideValue, None, itkThresholdMaximumConnectedComponentsImageFilterIUC2)
itkThresholdMaximumConnectedComponentsImageFilterIUC2.SetUpperBoundary = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC2_SetUpperBoundary, None, itkThresholdMaximumConnectedComponentsImageFilterIUC2)
itkThresholdMaximumConnectedComponentsImageFilterIUC2.GetInsideValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC2_GetInsideValue, None, itkThresholdMaximumConnectedComponentsImageFilterIUC2)
itkThresholdMaximumConnectedComponentsImageFilterIUC2.GetOutsideValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC2_GetOutsideValue, None, itkThresholdMaximumConnectedComponentsImageFilterIUC2)
itkThresholdMaximumConnectedComponentsImageFilterIUC2.GetUpperBoundary = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC2_GetUpperBoundary, None, itkThresholdMaximumConnectedComponentsImageFilterIUC2)
itkThresholdMaximumConnectedComponentsImageFilterIUC2.GetNumberOfObjects = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC2_GetNumberOfObjects, None, itkThresholdMaximumConnectedComponentsImageFilterIUC2)
itkThresholdMaximumConnectedComponentsImageFilterIUC2.GetThresholdValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC2_GetThresholdValue, None, itkThresholdMaximumConnectedComponentsImageFilterIUC2)
itkThresholdMaximumConnectedComponentsImageFilterIUC2_swigregister = _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC2_swigregister
itkThresholdMaximumConnectedComponentsImageFilterIUC2_swigregister(itkThresholdMaximumConnectedComponentsImageFilterIUC2)

def itkThresholdMaximumConnectedComponentsImageFilterIUC2___New_orig__():
    """itkThresholdMaximumConnectedComponentsImageFilterIUC2___New_orig__() -> itkThresholdMaximumConnectedComponentsImageFilterIUC2_Pointer"""
    return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC2___New_orig__()

def itkThresholdMaximumConnectedComponentsImageFilterIUC2_cast(obj):
    """itkThresholdMaximumConnectedComponentsImageFilterIUC2_cast(itkLightObject obj) -> itkThresholdMaximumConnectedComponentsImageFilterIUC2"""
    return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC2_cast(obj)

class itkThresholdMaximumConnectedComponentsImageFilterIUC3(itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    """


    Finds the threshold value of an image based on maximizing the number
    of objects in the image that are larger than a given minimal size.

    This method is based on Topological Stable State Thresholding to
    calculate the threshold set point. This method is particularly
    effective when there are a large number of objects in a microscopy
    image. Compiling in Debug mode and enable the debug flag for this
    filter to print debug information to see how the filter focuses in on
    a threshold value. Please see the Insight Journal's MICCAI 2005
    workshop for a complete description. References are below. Parameters
    The MinimumObjectSizeInPixels parameter is controlled through the
    class Get/SetMinimumObjectSizeInPixels() method. Similar to the
    standard itk::BinaryThresholdImageFilter the Get/SetInside and
    Get/SetOutside values of the threshold can be set. The
    GetNumberOfObjects() and GetThresholdValue() methods return the number
    of objects above the minimum pixel size and the calculated threshold
    value. Automatic Thresholding in ITK There are multiple methods to
    automatically calculate the threshold intensity value of an image. As
    of version 4.0, ITK has a Thresholding ( ITKThresholding ) module
    which contains numerous automatic thresholding methods.implements two
    of these. Topological Stable State Thresholding works well on images
    with a large number of objects to be counted. References: 1) Urish KL,
    August J, Huard J. "Unsupervised segmentation for myofiber counting
    in immunoflourescent images". Insight Journal. ISC /NA-MIC/MICCAI
    Workshop on Open-Source Software (2005) Dspace
    handle:https://hdl.handle.net/1926/48 2) Pikaz A, Averbuch, A.
    "Digital image thresholding based on topological stable-state".
    Pattern Recognition, 29(5): 829-843, 1996.

    Questions: email Ken Urish at ken.urish(at)gmail.com Please cc the itk
    list serve for archival purposes.

    C++ includes: itkThresholdMaximumConnectedComponentsImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__():
        """__New_orig__() -> itkThresholdMaximumConnectedComponentsImageFilterIUC3_Pointer"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self):
        """Clone(itkThresholdMaximumConnectedComponentsImageFilterIUC3 self) -> itkThresholdMaximumConnectedComponentsImageFilterIUC3_Pointer"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC3_Clone(self)

    PixelTypeComparable = _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC3_PixelTypeComparable

    def SetMinimumObjectSizeInPixels(self, _arg):
        """
        SetMinimumObjectSizeInPixels(itkThresholdMaximumConnectedComponentsImageFilterIUC3 self, unsigned int const _arg)

        Set
        the minimum pixel area used to count objects on the image. Thus, only
        objects that have a pixel area greater than the minimum pixel area
        will be counted as an object in the optimization portion of this
        filter. Essentially, it eliminates noise from being counted as an
        object. The default value is zero. 
        """
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC3_SetMinimumObjectSizeInPixels(self, _arg)


    def GetMinimumObjectSizeInPixels(self):
        """GetMinimumObjectSizeInPixels(itkThresholdMaximumConnectedComponentsImageFilterIUC3 self) -> unsigned int"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC3_GetMinimumObjectSizeInPixels(self)


    def SetInsideValue(self, _arg):
        """
        SetInsideValue(itkThresholdMaximumConnectedComponentsImageFilterIUC3 self, unsigned char const _arg)

        The following
        Set/Get methods are for the binary threshold function. This class
        automatically calculates the lower threshold boundary. The upper
        threshold boundary, inside value, and outside value can be defined by
        the user, however the standard values are used as default if not set
        by the user. The default value of the: Inside value is the maximum
        pixel type intensity. Outside value is the minimum pixel type
        intensity. Upper threshold boundary is the maximum pixel type
        intensity. 
        """
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC3_SetInsideValue(self, _arg)


    def SetOutsideValue(self, _arg):
        """SetOutsideValue(itkThresholdMaximumConnectedComponentsImageFilterIUC3 self, unsigned char const _arg)"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC3_SetOutsideValue(self, _arg)


    def SetUpperBoundary(self, _arg):
        """SetUpperBoundary(itkThresholdMaximumConnectedComponentsImageFilterIUC3 self, unsigned char const _arg)"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC3_SetUpperBoundary(self, _arg)


    def GetInsideValue(self):
        """GetInsideValue(itkThresholdMaximumConnectedComponentsImageFilterIUC3 self) -> unsigned char"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC3_GetInsideValue(self)


    def GetOutsideValue(self):
        """GetOutsideValue(itkThresholdMaximumConnectedComponentsImageFilterIUC3 self) -> unsigned char"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC3_GetOutsideValue(self)


    def GetUpperBoundary(self):
        """GetUpperBoundary(itkThresholdMaximumConnectedComponentsImageFilterIUC3 self) -> unsigned char"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC3_GetUpperBoundary(self)


    def GetNumberOfObjects(self):
        """
        GetNumberOfObjects(itkThresholdMaximumConnectedComponentsImageFilterIUC3 self) -> unsigned long

        Returns the
        number of objects in the image. This information is only valid after
        the filter has executed. Useful if your counting something 
        """
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC3_GetNumberOfObjects(self)


    def GetThresholdValue(self):
        """
        GetThresholdValue(itkThresholdMaximumConnectedComponentsImageFilterIUC3 self) -> unsigned char

        Returns the
        automatic threshold setpoint. This information is only valid after the
        filter has executed. 
        """
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC3_GetThresholdValue(self)

    __swig_destroy__ = _itkThresholdMaximumConnectedComponentsImageFilterPython.delete_itkThresholdMaximumConnectedComponentsImageFilterIUC3

    def cast(obj):
        """cast(itkLightObject obj) -> itkThresholdMaximumConnectedComponentsImageFilterIUC3"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC3_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkThresholdMaximumConnectedComponentsImageFilterIUC3

        Create a new object of the class itkThresholdMaximumConnectedComponentsImageFilterIUC3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkThresholdMaximumConnectedComponentsImageFilterIUC3.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkThresholdMaximumConnectedComponentsImageFilterIUC3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkThresholdMaximumConnectedComponentsImageFilterIUC3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkThresholdMaximumConnectedComponentsImageFilterIUC3.Clone = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC3_Clone, None, itkThresholdMaximumConnectedComponentsImageFilterIUC3)
itkThresholdMaximumConnectedComponentsImageFilterIUC3.SetMinimumObjectSizeInPixels = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC3_SetMinimumObjectSizeInPixels, None, itkThresholdMaximumConnectedComponentsImageFilterIUC3)
itkThresholdMaximumConnectedComponentsImageFilterIUC3.GetMinimumObjectSizeInPixels = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC3_GetMinimumObjectSizeInPixels, None, itkThresholdMaximumConnectedComponentsImageFilterIUC3)
itkThresholdMaximumConnectedComponentsImageFilterIUC3.SetInsideValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC3_SetInsideValue, None, itkThresholdMaximumConnectedComponentsImageFilterIUC3)
itkThresholdMaximumConnectedComponentsImageFilterIUC3.SetOutsideValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC3_SetOutsideValue, None, itkThresholdMaximumConnectedComponentsImageFilterIUC3)
itkThresholdMaximumConnectedComponentsImageFilterIUC3.SetUpperBoundary = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC3_SetUpperBoundary, None, itkThresholdMaximumConnectedComponentsImageFilterIUC3)
itkThresholdMaximumConnectedComponentsImageFilterIUC3.GetInsideValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC3_GetInsideValue, None, itkThresholdMaximumConnectedComponentsImageFilterIUC3)
itkThresholdMaximumConnectedComponentsImageFilterIUC3.GetOutsideValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC3_GetOutsideValue, None, itkThresholdMaximumConnectedComponentsImageFilterIUC3)
itkThresholdMaximumConnectedComponentsImageFilterIUC3.GetUpperBoundary = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC3_GetUpperBoundary, None, itkThresholdMaximumConnectedComponentsImageFilterIUC3)
itkThresholdMaximumConnectedComponentsImageFilterIUC3.GetNumberOfObjects = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC3_GetNumberOfObjects, None, itkThresholdMaximumConnectedComponentsImageFilterIUC3)
itkThresholdMaximumConnectedComponentsImageFilterIUC3.GetThresholdValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC3_GetThresholdValue, None, itkThresholdMaximumConnectedComponentsImageFilterIUC3)
itkThresholdMaximumConnectedComponentsImageFilterIUC3_swigregister = _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC3_swigregister
itkThresholdMaximumConnectedComponentsImageFilterIUC3_swigregister(itkThresholdMaximumConnectedComponentsImageFilterIUC3)

def itkThresholdMaximumConnectedComponentsImageFilterIUC3___New_orig__():
    """itkThresholdMaximumConnectedComponentsImageFilterIUC3___New_orig__() -> itkThresholdMaximumConnectedComponentsImageFilterIUC3_Pointer"""
    return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC3___New_orig__()

def itkThresholdMaximumConnectedComponentsImageFilterIUC3_cast(obj):
    """itkThresholdMaximumConnectedComponentsImageFilterIUC3_cast(itkLightObject obj) -> itkThresholdMaximumConnectedComponentsImageFilterIUC3"""
    return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUC3_cast(obj)

class itkThresholdMaximumConnectedComponentsImageFilterIUS2(itkImageToImageFilterAPython.itkImageToImageFilterIUS2IUS2):
    """


    Finds the threshold value of an image based on maximizing the number
    of objects in the image that are larger than a given minimal size.

    This method is based on Topological Stable State Thresholding to
    calculate the threshold set point. This method is particularly
    effective when there are a large number of objects in a microscopy
    image. Compiling in Debug mode and enable the debug flag for this
    filter to print debug information to see how the filter focuses in on
    a threshold value. Please see the Insight Journal's MICCAI 2005
    workshop for a complete description. References are below. Parameters
    The MinimumObjectSizeInPixels parameter is controlled through the
    class Get/SetMinimumObjectSizeInPixels() method. Similar to the
    standard itk::BinaryThresholdImageFilter the Get/SetInside and
    Get/SetOutside values of the threshold can be set. The
    GetNumberOfObjects() and GetThresholdValue() methods return the number
    of objects above the minimum pixel size and the calculated threshold
    value. Automatic Thresholding in ITK There are multiple methods to
    automatically calculate the threshold intensity value of an image. As
    of version 4.0, ITK has a Thresholding ( ITKThresholding ) module
    which contains numerous automatic thresholding methods.implements two
    of these. Topological Stable State Thresholding works well on images
    with a large number of objects to be counted. References: 1) Urish KL,
    August J, Huard J. "Unsupervised segmentation for myofiber counting
    in immunoflourescent images". Insight Journal. ISC /NA-MIC/MICCAI
    Workshop on Open-Source Software (2005) Dspace
    handle:https://hdl.handle.net/1926/48 2) Pikaz A, Averbuch, A.
    "Digital image thresholding based on topological stable-state".
    Pattern Recognition, 29(5): 829-843, 1996.

    Questions: email Ken Urish at ken.urish(at)gmail.com Please cc the itk
    list serve for archival purposes.

    C++ includes: itkThresholdMaximumConnectedComponentsImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__():
        """__New_orig__() -> itkThresholdMaximumConnectedComponentsImageFilterIUS2_Pointer"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self):
        """Clone(itkThresholdMaximumConnectedComponentsImageFilterIUS2 self) -> itkThresholdMaximumConnectedComponentsImageFilterIUS2_Pointer"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS2_Clone(self)

    PixelTypeComparable = _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS2_PixelTypeComparable

    def SetMinimumObjectSizeInPixels(self, _arg):
        """
        SetMinimumObjectSizeInPixels(itkThresholdMaximumConnectedComponentsImageFilterIUS2 self, unsigned int const _arg)

        Set
        the minimum pixel area used to count objects on the image. Thus, only
        objects that have a pixel area greater than the minimum pixel area
        will be counted as an object in the optimization portion of this
        filter. Essentially, it eliminates noise from being counted as an
        object. The default value is zero. 
        """
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS2_SetMinimumObjectSizeInPixels(self, _arg)


    def GetMinimumObjectSizeInPixels(self):
        """GetMinimumObjectSizeInPixels(itkThresholdMaximumConnectedComponentsImageFilterIUS2 self) -> unsigned int"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS2_GetMinimumObjectSizeInPixels(self)


    def SetInsideValue(self, _arg):
        """
        SetInsideValue(itkThresholdMaximumConnectedComponentsImageFilterIUS2 self, unsigned short const _arg)

        The following
        Set/Get methods are for the binary threshold function. This class
        automatically calculates the lower threshold boundary. The upper
        threshold boundary, inside value, and outside value can be defined by
        the user, however the standard values are used as default if not set
        by the user. The default value of the: Inside value is the maximum
        pixel type intensity. Outside value is the minimum pixel type
        intensity. Upper threshold boundary is the maximum pixel type
        intensity. 
        """
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS2_SetInsideValue(self, _arg)


    def SetOutsideValue(self, _arg):
        """SetOutsideValue(itkThresholdMaximumConnectedComponentsImageFilterIUS2 self, unsigned short const _arg)"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS2_SetOutsideValue(self, _arg)


    def SetUpperBoundary(self, _arg):
        """SetUpperBoundary(itkThresholdMaximumConnectedComponentsImageFilterIUS2 self, unsigned short const _arg)"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS2_SetUpperBoundary(self, _arg)


    def GetInsideValue(self):
        """GetInsideValue(itkThresholdMaximumConnectedComponentsImageFilterIUS2 self) -> unsigned short"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS2_GetInsideValue(self)


    def GetOutsideValue(self):
        """GetOutsideValue(itkThresholdMaximumConnectedComponentsImageFilterIUS2 self) -> unsigned short"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS2_GetOutsideValue(self)


    def GetUpperBoundary(self):
        """GetUpperBoundary(itkThresholdMaximumConnectedComponentsImageFilterIUS2 self) -> unsigned short"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS2_GetUpperBoundary(self)


    def GetNumberOfObjects(self):
        """
        GetNumberOfObjects(itkThresholdMaximumConnectedComponentsImageFilterIUS2 self) -> unsigned long

        Returns the
        number of objects in the image. This information is only valid after
        the filter has executed. Useful if your counting something 
        """
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS2_GetNumberOfObjects(self)


    def GetThresholdValue(self):
        """
        GetThresholdValue(itkThresholdMaximumConnectedComponentsImageFilterIUS2 self) -> unsigned short

        Returns the
        automatic threshold setpoint. This information is only valid after the
        filter has executed. 
        """
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS2_GetThresholdValue(self)

    __swig_destroy__ = _itkThresholdMaximumConnectedComponentsImageFilterPython.delete_itkThresholdMaximumConnectedComponentsImageFilterIUS2

    def cast(obj):
        """cast(itkLightObject obj) -> itkThresholdMaximumConnectedComponentsImageFilterIUS2"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS2_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkThresholdMaximumConnectedComponentsImageFilterIUS2

        Create a new object of the class itkThresholdMaximumConnectedComponentsImageFilterIUS2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkThresholdMaximumConnectedComponentsImageFilterIUS2.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkThresholdMaximumConnectedComponentsImageFilterIUS2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkThresholdMaximumConnectedComponentsImageFilterIUS2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkThresholdMaximumConnectedComponentsImageFilterIUS2.Clone = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS2_Clone, None, itkThresholdMaximumConnectedComponentsImageFilterIUS2)
itkThresholdMaximumConnectedComponentsImageFilterIUS2.SetMinimumObjectSizeInPixels = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS2_SetMinimumObjectSizeInPixels, None, itkThresholdMaximumConnectedComponentsImageFilterIUS2)
itkThresholdMaximumConnectedComponentsImageFilterIUS2.GetMinimumObjectSizeInPixels = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS2_GetMinimumObjectSizeInPixels, None, itkThresholdMaximumConnectedComponentsImageFilterIUS2)
itkThresholdMaximumConnectedComponentsImageFilterIUS2.SetInsideValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS2_SetInsideValue, None, itkThresholdMaximumConnectedComponentsImageFilterIUS2)
itkThresholdMaximumConnectedComponentsImageFilterIUS2.SetOutsideValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS2_SetOutsideValue, None, itkThresholdMaximumConnectedComponentsImageFilterIUS2)
itkThresholdMaximumConnectedComponentsImageFilterIUS2.SetUpperBoundary = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS2_SetUpperBoundary, None, itkThresholdMaximumConnectedComponentsImageFilterIUS2)
itkThresholdMaximumConnectedComponentsImageFilterIUS2.GetInsideValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS2_GetInsideValue, None, itkThresholdMaximumConnectedComponentsImageFilterIUS2)
itkThresholdMaximumConnectedComponentsImageFilterIUS2.GetOutsideValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS2_GetOutsideValue, None, itkThresholdMaximumConnectedComponentsImageFilterIUS2)
itkThresholdMaximumConnectedComponentsImageFilterIUS2.GetUpperBoundary = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS2_GetUpperBoundary, None, itkThresholdMaximumConnectedComponentsImageFilterIUS2)
itkThresholdMaximumConnectedComponentsImageFilterIUS2.GetNumberOfObjects = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS2_GetNumberOfObjects, None, itkThresholdMaximumConnectedComponentsImageFilterIUS2)
itkThresholdMaximumConnectedComponentsImageFilterIUS2.GetThresholdValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS2_GetThresholdValue, None, itkThresholdMaximumConnectedComponentsImageFilterIUS2)
itkThresholdMaximumConnectedComponentsImageFilterIUS2_swigregister = _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS2_swigregister
itkThresholdMaximumConnectedComponentsImageFilterIUS2_swigregister(itkThresholdMaximumConnectedComponentsImageFilterIUS2)

def itkThresholdMaximumConnectedComponentsImageFilterIUS2___New_orig__():
    """itkThresholdMaximumConnectedComponentsImageFilterIUS2___New_orig__() -> itkThresholdMaximumConnectedComponentsImageFilterIUS2_Pointer"""
    return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS2___New_orig__()

def itkThresholdMaximumConnectedComponentsImageFilterIUS2_cast(obj):
    """itkThresholdMaximumConnectedComponentsImageFilterIUS2_cast(itkLightObject obj) -> itkThresholdMaximumConnectedComponentsImageFilterIUS2"""
    return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS2_cast(obj)

class itkThresholdMaximumConnectedComponentsImageFilterIUS3(itkImageToImageFilterAPython.itkImageToImageFilterIUS3IUS3):
    """


    Finds the threshold value of an image based on maximizing the number
    of objects in the image that are larger than a given minimal size.

    This method is based on Topological Stable State Thresholding to
    calculate the threshold set point. This method is particularly
    effective when there are a large number of objects in a microscopy
    image. Compiling in Debug mode and enable the debug flag for this
    filter to print debug information to see how the filter focuses in on
    a threshold value. Please see the Insight Journal's MICCAI 2005
    workshop for a complete description. References are below. Parameters
    The MinimumObjectSizeInPixels parameter is controlled through the
    class Get/SetMinimumObjectSizeInPixels() method. Similar to the
    standard itk::BinaryThresholdImageFilter the Get/SetInside and
    Get/SetOutside values of the threshold can be set. The
    GetNumberOfObjects() and GetThresholdValue() methods return the number
    of objects above the minimum pixel size and the calculated threshold
    value. Automatic Thresholding in ITK There are multiple methods to
    automatically calculate the threshold intensity value of an image. As
    of version 4.0, ITK has a Thresholding ( ITKThresholding ) module
    which contains numerous automatic thresholding methods.implements two
    of these. Topological Stable State Thresholding works well on images
    with a large number of objects to be counted. References: 1) Urish KL,
    August J, Huard J. "Unsupervised segmentation for myofiber counting
    in immunoflourescent images". Insight Journal. ISC /NA-MIC/MICCAI
    Workshop on Open-Source Software (2005) Dspace
    handle:https://hdl.handle.net/1926/48 2) Pikaz A, Averbuch, A.
    "Digital image thresholding based on topological stable-state".
    Pattern Recognition, 29(5): 829-843, 1996.

    Questions: email Ken Urish at ken.urish(at)gmail.com Please cc the itk
    list serve for archival purposes.

    C++ includes: itkThresholdMaximumConnectedComponentsImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__():
        """__New_orig__() -> itkThresholdMaximumConnectedComponentsImageFilterIUS3_Pointer"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self):
        """Clone(itkThresholdMaximumConnectedComponentsImageFilterIUS3 self) -> itkThresholdMaximumConnectedComponentsImageFilterIUS3_Pointer"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS3_Clone(self)

    PixelTypeComparable = _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS3_PixelTypeComparable

    def SetMinimumObjectSizeInPixels(self, _arg):
        """
        SetMinimumObjectSizeInPixels(itkThresholdMaximumConnectedComponentsImageFilterIUS3 self, unsigned int const _arg)

        Set
        the minimum pixel area used to count objects on the image. Thus, only
        objects that have a pixel area greater than the minimum pixel area
        will be counted as an object in the optimization portion of this
        filter. Essentially, it eliminates noise from being counted as an
        object. The default value is zero. 
        """
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS3_SetMinimumObjectSizeInPixels(self, _arg)


    def GetMinimumObjectSizeInPixels(self):
        """GetMinimumObjectSizeInPixels(itkThresholdMaximumConnectedComponentsImageFilterIUS3 self) -> unsigned int"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS3_GetMinimumObjectSizeInPixels(self)


    def SetInsideValue(self, _arg):
        """
        SetInsideValue(itkThresholdMaximumConnectedComponentsImageFilterIUS3 self, unsigned short const _arg)

        The following
        Set/Get methods are for the binary threshold function. This class
        automatically calculates the lower threshold boundary. The upper
        threshold boundary, inside value, and outside value can be defined by
        the user, however the standard values are used as default if not set
        by the user. The default value of the: Inside value is the maximum
        pixel type intensity. Outside value is the minimum pixel type
        intensity. Upper threshold boundary is the maximum pixel type
        intensity. 
        """
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS3_SetInsideValue(self, _arg)


    def SetOutsideValue(self, _arg):
        """SetOutsideValue(itkThresholdMaximumConnectedComponentsImageFilterIUS3 self, unsigned short const _arg)"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS3_SetOutsideValue(self, _arg)


    def SetUpperBoundary(self, _arg):
        """SetUpperBoundary(itkThresholdMaximumConnectedComponentsImageFilterIUS3 self, unsigned short const _arg)"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS3_SetUpperBoundary(self, _arg)


    def GetInsideValue(self):
        """GetInsideValue(itkThresholdMaximumConnectedComponentsImageFilterIUS3 self) -> unsigned short"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS3_GetInsideValue(self)


    def GetOutsideValue(self):
        """GetOutsideValue(itkThresholdMaximumConnectedComponentsImageFilterIUS3 self) -> unsigned short"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS3_GetOutsideValue(self)


    def GetUpperBoundary(self):
        """GetUpperBoundary(itkThresholdMaximumConnectedComponentsImageFilterIUS3 self) -> unsigned short"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS3_GetUpperBoundary(self)


    def GetNumberOfObjects(self):
        """
        GetNumberOfObjects(itkThresholdMaximumConnectedComponentsImageFilterIUS3 self) -> unsigned long

        Returns the
        number of objects in the image. This information is only valid after
        the filter has executed. Useful if your counting something 
        """
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS3_GetNumberOfObjects(self)


    def GetThresholdValue(self):
        """
        GetThresholdValue(itkThresholdMaximumConnectedComponentsImageFilterIUS3 self) -> unsigned short

        Returns the
        automatic threshold setpoint. This information is only valid after the
        filter has executed. 
        """
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS3_GetThresholdValue(self)

    __swig_destroy__ = _itkThresholdMaximumConnectedComponentsImageFilterPython.delete_itkThresholdMaximumConnectedComponentsImageFilterIUS3

    def cast(obj):
        """cast(itkLightObject obj) -> itkThresholdMaximumConnectedComponentsImageFilterIUS3"""
        return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS3_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkThresholdMaximumConnectedComponentsImageFilterIUS3

        Create a new object of the class itkThresholdMaximumConnectedComponentsImageFilterIUS3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkThresholdMaximumConnectedComponentsImageFilterIUS3.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkThresholdMaximumConnectedComponentsImageFilterIUS3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkThresholdMaximumConnectedComponentsImageFilterIUS3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkThresholdMaximumConnectedComponentsImageFilterIUS3.Clone = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS3_Clone, None, itkThresholdMaximumConnectedComponentsImageFilterIUS3)
itkThresholdMaximumConnectedComponentsImageFilterIUS3.SetMinimumObjectSizeInPixels = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS3_SetMinimumObjectSizeInPixels, None, itkThresholdMaximumConnectedComponentsImageFilterIUS3)
itkThresholdMaximumConnectedComponentsImageFilterIUS3.GetMinimumObjectSizeInPixels = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS3_GetMinimumObjectSizeInPixels, None, itkThresholdMaximumConnectedComponentsImageFilterIUS3)
itkThresholdMaximumConnectedComponentsImageFilterIUS3.SetInsideValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS3_SetInsideValue, None, itkThresholdMaximumConnectedComponentsImageFilterIUS3)
itkThresholdMaximumConnectedComponentsImageFilterIUS3.SetOutsideValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS3_SetOutsideValue, None, itkThresholdMaximumConnectedComponentsImageFilterIUS3)
itkThresholdMaximumConnectedComponentsImageFilterIUS3.SetUpperBoundary = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS3_SetUpperBoundary, None, itkThresholdMaximumConnectedComponentsImageFilterIUS3)
itkThresholdMaximumConnectedComponentsImageFilterIUS3.GetInsideValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS3_GetInsideValue, None, itkThresholdMaximumConnectedComponentsImageFilterIUS3)
itkThresholdMaximumConnectedComponentsImageFilterIUS3.GetOutsideValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS3_GetOutsideValue, None, itkThresholdMaximumConnectedComponentsImageFilterIUS3)
itkThresholdMaximumConnectedComponentsImageFilterIUS3.GetUpperBoundary = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS3_GetUpperBoundary, None, itkThresholdMaximumConnectedComponentsImageFilterIUS3)
itkThresholdMaximumConnectedComponentsImageFilterIUS3.GetNumberOfObjects = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS3_GetNumberOfObjects, None, itkThresholdMaximumConnectedComponentsImageFilterIUS3)
itkThresholdMaximumConnectedComponentsImageFilterIUS3.GetThresholdValue = new_instancemethod(_itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS3_GetThresholdValue, None, itkThresholdMaximumConnectedComponentsImageFilterIUS3)
itkThresholdMaximumConnectedComponentsImageFilterIUS3_swigregister = _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS3_swigregister
itkThresholdMaximumConnectedComponentsImageFilterIUS3_swigregister(itkThresholdMaximumConnectedComponentsImageFilterIUS3)

def itkThresholdMaximumConnectedComponentsImageFilterIUS3___New_orig__():
    """itkThresholdMaximumConnectedComponentsImageFilterIUS3___New_orig__() -> itkThresholdMaximumConnectedComponentsImageFilterIUS3_Pointer"""
    return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS3___New_orig__()

def itkThresholdMaximumConnectedComponentsImageFilterIUS3_cast(obj):
    """itkThresholdMaximumConnectedComponentsImageFilterIUS3_cast(itkLightObject obj) -> itkThresholdMaximumConnectedComponentsImageFilterIUS3"""
    return _itkThresholdMaximumConnectedComponentsImageFilterPython.itkThresholdMaximumConnectedComponentsImageFilterIUS3_cast(obj)


def threshold_maximum_connected_components_image_filter(*args, **kwargs):
    """Procedural interface for ThresholdMaximumConnectedComponentsImageFilter"""
    import itk
    instance = itk.ThresholdMaximumConnectedComponentsImageFilter.New(*args, **kwargs)
    return instance.__internal_call__()

def threshold_maximum_connected_components_image_filter_init_docstring():
    import itk
    import itkTemplate
    if isinstance(itk.ThresholdMaximumConnectedComponentsImageFilter, itkTemplate.itkTemplate):
        threshold_maximum_connected_components_image_filter.__doc__ = itk.ThresholdMaximumConnectedComponentsImageFilter.values()[0].__doc__
    else:
        threshold_maximum_connected_components_image_filter.__doc__ = itk.ThresholdMaximumConnectedComponentsImageFilter.__doc__




