#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['prom_url_checker', 'prom_url_checker.utils']

package_data = \
{'': ['*']}

install_requires = \
['clize==4', 'aiohttp==3.5.4', 'aioprometheus==18.7.1']

extras_require = \
{'dev': ['black', 'bumpversion', 'flake8', 'flit', 'mypy'],
 'doc': ['mkdocs'],
 'test': ['pytest', 'pytest-cov', 'pytest-asyncio', 'pytest-aiohttp', 'tox']}

entry_points = \
{'console_scripts': ['prom-url-checker = prom_url_checker.app:cli_run']}

setup(name='prom-url-checker',
      version='0.0.4',
      description='Prom-url-checker, a url checker with prometheus metrics output',
      author='Matthias Ludwig',
      author_email='m.ludwig@datalyze-solutions.com',
      url='https://github.com/datalyze-solutions/prom-url-checker',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=3.6',
     )
