
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": true,
 "error": null,
 "full-revisionid": "b54d3268fcc78c9de17ace403dc8c32638eb5845",
 "version": "0.23.1.b4614"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
