import os

HOST_AUTH = os.getenv("PROPILEU_SDK_AUTH")
HOST = os.getenv("PROPILEU_SDK_HOST")
USERNAME = os.getenv("PROPILEU_USERNAME")
PASSWORD = os.getenv("PROPILEU_PASSWORD")

REQUESTS_TIMEOUT = os.getenv("PROPILEU_REQUESTS_TIMEOUT", 30)
REQUESTS_MAX_RETRIES = os.getenv("PROPILEU_REQUESTS_MAX_RETRIES", 3)
