image: python:3.6

stages:
  - test

python_test:
  stage: test
  script:
    - pip install virtualenv
    - virtualenv --python=python3 ve
    - source ve/bin/activate
    - pip3 install -rrequirements.txt
    - tox -r



