# Generated by Django 2.2.1 on 2019-06-14 18:41

from django.db import migrations, models
import issuestracker.utils.storage_service


class Migration(migrations.Migration):

    dependencies = [
        ('issuestracker', '0012_auto_20190614_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='active',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='date_exited',
        ),
        migrations.AddField(
            model_name='candidate',
            name='social_image',
            field=models.ImageField(blank=True, null=True, storage=issuestracker.utils.storage_service.StorageService(), upload_to='%Y/%m/'),
        ),
    ]
