# Generated by Django 2.2.2 on 2019-07-01 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuestracker', '0013_auto_20190614_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', related_query_name='updates', to='issuestracker.Category'),
        ),
        migrations.AlterField(
            model_name='update',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', related_query_name='updates', to='issuestracker.Issue'),
        ),
        migrations.AlterField(
            model_name='update',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
