# Generated by Django 2.2.2 on 2019-07-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuestracker', '0014_auto_20190701_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
