from distutils.core import setup
setup(
  name = 'py_cmd_app',         
  packages = ['py_cmd_app'],   
  version = '0.1',      
  license='MIT',       
  description = 'A base for creating python command line apps.',   
  author = 'Youssef Moawad',             
  author_email = 'youssef_programming@icloud.com',      
  url = 'https://devdude.me',   
  download_url = 'https://github.com/DevdudeSami/py_cmd_app/archive/0.1.tar.gz',   
  keywords = [],   
  install_requires=[],
  classifiers=[
    'Development Status :: 4 - Beta',  
    'Intended Audience :: Developers',      
    'Topic :: Software Development :: Build Tools',
    'License :: OSI Approved :: MIT License',   
    'Programming Language :: Python :: 3',     
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
  ],
)