[tool.poetry]
name = "rarbg"
version = "1.2.2"
description = "RSS interface to TorrentAPI"
authors = ["banteg <banteeg@gmail.com>"]
repository = "https://github.com/banteg/rarbg"
readme = "readme.md"

[tool.poetry.dependencies]
python = "^3.6"
aiohttp = "^3.5"
python-dateutil = "^2.8"
humanize = "^0.5.1"
jinja2 = "^2.10"
click = "^7.0"

[tool.poetry.scripts]
rarbg = "rarbg:main"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
