# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hd_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeevent',
            old_name='type',
            new_name='name',
        ),
    ]
