# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_data', '0003_auto_20190527_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Témoignage'),
        ),
    ]
