# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_data', '0004_testimony_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.TextField(blank=True, max_length=225, null=True, verbose_name='Adresse'),
        ),
    ]
