# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-05 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hd_data', '0006_event_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locationevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Lieu, établissement')),
                ('adress', models.TextField(blank=True, max_length=225, null=True, verbose_name='Adresse')),
            ],
            options={
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view', 'control'),
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='place',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hd_data.Locationevent', verbose_name="Lieu de l'évènement"),
        ),
    ]
