# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-26 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_data', '0010_auto_20190613_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='porteur',
            field=models.CharField(default='PO', max_length=2, verbose_name='Porteur de cellule'),
        ),
    ]
