# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-01 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_data', '0017_auto_20190628_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='textautre',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
