# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-10 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_data', '0019_auto_20190701_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='howhelp',
            name='keyword',
            field=models.CharField(default='client', max_length=15, verbose_name='mot-clé'),
        ),
    ]
