
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": true,
 "error": null,
 "full-revisionid": "f54a8bca3b4027bf4492cdf6ea4294c885fc2784",
 "version": "0.22.22.b4545"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
