language: python
python:
  - 2.7

cache:
  pip: true
  directories:
    - buildout-cache/downloads
    - buildout-cache/eggs

install:
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap.py -c travis.cfg
  - bin/buildout -N -c travis.cfg annotate
  - bin/buildout -c travis.cfg -N -q -t 3

script:
  - bin/test

notifications:
  email:
    - travis-reports@ecreall.com
    - devs@imio.be
