[tool.poetry]
name = "galaxy-fds-sdk"
version = "1.4.23"
description = "Python sdk for Galaxy FDS"
authors = ["hujianxin <hujianxin@xiaomi.com>"]
packages = [
    { include = "fds" },
]

[tool.poetry.dependencies]
python = "^3"
requests = "^2.21"
argcomplete = "^1.9"
click = "^7.0"

[tool.poetry.dev-dependencies]
rope = "^0.14.0"
pep8 = "^1.7"
autopep8 = "^1.4"
black = {version = "^18.3-alpha.0",allows-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
