# https://travis-ci.org/django-polymorphic/django-polymorphic
dist: xenial
sudo: false
language: python

services:
  - postgres
addons:
  postgresql: "9.6"

matrix:
  fast_finish: true
  include:
    # Django 1.11: Python 2.7, 3.5, or 3.6
    - { env: TOXENV=py27-django111, python: 2.7 }
    - { env: TOXENV=py35-django111, python: 3.5 }
    - { env: TOXENV=py36-django111, python: 3.6 }
    - { env: TOXENV=py36-django111-postgres DB=postgres, python: 3.6 }
    # Django 2.0: Python 3.5, or 3.6
    - { env: TOXENV=py35-django20, python: 3.5 }
    - { env: TOXENV=py36-django20, python: 3.6 }
    - { env: TOXENV=py36-django20-postgres DB=postgres, python: 3.6 }
    # Django 2.1: Python 3.6, or 3.7
    - { env: TOXENV=py36-django21, python: 3.6 }
    - { env: TOXENV=py37-django21, python: 3.7 }
    - { env: TOXENV=py37-django21-postgres DB=postgres, python: 3.7 }
    # Django 2.2: Python 3.6, or 3.7
    - { env: TOXENV=py36-django22, python: 3.6 }
    - { env: TOXENV=py37-django22, python: 3.7 }
    - { env: TOXENV=py37-django22-postgres DB=postgres, python: 3.7 }
    # Django development master (direct from GitHub source):
    - { env: TOXENV=py36-djangomaster, python: 3.6 }
    - { env: TOXENV=py37-djangomaster, python: 3.7 }
    - { env: TOXENV=py37-djangomaster-postgres DB=postgres, python: 3.7 }

  allow_failures:
    - env: TOXENV=py36-djangomaster
    - env: TOXENV=py37-djangomaster
    - env: TOXENV=py37-djangomaster-postgres DB=postgres

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox

before_install:
- psql -c 'CREATE DATABASE default;' -U postgres || true
- psql -c 'CREATE DATABASE secondary;' -U postgres || true

install:
  - pip install --upgrade pip wheel setuptools
  - pip install codecov coverage tox

script:
  - tox

after_success:
  - coverage xml -i
  - codecov

branches:
  only:
    - master
