[build-system]
requires = ['flit']
build-backend = 'flit.buildapi'

[tool.flit.metadata]
module = 'fastgenomics'
author = 'FASTGenomics Team'
author-email = 'contact@fastgenomics.org'
home-page = 'https://github.com/fastgenomics/fastgenomics-py'
description-file = 'README.md'
requires-python = '~=3.6'

requires = [
        'deprecated (~=1.2.4)', 
	'jsonschema (~=2.6)',
	'Jinja2 (~=2.9)',
	'get_version (~=2.0.1)',
	'setuptools'  # get the installed version
]
classifiers = [
	'Development Status :: 5 - Production/Stable',
	'Environment :: Console',
	'Intended Audience :: Developers',
	'Intended Audience :: Science/Research',
	'Natural Language :: English',
	'Operating System :: MacOS :: MacOS X',
	'Operating System :: Microsoft :: Windows',
	'Operating System :: POSIX :: Linux',
	'Programming Language :: Python :: 3',
	'Programming Language :: Python :: 3.6',
	'Topic :: Scientific/Engineering :: Bio-Informatics',
	'Topic :: Scientific/Engineering :: Visualization',
	'License :: OSI Approved :: MIT License',
]

[tool.flit.metadata.requires-extra]
doc = [
    'sphinx',
    'sphinx_rtd_theme',
    'sphinx-autodoc-typehints',
]
test = [
     "pytest >=4",
     "anndata >=0.6",
     'scipy (>=1.2.1)'
]

[tool.flit.metadata.urls]
Documentation = 'https://fastgenomics.readthedocs.io'
