
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-25T10:18:34-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "da99945ac4a6d3460a2f024a6371e97c2fa16659",
 "version": "0.3.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
