
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-18T17:52:29-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "7ee0bde3a9be44c01488078381cee9b8d9b3caaf",
 "version": "1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
