
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-28T11:55:53+0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ac77beadd20c7a63187a8dbe79ddd52b0a995c9a",
 "version": "0.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
