[tool.poetry]
name = "ipython-namespaces"
version = "0.1.1"
description = "Extension for IPython/Jupyter Notebooks that adds namespaces that you can enter and re-enter"
authors = ["Denis Drescher <denis.drescher@claviger.net>"]
repository = "https://bitbucket.org/Telofy/ipython-namespaces"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
ipython = "^5.0"

[tool.poetry.dev-dependencies]
pytest = "^5.0"

[build-system]
requires = ["poetry>=0.12", "jsonschema>=3.0.1"]
build-backend = "poetry.masonry.api"
