dist: xenial
language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: 3.7
      env: TOXENV=lint
    - python: 3.7
      env: DEPLOYER=true
    - python: 3.6
    - python: 3.8-dev

install:
  - pip install -U pip
  - pip install -U tox-travis

script:
  - tox

after_success:
  - |
    if [ "$TOXENV" != "lint" ]; then
      pip install codecov && codecov
    fi

deploy:
  - provider: pypi
    server: https://test.pypi.org/legacy/
    on:
      tags: false
      repo: hugovk/tinytext
      branch: master
      condition: $DEPLOYER = true
    user: "@token"
    password:
      secure: "GanrAfzFDsURl5vFNaWe3VT4/39v6GRhgOh6N5Bq2iKajCQ1758zX5J9IHlf5Jz+2TFMbkDTJpMbG3TKAQ3xkarK600rPdorVWIPDsEIgfvpzG/a65oyEpCLo4C2xT6EydhfZvQSJy0XQwnTyHJuM4kkVvDytSB9X87YtOK330dacYxseZWCb85grkf7Csf+1ScEvQURmldGb4DFY9cQwMGtVqWXAHnfScTnDKaycQr5AaX/e+8UzzWYYE7xXvnbXtUibyEi1VqyU3FcC0MOIfX1z3CoZRtz0EX/vSMINjg+neTSpWmNEqyhTkEWYWmCjtqj3Um1jsZUSXtjwqqbuuD2SBOyOQ55M1FePLgsb3iORByhDdVFsVdvVvQw1KIla8Zubjg75GSRXbJO/PJ5drjy5xpNJNAzFNxeNfcg0ZI+tb+4dVjTPmW0JOtNAYy/GSRkPkX1OgF396nx2Bs3qwNZ4+CI38Arfa2hXFBiT2OjUilRct55Ho9g1HLiiKxjYsFmzAtwD13yL13WOvYkmM3XZHuL5/WJD1COZQ4ZUVuGiI9wOxiC1//gCSC3H2IUMFTZ9RMEqauMba3VYo1eBOhqNykCOJve0aE5D3C/nF6yej27+w9TKQErmOreHo198ej2FGHb0yOxW+1iCQz9hH67CRGjE0PStqAKTVcpwRo="
    distributions: sdist --format=gztar bdist_wheel
    skip_existing: true
  - provider: pypi
    on:
      tags: true
      repo: hugovk/tinytext
      branch: master
      condition: $DEPLOYER = true
    user: "@token"
    password:
      secure: "V8tmw/GjaN+Yk/eeJCcDEhEKWqyQY7H1cpDKCvATxaBdc4261dbgfKWjpifx8a9ByjW5POY09SuM5spyA8XawnA61RLItUdDi6p/OK2vZ/AGK8gYrvKbsLPzZQoq1/hzNyD9wRQNFcF0d2U4VYNbYiGiwN2qVWe9A1JCWqcwLPeu+ioeDKM2DgPmaa9nViYNtNmsNwWDB+ptztp17zKLaXL7W3Rhe2B4Tid/v8fNqKdkHGuH60VSNL2eqWWWap/yDctTB9nqqpLl9ZOWgWYrZQzyzeMSzUp0s80YCIty+umMC5GdaMZX4qsj4A4dk2sa6sU2IasmHs0kKHNqs3r6QE9TOcxMI1JFPch3jq+i+nRg1bA1E+JjYmlvVdPJhKrlMv/jvDiaukMtFa+Kk52xGXFWwDX5IC+Vedv/xRSVLE2/WgHLGWfV7t0bWeZaUhx3OS2L8eJh4eCRHGG68o0VoXmSPLEM7tzRT0sy1THyLY/nTwFh3/u99kG4xFUQ6TGntRzRCBVFj/bjmvqlLMeOb+yTuIG0bHUG7e+ozYZAGGCUu0VTemlYG0jSmiqU4QeKJS3YSMWuglUTxgg/9LPRj4OJsuhvfOejygz1hERruhMewmpZtNJStEuN2L+Tmxj/pymO8x9QL6unTp+yhH7us+f3CApjY/c275qGhi3nm3I="
    distributions: sdist --format=gztar bdist_wheel
    skip_existing: true
