# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/

sudo: false
language: python
virtualenv:
  system_site_packages: false
matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      env: DISTRIB="conda" PYTHON_VERSION="3.7" COVERAGE="false"
    - python: 3.6
      env: DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="false"
    - python: 3.5
      env: DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="false"
    - python: 2.7
      env: DISTRIB="conda" PYTHON_VERSION="2.7" COVERAGE="false"


install:
  - source tests/travis_install.sh

before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
script:
  - python setup.py test
  - tox
  - |
    if [[ "$COVERAGE" == "true" ]]; then
      pre-commit install
      pre-commit run --all-files
    fi
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
after_script:
  - travis-cleanup
cache:
  pip: true
  directories:
    - $HOME/miniconda
