# This file was automatically generated by sub\epyqlib\epyqlib\cli\generateversion.py
__version_build_time__ = '2019-07-21T22:26:37.933394'

__version__ = '2019.7.3'
__sha__ = 'cf99e62925c3d1ed0f28ec15d6f70aa7c958d861'
__revision__ = 'cf99e62925c3d1ed0f28ec15d6f70aa7c958d861'
