{% if db %}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ project_name }}-db
spec:
  template:
    spec:
      containers:
      - name: {{ project_name }}-db
        image: postgres:11-alpine
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 5432
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - exec pg_isready -U $POSTGRES_USER -d {{ project_name }}-db -h localhost
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - exec pg_isready -U $POSTGRES_USER -d {{ project_name }}-db -h localhost
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ project_name }}-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ project_name }}-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: {{ project_name }}-db
{% endif %}
