[tool.poetry]
name = "devo"
version = "0.9.0"
description = ""
authors = ["Dominic Werner <aka.vince@gmail.com>"]
license = "MIT"

[tool.poetry.scripts]
devo = 'devo.main:cli'

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.0"
"ruamel.yaml" = "^0.15.94"
python-gitlab = "^1.8"
jinja2 = "^2.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
