XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX    
    BBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBBB
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XX XXXXXXX 
            XXXXXXXXXXXXXXXXXXXXXXXXXX 
            XXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX 
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX
            XXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX 
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXX X XXXXXXXXXXXXXXXXX
                    XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXX XX XXXXXXXXX 
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX 
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXXXXX
                        XX XXXXXXXXXXXXXXXXXX 
                            XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX 
                            XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX 
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXX
                            XXXXXX

                    XXXXXXX
                    XXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXX 
                        XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXX XXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXX XXXXXXX
                XXXXXX
                XXXX XXXXXX 
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX XXXXXXXXXXXXXX XX XXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                            XXXXXXXX
                        XX XXXXXXXXXXXXXXXXXX 
                        XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX 
                        XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXX
                    XXXXXXXXXXX
                    XXXXXXXXX XXXXXXX
                        XX XXXXXXXXXXXXXXXXXX 
                        XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXX XXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXX XXXXXXXXXXX
                    XXXXXXXXXXX
                XXXXXX
            XXXXXX XXXX XXXXXXXXXXXXXXXX XXX
            XXXX XXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXX XX XXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX X X XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXXX
            XXXXX
        XXXXXX
    XXXXXX
    BBBBBBBBBBB
    XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXBB BBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXX