#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pyatsa']

package_data = \
{'': ['*'], 'pyatsa': ['.empty/*', '.ipynb_checkpoints/*', 'tests/*']}

install_requires = \
['numpy>=1.8',
 'scipy>=1.3.0',
 'scikit-image>=0.15',
 'statsmodels>=0.10.0',
 'scikit-learn>=0.21.2',
 'xarray>=0.12.3',
 'dask>=2.1.0',
 'rasterio>=1.0.7',
 'porder>=0.3.7']

setup(name='pyatsa',
      version='0.2',
      description='The ATSA cloud masking method for Planetscope 4-band imagery',
      author='Ryan Avery',
      author_email='ravery@ucsb.edu',
      url='https://github.com/agroimpacts/pyatsa',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.5',
     )
