[tool.poetry]
name = "sd_cloud_utils"
version = "0.1.1"
description = ""
authors = ["Sean Davis <seandavi@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
boto3 = "^1.9"

[tool.poetry.dev-dependencies]
pytest = "^3.0"


[tool.dephell]
[tool.dephell.poetry]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "poetrylock", path = "poetry.lock"}

[build.setup]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.dephell.main]
envs = ["main"]

