[tool.poetry]
name = "ipython-namespaces"
version = "0.1.0"
description = "Extension for IPython/Jupyter Notebooks that adds namespaces that you can enter and re-enter"
authors = ["Denis Drescher <denis.drescher@claviger.net>"]

[tool.poetry.dependencies]
python = "^3.6"
ipython = "^5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
