---
- name: Install zsh
  apt: name=zsh state=present

- name: Create the 'ansibl' group
  group: name=ansibl state=present

- name: Create the 'ansibl' user
  user: name=ansibl shell=/bin/bash groups=ansibl append=yes

- name: Protect home directory
  file: path=/home/ansibl state=directory owner=ansibl group=ansibl mode=0700

- name: Create ssh directory
  file: path=/home/ansibl/.ssh state=directory owner=ansibl group=ansibl mode=0700

- name: Copy ssh public key
  copy: src=files/ansible.pub dest=/home/ansibl/.ssh/authorized_keys owner=ansibl group=ansibl mode=0400

- name: Add 'ansibl' group to sudoers
  lineinfile: dest=/etc/sudoers state=present regexp='^%ANSIBL ALL\=' line='%ANSIBL ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'
