# This is a common .travis.yml for generating library release zip files for
# CircuitPython library releases using circuitpython-build-tools.
# See https://github.com/adafruit/circuitpython-build-tools for detailed setup
# instructions.

dist: xenial
language: python
python:
  - "3.6"

cache:
  pip: true

env:
  - DEPLOY_PYPI="true"

deploy:
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file: "$TRAVIS_BUILD_DIR/bundles/*"
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
  # TODO: Use 'travis encrypt --com -r adafruit/<repo slug>' to generate
  #       the encrypted password for adafruit-travis. Paste result below.
  - provider: pypi
    user: fourstix
    password:
      secure: uYIy80a9qoGtRUQsczO8b7HRwhd2PELYjBpHuFGCgbj9nMsPyiwgHwREZhF7sr1Mbw3uI2DQaqqVvhax/9inncO9pX1228Iaw8bfgxVrnhhiRr4ruUleGr9z7Fp1TxLFfo2/bZVSq0NJ2abZ7JuCAkB9KxL50eeoo5vtVk8ZUlsi1DOxdiU9VgrGZ3cVemiBH49RZzZ/n3sTAkWmFIzzpc2daTU0yX9UOBTNwXUf8aL+g+jOgAGN8XLbRwgd/HU09evnaQh93U1cxb+3QC9TbM3tLTEWCmB/YN1AtGYj1z8+PvBKtbuzcH0TktBZ2yFiOXbD7ikeq7nJApD2uLc/t7Y4UTSjOvoeqy/YTbCEgQxo75hVFuZe5PIQH4/hFGULY/7FTW0T36qdVtLkwNSUP7ZYSX6rZFVo9FdZSPaKB5g4Ve+gQRJzOepK8faTyGfUgl7LlQqI7xPogNlXYsn9RxzRr2ZU5vC9qKu8Pk7/mBGF9pvPKx1CE3lYi41CePDxRFMDrbdtLEHyfQ2K+qt7Nlk4mzyqFgo8kb+LFfRzSRbDdEmHC9htaEA1cAk/UJJhNMNRZKYYuVfJHBbaQhnT7ponK1Gjmrhen9d+fZ7ojyHG5baKdYMtAtfTYsgU3O/7GzaEBPYjBow69ESlKFWUBh4Ik8KJNNa8Qmd0VhMzPIc=
    on:
      tags: true
      condition: $DEPLOY_PYPI = "true"

install:
  - pip install -r requirements.txt
  - pip install circuitpython-build-tools Sphinx sphinx-rtd-theme
  - pip install --force-reinstall pylint==1.9.2

script:
  - pylint sparkfun_qwiicas3935.py
  - ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace examples/*.py)
  - circuitpython-build-bundles --filename_prefix sparkfun-circuitpython-qwiicas3935 --library_location .
  - cd docs && sphinx-build -E -W -b html . _build/html && cd ..
