
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-12T10:41:03-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "8d9d1a315d9754b452406146e945bca12ce0b5f1",
 "version": "0.4.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
