# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Package:
      python.version: '3.7'
      tox.env: package

    Manifest:
      python.version: '3.7'
      tox.env: manifest

    Python37:
      python.version: '3.7'
      tox.env: py37

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements/dev.txt
  displayName: 'Install dev dependencies'

- script: |
    tox -e $(tox.env)
  displayName: 'test `tox -e $(tox.env)`'
