#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['undefined']

package_data = \
{'': ['*'], 'undefined': ['tests/*']}

setup(name='undefined',
      version='0.0.8',
      description='a simple package',
      author='Matthias Bussonnier',
      author_email='bussonniermatthias@gmail.com',
      url='https://github.com/Carreau/undefined',
      packages=packages,
      package_data=package_data,
      python_requires='>=3.4',
     )
