[tool.poetry]
name = "midnite"
version = "0.1.1"
description = "This is a framework for visualization and uncertainty in CNNs."
authors = ["Christina Aigner, Fabian Huch"]
homepage = "https://luminovo.gitlab.io/midnite"

[tool.poetry.dependencies]
python = "^3.7"
torch = "=1.1"
numpy = "^1.16"
pillow = "^6.1"
opencv-python = "^4.0"
tqdm = "^4.31"

[tool.poetry.dev-dependencies]
pytest = "^3.8"
gdown = "^3.7"
jupyter = "^1.0"
matplotlib = "^3.0"
assertpy = "^0.14"
pytest-mock = "^1.10"
torchvision = "^0.3"
tabulate = "^0.8"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
