---
- name: sshd configuration
  copy: src=sshd_config dest=/etc/ssh/sshd_config owner=root group=root mode=0644
  notify: restart sshd

- name: create candidates
  command: ssh-keygen -G /etc/ssh/moduli-2048.candidates -b 2048 creates=/etc/ssh/moduli-2048.candidates

- name: select candidates
  command: ssh-keygen -T /etc/ssh/moduli -f /etc/ssh/moduli-2048.candidates creates=/etc/ssh/moduli
