[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "keruk"
author = "Aditya Kelvianto Sidharta"
author-email = "aditya.sdrt@gmail.com"
home-page = "https://github.com/AdityaSidharta/keruk"
classifiers = ["License :: OSI Approved :: MIT License"]
requires = ["requests>=2.22.0",
            "pandas>=0.24",
            "beautifulsoup4>=4.8"]
