
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-10T11:05:59+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6952485a4d6052fa8f42c6da30239505d24738eb",
 "version": "0.6.63"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
