# -*- coding: utf-8 -*-

"""
    api_tester_upload_test

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import api_tester_upload_test.models.result_share

class CreateAndAlterShareResponse(object):

    """Implementation of the 'CreateAndAlterShareResponse' model.

    TODO: type model description here.

    Attributes:
        error (string): TODO: type description here.
        result (ResultShare): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "error":'error',
        "result":'result'
    }

    def __init__(self,
                 error=None,
                 result=None):
        """Constructor for the CreateAndAlterShareResponse class"""

        # Initialize members of the class
        self.error = error
        self.result = result


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        error = dictionary.get('error')
        result = api_tester_upload_test.models.result_share.ResultShare.from_dictionary(dictionary.get('result')) if dictionary.get('result') else None

        # Return an object of this model
        return cls(error,
                   result)


