language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"

cache: apt
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran

#before_install:
#- sudo apt-get update -qq
#- sudo apt-get install -qq libgfortran3:i386
#- conda install libgfortran==1

install:
    - pip install --upgrade pip setuptools wheel
    - pip install --only-binary=numpy,scipy numpy scipy
    - pip install -r requirements.txt
script:
    - py.test