# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-02 00:37
from __future__ import unicode_literals

import authwrapper.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authwrapper', '0003_auto_20170710_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='account_type',
            field=models.CharField(blank=True, choices=[('username', 'username'), ('mail', 'mail'), ('phone', 'phone')], default='username', max_length=50, null=True, verbose_name='account type'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=authwrapper.models.image_upload_to, verbose_name='image'),
        ),
    ]
