# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-16 05:26
from __future__ import unicode_literals

import authwrapper.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authwrapper', '0004_auto_20171202_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=authwrapper.fields.PhoneNumberNullField(blank=True, error_messages={'unique': 'A user with that phone number already exists.'}, help_text='Required. digits and + only.', max_length=30, null=True, unique=True, verbose_name='phone'),
        ),
    ]
