# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-30 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authwrapper', '0005_auto_20171216_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_role',
            field=models.CharField(choices=[('admin', 'administrator'), ('guest', 'guest'), ('driver', 'driver')], default='guest', max_length=50, verbose_name='user role'),
        ),
    ]
