# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-17 13:57
from __future__ import unicode_literals

import authwrapper.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authwrapper', '0006_myuser_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=authwrapper.fields.PhoneNumberNullField(blank=True, error_messages={'unique': 'A user with that phone number already exists.'}, max_length=30, null=True, unique=True, verbose_name='phone'),
        ),
    ]
