
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-18T16:32:40+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "50b63458b8274be1143b778cb165ee491c54d648",
 "version": "0.0.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
