
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-21T11:49:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "42cbf8055bb5a02c45904b43c3c75292c80cead4",
 "version": "2.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
