# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nodeflux/types/v1beta1/bounding_box.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nodeflux/types/v1beta1/bounding_box.proto',
  package='nodeflux.types.v1beta1',
  syntax='proto3',
  serialized_options=_b('\n\031io.nodeflux.types.v1beta1B\020BoundingBoxProtoP\001Z6gitlab.com/nodefluxio/nodefluxapis/types/v1beta1;types'),
  serialized_pb=_b('\n)nodeflux/types/v1beta1/bounding_box.proto\x12\x16nodeflux.types.v1beta1\"G\n\x0b\x42oundingBox\x12\x0b\n\x03top\x18\x01 \x01(\x02\x12\x0c\n\x04left\x18\x02 \x01(\x02\x12\x0e\n\x06height\x18\x03 \x01(\x02\x12\r\n\x05width\x18\x04 \x01(\x02\x42g\n\x19io.nodeflux.types.v1beta1B\x10\x42oundingBoxProtoP\x01Z6gitlab.com/nodefluxio/nodefluxapis/types/v1beta1;typesb\x06proto3')
)




_BOUNDINGBOX = _descriptor.Descriptor(
  name='BoundingBox',
  full_name='nodeflux.types.v1beta1.BoundingBox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='top', full_name='nodeflux.types.v1beta1.BoundingBox.top', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='left', full_name='nodeflux.types.v1beta1.BoundingBox.left', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='nodeflux.types.v1beta1.BoundingBox.height', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='nodeflux.types.v1beta1.BoundingBox.width', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=140,
)

DESCRIPTOR.message_types_by_name['BoundingBox'] = _BOUNDINGBOX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BoundingBox = _reflection.GeneratedProtocolMessageType('BoundingBox', (_message.Message,), dict(
  DESCRIPTOR = _BOUNDINGBOX,
  __module__ = 'nodeflux.types.v1beta1.bounding_box_pb2'
  # @@protoc_insertion_point(class_scope:nodeflux.types.v1beta1.BoundingBox)
  ))
_sym_db.RegisterMessage(BoundingBox)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
