# This file was automatically generated by sub\epyqlib\epyqlib\cli\generateversion.py
__version_build_time__ = '2019-07-19T20:42:17.814632'

__version__ = '2019.7.1'
__sha__ = 'bf6316a7d825576d4f8ed867e4e64d45e0f9472b'
__revision__ = 'bf6316a7d825576d4f8ed867e4e64d45e0f9472b'
