[tool.poetry]
name = "podcast-archiver"
version = "1.0.0-alpha"
description = "Feed parser and download client for local podcast archival"
authors = ["Jan Willhaus <mail@janwillhaus.de>"]
license = "Apache-2.0"
repository = "https://github.com/janw/podcast-archiver"


[tool.poetry.dependencies]
python = "^3.7"
feedparser = "^5.2"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
podcast-archiver = 'podcast_archiver.__main__:main'

[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
  | \.git
  | \.tox
  | \.venv
)/
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
