sudo: false
language: python

os: linux
dist: xenial

git:
  depth: 3
  submodules: false

branches:
  only:
    - master
    - next

matrix:
  fast_finish: true

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"

cache: pip

install:
  - pip install --upgrade -r venv/requirements-test.txt
  - pip install --upgrade -r requirements.txt
  - pip install --upgrade .
  - sadm --version

script: ./check.sh
