# Initial set of jobs that will be extended over time as
# we get things working.
- project:
    templates:
      - integrated-gate-py3
      - publish-openstack-docs-pti
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-functional
        - openstack-tox-functional-py35
        - openstack-tox-functional-py36
        - placement-perfload:
            voting: false
        - tempest-full-py3:
            # Alias 'gate-irrelevant-files' define the set of irrelevant-files
            # for which integrated testing jobs not required to run. If
            # changes are only to those files then, zuul can skip the
            # integrated testing job to save the infra resources.
            # 'gate-irrelevant-files' should be used for integrated gate
            # jobs only not for any other jobs like functional, unit, doc
            # jobs.
            irrelevant-files: &gate-irrelevant-files
              - ^api-.*$
              - ^.*\.rst$
              - ^.git.*$
              - ^doc/.*$
              - ^placement/tests/.*$
              - ^releasenotes/.*$
              - ^tools/.*$
              - ^tox.ini$
        - grenade-py3:
            irrelevant-files: *gate-irrelevant-files
    gate:
      jobs:
        - openstack-tox-functional
        - openstack-tox-functional-py35
        - openstack-tox-functional-py36
        - tempest-full-py3:
            irrelevant-files: *gate-irrelevant-files
        - grenade-py3:
            irrelevant-files: *gate-irrelevant-files

- job:
    name: placement-perfload
    parent: base
    description: |
        A simple node on which to run placement with the barest of configs and
        make performance related tests against it.
    required-projects:
        - opendev.org/openstack/placement
    irrelevant-files:
        - ^.*\.rst$
        - ^api-ref/.*$
        - ^doc/.*$
        - ^releasenotes/.*$
        - ^.git.*$
        - ^placement/tests/.*$
        - ^tox.ini$
    run: playbooks/perfload.yaml
    post-run: playbooks/post.yaml
