
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-19T15:15:37-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d8fedbe1fa244f20438eb937d13bbd95c61878ad",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
