[build-system]
requires = [
    "wheel",
    "setuptools",
    "Cython>=0.29.2",
    "numpy; python_version=='2.7'",
    "numpy==1.13.3; python_version=='3.5'",
    "numpy==1.13.3; python_version=='3.6'",
    "numpy==1.14.5; python_version>='3.7'",
]