
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-25T12:05:15+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "e5867e2c781c175e46fffc5a69c34b9740adf1d7",
 "version": "v1.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
