[tool.poetry]
name = "xlscrap"
version = "0.1.0"
description = "A package to ease Excel files mass data extraction"
authors = ["Philippe ENTZMANN <philippe@phec.net>"]
license = "BSD-3-Clause"
readme = "README.md"
keywords = ['spreadsheet', 'poetry']

[tool.poetry.dependencies]
python = "^3.7"
openpyxl = "^2.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
jupyterlab = "^1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
