
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": true,
 "error": null,
 "full-revisionid": "0cb3acd74a9ea9f6a7818a4b2e7b5749c02df225",
 "version": "0.22.24.b4573"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
