# Generated by Django 2.2.3 on 2019-07-20 00:20

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='first name')),
                ('last_name', models.CharField(max_length=25, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('language', models.CharField(max_length=2, verbose_name='language')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='country')),
                ('subscribed', models.BooleanField(default=True, verbose_name='subscribed')),
                ('uploaded', models.BooleanField(default=False, verbose_name='uploaded')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'verbose_name': 'subscriber',
                'verbose_name_plural': 'subscribers',
                'ordering': ('-created',),
            },
        ),
    ]
