apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app
{% if db %}
  - db
{% endif %}

commonLabels:
  app.kubernetes.io/part-of: {{ project_name }}


secretGenerator:
  - name: {{ project_name }}-secrets
    literals:
{% if db %}
      - POSTGRES_USER={{ project_name }}
      - POSTGRES_PASSWORD={{ project_name }}
{% endif %}
      - DEBUG=True
