
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-25T18:21:32+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "b1c3cdf1c25c48fc27210d1b043cab87e834e22e",
 "version": "1.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
