
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-19T09:25:53+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "93a7d0b04db95150b2754bfc81dc79287f3fd8b8",
 "version": "0.9.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
