ACTION_BUY = 'Buy'
ACTION_SELL = 'Sell'

STOCK_PRICE_TYPE_LIMITPRICE = 'LMT'
STOCK_PRICE_TYPE_CLOSE = 'Close'
STOCK_PRICE_TYPE_LIMITUP = 'LimitUp'
STOCK_PRICE_TYPE_LIMITDOWN = 'LimitDown'

STOCK_ORDER_TYPE_COMMON = 'Common'  # 整股
STOCK_ORDER_TYPE_BLOCKTRADE = 'BlockTrade'  # 鉅額
STOCK_ORDER_TYPE_FIXING = 'Fixing'  # 定盤
STOCK_ORDER_TYPE_ODD = 'Odd'  # 零股

STOCK_ORDER_COND_CASH = 'Cash'  # 現股
STOCK_ORDER_COND_NETTING = 'Netting'  # 餘額交割
STOCK_ORDER_COND_MARGINTRADING = 'MarginTrading'  # 融資
STOCK_ORDER_COND_SHORTSELLING = 'ShortSelling'  # 融券

STOCK_FIRST_SELL_YES = 'true'
STOCK_FIRST_SELL_NO = 'false'

FUTURES_PRICE_TYPE_LMT = 'LMT'
FUTURES_PRICE_TYPE_MKT = 'MKT'
FUTURES_PRICE_TYPE_MKP = 'MKP'

FUTURES_ORDER_TYPE_ROD = 'ROD'
FUTURES_ORDER_TYPE_IOC = 'IOC'
FUTURES_ORDER_TYPE_FOK = 'FOK'

FUTURES_OCTYPE_AUTO = 'Auto'
FUTURES_OCTYPE_NEWPOSITION = 'New'
FUTURES_OCTYPE_COVER = 'Cover'
FUTURES_OCTYPE_DAYTRADE = 'DayTrade'

FUTURES_CALLPUT_FUT = 'F'
FUTURES_CALLPUT_CALL = 'C'
FUTURES_CALLPUT_PUT = 'P'

QUOTE_TYPE_TICK = 'tick'
QUOTE_TYPE_BIDASK = 'bidask'