
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-13T15:30:08-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "812b3a4ea628276c5f6f9b72f7130a86296ec2dd",
 "version": "2021.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
