stages:
  - dist
  - build
  - test

.dist-artifacts: &dist-artifacts
  after_script:
    # list files
    - find dist
  artifacts:
    expire_in: 18h
    paths:
      - dist

# -- dist -------------------

dist:tarball:
  <<: *dist-artifacts
  stage: dist
  image: python:3.6
  script:
    - python -m pip install setuptools
    - python setup.py sdist bdist_wheel

# -- build ------------------

.build: &build
  <<: *dist-artifacts
  stage: build
  dependencies:
    - dist:tarball

.build:el: &build-rhel
  <<: *build
  before_script:
    # install enough to create a src RPM and parse the build dependencies
    - yum -y -q install
          yum-utils
          rpm-build
          python34
          python3-rpm-macros
  script:
    - DIST_NAME=${CI_JOB_NAME#build:rhel:}
    - mkdir -pv dist/${DIST_NAME}
    # build src rpm
    - SRC_RPM=$(rpmbuild -ts dist/bruco*.tar.gz | cut -d\  -f2)
    # install build dependencies for src rpm
    - yum-builddep -y -q ${SRC_RPM}
    # build binary rpms
    - rpmbuild --rebuild ${SRC_RPM}
    # move things into dist/
    - mv -v ~/rpmbuild/RPMS/*/python*-bruco-*.rpm dist/${DIST_NAME}/

.build:debian: &build-debian
  <<: *build
  before_script:
    - apt-get update -yqq
    - apt-get install -yq
          dpkg-dev
          devscripts
  script:
    - DIST_NAME=${CI_JOB_NAME#build:debian:}
    - mkdir -pv dist/${DIST_NAME}
    # unpack tarball
    - mkdir -pv build
    - tar -xvf dist/bruco-*.tar.gz -C ./build --strip-components=1
    - pushd build
    # install build dependencies
    - mk-build-deps --tool "apt-get -y" --install --remove
    # build debian packages
    - dpkg-buildpackage -us -uc -b
    # move things into dist/
    - popd
    - mv -v {python,python3}-bruco_*.deb bruco_*.{buildinfo,changes} dist/${DIST_NAME}/

build:rhel:el7:
  <<: *build-rhel
  image: ligo/base:el7

build:debian:stretch:
  <<: *build-debian
  image: ligo/base:stretch

# -- test -------------------

.test: &test
  stage: test
  dependencies:
    - dist:tarball
  before_script:
    - python -m pip install dist/bruco-*.tar.gz
  script:
    - python -m bruco --help

test:python2.7:
  <<: *test
  image: python:2.7

test:python3.5:
  <<: *test
  image: python:3.5

test:python3.6:
  <<: *test
  image: python:3.6

test:python3.7:
  <<: *test
  image: python:3.7
