[tool.poetry]
name = "imagestoanimation"
version = "0.1.8"
description = "Converts a series of images to an animation using OpenCV"
authors = ["jpsmithnl <jp.smith@mun.ca>"]
homepage = "https://github.com/jpsmithnl/imagesToAnimation"
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
opencv-python = "^4.1"
configargparse = "^0.14.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
imgvid = 'imagesToAnimation:run'
