language: cpp

branches:
  only: 
    - master

env:
- PYTHON_BUILD_VERSION=3.7

dist: xenial
sudo: false

addons:
  apt:
    packages:
    - git 
    - cmake 
    - build-essential 
    - libxmu-dev 
    - libxi-dev 
    - xorg-dev
    - freeglut3-dev 
    - libglfw3-dev 
    - libglew-dev
    - python3-dev 
    - python3-pip
    - python3-setuptools

script: |
  git submodule init
  git submodule update
  
  cd src_cpp/external/glfw
  cmake .
  make
  cd ../../../

  cd tests/googletest
  cmake .
  make
  cd ../../

  cd tests
  mkdir buildMake
  cd buildMake
  cmake ..
  make
  make test 
  ./runUnitTests
  cd ../../

  cd examples_cpp
  mkdir buildMake
  cd buildMake
  cmake ..
  make -i
  cd ../..

  pyenv versions
  pyenv global 3.7
  python --version  

  cd src_pybind/core
  mkdir buildMake
  cd buildMake
  cmake ..
  make    
  cd ../../../

  cd src_pybind/gl
  mkdir buildMake
  cd buildMake
  cmake ..
  make    
  cd ../../../

  cd src_pybind/eigen
  mkdir buildMake
  cd buildMake
  cmake ..
  make    
  cd ../../../

  pip3 install --upgrade pip setuptools
  pip3 install -e .  
  python3 setup.py install
  python3 setup.py test    
  python3 setup.py develop

  cd tests
  python3 test_cadmsh.py
  python3 test_fem.py