name: thelper
channels:
  - pytorch
  - albumentations
dependencies:
  - pytorch
  - torchvision
  - numpy
  - cython
  - matplotlib
  - opencv
  - lz4
  - scikit-learn
  - gitpython
  - mock
  - pip
  - pytest
  - pytest-cov
  - pytest-mock
  - tqdm
  - shapely
  - albumentations
  - pip:
    - h5py
    - imgaug==0.2.5
    - augmentor
    - opencv-python
    - tensorboardX
    - pynput
