
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-10T11:30:54+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "03c40d153f0dd001c9534df4b6717a047f27ce3b",
 "version": "0.6.65"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
