[tool.poetry]
name = "isp-git-hooks"
version = "0.9.0"
description = ""
authors = ["Marcel Hekking <m.hekking@isprojects.nl>"]

[tool.poetry.dependencies]
python = "^3.6"
pre-commit = "^1.17"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
flake8 = "^3.7"
pdbpp = "^0.10.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
