
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-24T15:41:09-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "44b04ca522f2a4ca96ba3da5560a7f430b8b7ce7",
 "version": "0.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
