[tool.poetry]
name = "hilde"
version = "0.3.0.dev2"
description = "Haber Institute Lattice Dynamics Environment"
authors = ["Florian Knoop <knoop@fhi-berlin.mpg.de>"]
license = "ISC"
readme = "README.md"
repository = "https://gitlab.com/flokno/hilde"

keywords = ['physics']

build = "build.py"

[tool.poetry.dependencies]
python = "^3.6, <4.0"
numpy = "^1.16"
scipy = "~1.2.1"
matplotlib = "^3.1"
son = "^0.3.2"
spglib = "^1.12"
phonopy = "^2.1"
ase = "^3.18.0"
click = "^7.0"
attrs = "^19.1"
pandas = "^0.24.2"
seekpath = "^1.8.4"
fireworks = {version = "^1.9",optional = true}
phono3py = {version = "^1.17",optional = true}
python-gssapi = {version = "^0.6.4",optional = true}
pymongo = {version = "^3.8",optional = true}
fabric = {version = "^2.4",optional = true}
paramiko = {version = "^2.4",optional = true}
psycopg2 = {version="^2.8.0", optional=true}
seaborn = {version = "^0.9.0",optional = true}
jupyter = {version = "^1.0",optional = true}
xarray = "^0.12.3"
netCDF4 = "^1.5"
click_completion = "^0.5.1"

[tool.poetry.extras]
fireworks = ["fireworks", "python-gssapi", "pymongo", "fabric", "paramiko"]
phono3py = ["phono3py"]
postgresql = ["psycopg2"]
tutorial = ["seaborn", "jupyter"]

[tool.poetry.dev-dependencies]
black = "^18.9b0"
pytest = "^4.6"
flake8 = "^3.7"
rope = "^0.14.0"

[tool.poetry.scripts]
hilde = 'hilde.cli:cli'

[tool.black]
target-version = ['py37']


[build-system]
requires = ["poetry>=0.12", "numpy"]
build-backend = "poetry.masonry.api"

