apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./../base
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: {{ project_name }}

namespace: {{ project_name }}-stage

vars:
  - name: NAMESPACE_URL
    objref:
      kind: Ingress
      name: {{ project_name }}-ingress
      apiVersion: extensions/v1beta1
    fieldref:
      fieldpath: metadata.namespace

