#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['mentormatch',
 'mentormatch.applicants',
 'mentormatch.excel_data_handling',
 'mentormatch.main',
 'mentormatch.roster',
 'mentormatch.schema',
 'mentormatch.setup',
 'mentormatch.utilities']

package_data = \
{'': ['*']}

install_requires = \
['click']

entry_points = \
{'console_scripts': ['mentormatch = mentormatch.main.cli:main']}

setup(name='mentormatch',
      version='0.1.6',
      description='J&J Cross-Sector Mentoring Program utility that matches mentors with mentees.',
      author='Jonathan Chukinas',
      author_email='chukinas@gmail.com',
      url='https://github.com/jonathanchukinas/mentormatch',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
     )
