# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-07 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmbedlyParsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('parsed', models.BooleanField(db_index=True, default=False)),
                ('parsed_datetime', models.DateTimeField(blank=True, null=True)),
                ('favicon', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=25, null=True)),
                ('version', models.CharField(blank=True, max_length=25, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_original', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('author_url', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_name', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_url', models.CharField(blank=True, max_length=255, null=True)),
                ('cache_age', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail_url', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OembedSized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('thumbnail_width', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail_height', models.PositiveIntegerField(blank=True, null=True)),
                ('html', models.TextField(blank=True, null=True)),
                ('width_returned', models.PositiveIntegerField(blank=True, null=True)),
                ('height_returned', models.PositiveIntegerField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csembedlyparser.EmbedlyParsed')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='oembedsized',
            unique_together=set([('url', 'width', 'height')]),
        ),
    ]
