# coding: utf-8

"""
    Haven Money API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import haven
from haven.models.get_webhooks_response import GetWebhooksResponse  # noqa: E501
from haven.rest import ApiException


class TestGetWebhooksResponse(unittest.TestCase):
    """GetWebhooksResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetWebhooksResponse(self):
        """Test GetWebhooksResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = haven.models.get_webhooks_response.GetWebhooksResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
