language: python
python:
- 3.5
- 3.6
install: pip install -U tox-travis
script: tox
before_deploy: make clean
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: avmo-ci
  password:
    secure: WqM1SQ4aZseG6i4wsCApaTUBeB4/ZmnVgujOyKga6NGI8YJr+7tgqAPq1K234Ejk4lGUSK21R+bJOOl7WwHlPZZQFIpD5EfTx2L8U3OJSNJ64UfgV2uX1m0V1Z1YdTwE8ofVkKOsqxCBENGCgV3AQaoJEJbjnAaQ+e9flXnbFZCa5Jyr1IQWRuqNBErD7fFJMrWkjkZ3x0FMVl8un6pSAvEiMrKa+Jdi2ZQgPdx+wSeV8VDrw9Tlu5JQ53adm4/jBIa/7rmHXJGVttMI0YdwPeUdvX4UgR27x+f0V5A7u6yJKfzV23iVR0hqrfC1fhKHiYKhV1d622i+Lu38Icn14Iu9vdEIyx2uNDIG44REb/yt346b9m55aZoI496GhC1u1UT/U7mDvwcmc+GWcpB80HNiQkp/T3j2xnFGK3qi5bavc/0ZwddKGbCHjzHoBUfpZWV+C2I6nluvXvMqbU8oVNTmbMmeQfkfo0CzRw6RSMG6SjxG8Zs/AfDzbF4ZFBLh+yCukDoncJHfalhg6KK3AN+R8KmiLMUjGRG7XC9mXL648YBtWkmysy40H7eob1akTriJCmucB+oR9IC8uZfkCv+GUydBc4m0F6NqfzcbxGCYAUkV9dVVk3RHerUqzklZnFSkFzzX7Dml37s+Pgql8NHSTN/slnPdiHNpo4oZzBk=
  on:
    tags: true
    repo: ashwinvis/xrandr-extend
    python: 3.6
