[tool.poetry]
name = "lobio"
version = "0.2.0"
description = "Extra utilities for BioPython"
authors = ["Justin Vrana <justin.vrana@gmail.com>"]
homepage = "https://www.github.com/jvrana/LoBio"
repository = "https://www.github.com/jvrana/LoBio"
documentation = "https://www.github.com/jvrana/LoBio"
readme = 'README.md'

[tool.poetry.dependencies]
python = "^3.5"
biopython = "^1.73"

[tool.poetry.dev-dependencies]
black = { version = "^19.3b0", python = "^3.6" }
pytest = "^4.1"
pre-commit = "^1.17"
toml = "^0.10.0"
tox = "^3.13"
tox-conda = "^0.2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
